dimagi/formplayer

build.gradle

formsplayer -> formplayer

---

build.gradle

just doing this in a separate PR so it's not dependent on the other stuff and staging won't break on deploy

Update build.gradle to do 1.7

---

.gitignore
src/test/resources/requests/new_form/new_form_2.json

Fixes for build

---

src/main/java/application/SessionController.java
src/main/java/beans/CurrentResponseBean.java
src/main/java/beans/EvaluateXPathRequestBean.java
src/main/java/beans/EvaluateXPathResponseBean.java
src/main/java/hq/RestoreUtils.java
src/main/java/session/FormEntrySession.java
src/main/java/util/Constants.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/CaseTests.java
src/test/java/tests/FormEntryTest.java
src/test/java/tests/SessionControllerTest.java

responses to https://github.com/dimagi/formplayer/pull/16/files#r51883783

PR responses

---

src/main/java/application/WebAppContext.java

@benrudolph this also should help with memory leaks

manually deregister JDBC drivers

---

config/application.properties.example
src/main/java/application/WebAppContext.java

See https://github.com/dimagi/commcarehq-ansible/pull/377
@benrudolph

use jedis host

---

src/main/java/session/FormplayerInstanceInitializer.java

fixes a few issues introduced by sub repo refactors

sub repo update

---

src/main/java/application/SessionController.java
src/main/java/install/FormplayerConfigEngine.java
src/main/java/session/FormSession.java
src/test/java/tests/BaseTestClass.java

Undo subrepo updates that should've have been made as part of deploy process
@benrudolph

Revert subs

---

src/main/java/application/FormController.java
src/main/java/application/MenuController.java
src/main/java/application/WebAppContext.java
src/main/java/beans/AnswerQuestionRequestBean.java
src/main/java/beans/SessionBean.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/InstallTests.java

Split up form entry and menu navigation controllers

Split controllers

---

src/main/java/application/MenuController.java
src/main/java/beans/menus/Command.java
src/main/java/beans/menus/CommandListResponseBean.java
src/main/java/session/MenuSession.java

Enable FormPlayer to differentiate form vs module commands as on mobile
cross https://github.com/dimagi/commcare-hq/pull/11793

add navState to command response

---

README.md

@wpride 
cc: @proteusvacuum @sravfeyn

Proper startup command

---

config/application.properties.example

We need to add a param to the Postgres URL for the prepareThreshold to be zero for PGBouncer
https://jdbc.postgresql.org/documentation/head/server-prepare.html

update example with threshold

---

src/main/java/session/FormSession.java
src/main/java/session/MenuSession.java
src/test/java/tests/CaseTests.java
src/test/resources/requests/filter/filter_cases_sql_escape.json

Addresses http://manage.dimagi.com/default.asp?231582
@benrudolph

scrub sql usernames

---

src/main/java/repo/impl/PostgresSessionRepo.java

Add locking to Postgres session repository

add locking to session repo

---

config/application.properties.example

@wpride i think HQ devs will find these defaults better

Better defaults for example file

---

.gitignore
build.gradle
src/main/java/application/FormplayerAuthFilter.java
src/main/java/application/UtilController.java
src/main/java/beans/ServerUpBean.java
src/main/java/util/Constants.java

@wpride look ma! i wrote java code!

server up route for formplayer

---

src/main/java/application/CORSFilter.java
src/main/java/application/WebAppContext.java

remove specific app config loading

---

build.gradle
src/main/java/application/AbstractBaseController.java
src/main/java/application/WebAppContext.java

@wpride aight fixed this email thing. pandora's box has been opened 📖  best read commit by commit

fix email sending

---

src/main/java/application/AbstractBaseController.java

@wpride tweaking them emails to give more info. can't seem to get post body which is a shame

Tweak emails to give more information

---

src/main/java/application/MenuController.java
src/main/java/session/MenuSession.java

Think this will fix some of the NPE's value labs was seeing

Don't throw NPE when we step overflow

---

src/main/java/application/FormController.java

Fix for http://manage.dimagi.com/default.asp?pre=preMultiSearch&pg=pgList&pgBack=pgSearch&search=2&searchFor=235105

Set form title on answer and repeat responses

---

src/main/java/application/AbstractBaseController.java

@wpride hoping this'll fix up some of the html email formatting. hard to tell since it already works locally for me
cc: @czue

Fix up html

---

src/main/java/beans/menus/EntityListResponse.java

cross https://github.com/dimagi/commcare-hq/pull/12851
Fixes http://manage.dimagi.com/default.asp?235189
@ctsims

don't fail on no details

---

src/main/java/beans/SessionListItem.java
src/main/java/db/migration/V3__incomplete_forms_title.java
src/main/java/objects/SerializableFormSession.java
src/main/java/repo/impl/PostgresFormSessionRepo.java
src/main/java/session/FormSession.java

@benrudolph this will cause all extant incomplete forms to display nothing, but I'm not that worried about that... you? 
cross https://github.com/dimagi/commcare-hq/pull/12839

add title and dateOpened to incomplete forms essions

---

build.gradle
src/main/java/application/AbstractBaseController.java
src/main/java/application/Application.java
src/main/java/application/FormController.java
src/main/java/application/FormplayerAuthFilter.java
src/main/java/application/MenuController.java
src/main/java/application/WebAppContext.java
src/test/java/tests/BaseTestClass.java
src/test/java/utils/TestContext.java

This should clean up most of the issues that have been coming up recently - basically, only allow a single user to be using any route at a given time.
Definitely want to clean up the FormController routes in particular - lots of shared code now. 
Also removed redundant mocking in test context

Lock API routes by user

---

src/main/java/application/WebAppContext.java

fix autowiring

---

src/main/java/application/WebAppContext.java

cross https://github.com/dimagi/commcarehq-ansible/pull/506
@benrudolph

use redis hostname properly

---

src/main/java/db/migration/V4__incomplete_forms_default.java
src/main/java/db/migration/V5__incomplete_forms_set.java
src/main/java/repo/impl/PostgresFormSessionRepo.java

Fixes https://github.com/dimagi/commcare-hq/pull/12913
Cross https://github.com/dimagi/commcare-hq/pull/12913
@benrudolph I'm not too worried about the default values since these should only ever show up for people on the test versions

Give defaults to old incomplete form sessions, sort on server side

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/MenuController.java
src/main/java/beans/menus/BaseResponseBean.java
src/main/java/beans/menus/CommandListResponseBean.java
src/main/java/beans/menus/EntityListResponse.java

Also fixes http://manage.dimagi.com/default.asp?235449
Basically we only want to save menu state when we start or finish form entry - otherwise, remain RESTful

Don't re-save menuSession during stepping

---

src/main/java/application/MenuController.java
src/main/java/beans/PreviewRequestBean.java
src/main/java/beans/SessionNavigationBean.java
src/main/java/util/Constants.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/PreviewTests.java
src/test/resources/requests/preview/preview.json
src/test/resources/requests/preview/preview_step.json

@benrudolph amazingly, this will work. Hold off merge until I can do the JS side

Preview form parameter, with tests

---

src/main/java/application/MenuController.java
src/main/java/util/SessionUtils.java

Don't rely on there being a nextScreen when determining app title (since sometime there isn't)

safely get the app title if no selections

---

src/main/java/application/MenuController.java

This will give a better error message when we end up with an invalid preview command as in http://manage.dimagi.com/default.asp?236315#1211260

Better error message with invalid preview command

---

src/main/java/beans/menus/CommandListResponseBean.java
src/main/java/util/SessionUtils.java
src/test/java/tests/DoubleManagementTest.java

Fixes http://manage.dimagi.com/default.asp?235445

Use proper helper method to get command list title

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/FormController.java
src/main/java/beans/menus/EntityListResponse.java
src/main/java/exceptions/ApplicationConfigException.java
src/main/java/exceptions/FormNotFoundException.java
src/main/java/install/FormplayerConfigEngine.java
src/main/java/repo/FormSessionRepo.java
src/main/java/repo/impl/PostgresFormSessionRepo.java
src/main/java/screens/FormplayerSyncScreen.java
src/main/java/util/PrototypeUtils.java
src/test/java/tests/BaseTestClass.java

Should prevent those "Expected 1 but found 0" exceptions that are cropping up in the 500s
Also updates our compatibility with master

Error gracefully if trying to access a form that doesn't exist

---

src/main/java/application/AbstractBaseController.java

@benrudolph yet another one we shouldn't email on (happens when something in menu nav is misconfigured)

don't email on session exception

---

config/application.properties.example
src/main/java/application/SQLiteProperties.java
src/main/java/hq/CaseAPIs.java
src/main/java/session/FormSession.java
src/main/java/util/ApplicationUtils.java
src/test/java/tests/CaseTests.java
src/test/java/tests/FilterTests.java

@wpride this allows for a configurable sqlite data dir and allow us to encrypt the data directory. test don't pass yet because i have to figureout how to inject the proper dataDir when running tests. also can't merge this until settings are updated. 
cc: @dannyroberts

configurable sqlite dir

---

src/main/java/application/SQLiteProperties.java

@wpride didn't test this syntax out well enough. we can just take out

Fix dbs path

---

build.gradle
src/main/java/beans/menus/Entity.java
src/main/java/beans/menus/EntityListResponse.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/DoubleManagementTest.java
src/test/resources/requests/navigators/navigator_0.json
src/test/resources/requests/preview/preview_step.json

@benrudolph here's the backend for this change, hold off on merge until frontend is fixed. 
cross https://github.com/dimagi/commcare-hq/pull/13106

Use case_id instead of index when selecting case

---

src/main/java/beans/EvaluateXPathResponseBean.java
src/test/java/tests/FormEntryTest.java

@wpride this catches xpath errors appropriately (allows debugger to handle them more gracefully)
cc: @wpride

catch xpath errors

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/MenuController.java

Fixes http://manage.dimagi.com/default.asp?236976

Respect search and pagination after end of form navigation

---

src/test/java/tests/InstallTests.java

make case select test actually do something

---

src/main/java/application/AbstractBaseController.java
src/main/java/beans/menus/BaseResponseBean.java
src/main/java/session/FormplayerInstanceInitializer.java
src/main/java/session/MenuSession.java

cross https://github.com/dimagi/commcare-hq/pull/13159

Add version info to all menu responses

---

src/main/java/beans/QuestionBean.java

@wpride adds the control type to the answer response
needs this commit: https://github.com/dimagi/commcare-core/commit/ca6aba7468d3df40170c4543059228bf185ccc54

Add control type to answer

---

scripts/gitutils.py
scripts/rebuildstaging
scripts/rebuildstaging.py
scripts/sh_verbose.py
scripts/staging.yaml

@wpride this'll allow us to have the same workflow in HQ to commit to autostaging. we just need a jenkins config that will make a build off that branch. right now you'll have to HQ virtualenv
@dannyroberts do you feel like there's some future state where this staging module will be more applicable to more of our projects. i thought for a bit about making it a pip project so it could easily be installed and used on the command line

Staging V1

---

config/application.properties.example
src/main/java/application/WebAppContext.java
src/main/java/util/Constants.java

@wpride need this for it to work on staging (should still work on prod)

use database name

---

build.gradle
src/main/java/application/AbstractBaseController.java
src/main/java/beans/menus/DetailResponse.java
src/main/java/beans/menus/EntityDetailResponse.java
src/main/java/beans/menus/EntityListResponse.java
src/main/java/beans/menus/MenuBean.java
src/test/java/tests/CaseTilesTest.java

Actually this is gtg
cross-request: https://github.com/dimagi/commcare-hq/pull/13204

Persistent Case Tiles

---

src/main/java/application/FormController.java
src/main/java/beans/JumpToIndexRequestBean.java
src/main/java/beans/NewSessionRequestBean.java
src/main/java/db/migration/V6__formsessions_oqps.java
src/main/java/objects/SerializableFormSession.java
src/main/java/repo/impl/PostgresFormSessionRepo.java
src/main/java/services/NewFormRequest.java
src/main/java/session/FormSession.java
src/main/java/util/Constants.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/CaseTests.java
src/test/java/tests/FormEntryTest.java
src/test/java/tests/GroupTests.java
src/test/resources/requests/new_form/new_form_oqps.json
src/test/resources/xforms/oqps.xml

Formplayer allow one question per screen

---

src/main/java/beans/EvaluateXPathResponseBean.java

Catch xpath xyntax error in evaluate xpath method

---

src/main/java/util/ApplicationUtils.java

@wpride wipe dbs was failing cause we weren't scrubbing the username

Fix wipe dbs

---

src/main/java/beans/InstallRequestBean.java
src/main/java/repo/impl/PostgresFormSessionRepo.java

update the session currentIndex in postgres

---

src/main/java/application/UtilController.java

Fix for http://manage.dimagi.com/default.asp?235897#1212358
Just doing a quick fix since this will also be addressed in https://github.com/dimagi/formplayer/pull/140/files
@benrudolph

Scrub username before syncing db

---

src/main/java/application/AbstractBaseController.java

Don't need to email on this one

don't email on fixture too large exception

---

src/main/java/application/AbstractBaseController.java
src/main/java/beans/BaseExceptionResponseBean.java
src/main/java/beans/ExceptionResponseBean.java
src/main/java/beans/HTMLExceptionResponseBean.java
src/main/java/exceptions/FormattedApplicationConfigException.java
src/main/java/install/FormplayerConfigEngine.java
src/main/java/util/Constants.java

@wpride this'll add the ability to handle html error returned from commcarehq

Error html

---

src/main/java/application/FormController.java
src/main/java/session/FormSession.java

fyi for @wpride 
along with https://github.com/dimagi/commcare-core/pull/415
attempts to fix the issue where a question is answered in oneQuestionPerScreen mode and the whole question list is sent back rather than the current question

handle one question per screen on question answer

---

src/main/java/application/MenuController.java

Fixes http://manage.dimagi.com/default.asp?238620
cc @benrudolph

Clear app DB when previewing a form

---

src/main/java/application/FormController.java
src/main/java/beans/FormEntryNavigationResponseBean.java
src/main/java/session/FormSession.java

- handle submit in one question per screen mode
- know if index is end of form
related: https://github.com/dimagi/commcare-hq/pull/13441
@wpride @benrudolph 
cc @orangejenny

One Question Per Screen Updates

---

src/main/java/application/FormController.java
src/main/java/util/Constants.java

@wpride this'll delete a session
cc: @orangejenny

Route to delete session

---

src/main/java/application/AbstractBaseController.java
src/main/java/beans/exceptions/BaseExceptionResponseBean.java
src/main/java/beans/exceptions/ExceptionResponseBean.java
src/main/java/beans/exceptions/HTMLExceptionResponseBean.java
src/main/java/beans/exceptions/RetryExceptionResponseBean.java
src/main/java/exceptions/AsyncRetryException.java
src/main/java/services/impl/RestoreServiceImpl.java
src/main/java/util/Constants.java
src/test/java/tests/AsyncRestoreTest.java
src/test/resources/restores/async_restore_response.xml

@wpride this implements the backend code needed to handle async restores. frontend handling is still a work in progress. We can go ahead and merge this is as though since async restores itself is behind a feature flag
cc: @orangejenny

Async restores

---

src/main/java/db/migration/V9__menu_session_as_user.java

Had conflicting merge file versions :(

Rename file to change version

---

src/main/java/services/RestoreFactory.java

Scrub username in restoreFactory

---

src/main/java/beans/SyncDbRequestBean.java
src/main/java/services/RestoreFactory.java

fix restore as url and param issues

---

src/main/java/beans/menus/EntityBean.java
src/main/java/beans/menus/EntityListResponse.java
src/test/java/tests/CasePaginationTests.java

WIP, implements case list sorting
~~TODO~~
Could be merged without those if we want this though

Case List Sorting in Nimbus

---

config/application.properties.example
src/main/java/application/AbstractBaseController.java

@wpride this'll add the environment to emails so staging and production emails will thread separately. hold off on merge, needs ansible component

Add hq environment to emails

---

src/main/java/application/FormplayerAuthFilter.java

Old CloudCare puts the username in a different place than Nimbus

get the username from old cloudcare requests

---

src/main/java/application/FormplayerAuthFilter.java

Comment on username

---

src/main/java/application/DebuggerController.java
src/main/java/application/WebAppContext.java
src/main/java/beans/InstanceXmlBean.java
src/main/java/beans/debugger/DebuggerFormattedQuestionsResponseBean.java
src/main/java/services/FormattedQuestionsService.java
src/main/java/services/impl/FormattedQuestionsServiceImpl.java
src/main/java/util/Constants.java
src/main/java/util/XmlUtils.java

Debugger Route

---

src/main/java/install/FormplayerConfigEngine.java

Get us up to date with the most recent core code. Don't merge until Monday, I don't want this lingering over the weekend without us online since these changes can manifest subtly/weirdly

Merge commcare-core 2.31 to Nimbus

---

src/main/java/application/DebuggerController.java
src/main/java/beans/debugger/DebuggerFormattedQuestionsResponseBean.java
src/main/java/beans/debugger/QuestionResponseItem.java
src/main/java/services/FormattedQuestionsService.java
src/main/java/services/impl/FormattedQuestionsServiceImpl.java

Add question list in addition to html form data

---

src/main/java/application/FormController.java
src/main/java/application/MenuController.java
src/main/java/application/UtilController.java
src/main/java/application/WebAppContext.java
src/main/java/aspects/LoggingAspect.java

Another aspect, this one handles logging the call and return of all methods that request a URL mapping

Aspect for logging API calls

---

src/main/java/aspects/LoggingAspect.java

Will address the current server-up errors with Formplayer

Fix logging for requests with no body

---

src/main/java/annotations/UserLock.java
src/main/java/application/AbstractBaseController.java
src/main/java/application/FormController.java
src/main/java/application/MenuController.java
src/main/java/application/WebAppContext.java
src/main/java/aspects/LockAspect.java

Remake of https://github.com/dimagi/formplayer/pull/155 but using Java configuration and some other changes
Weaves a function to handle locking and unlocking around method exception, allowing us to remove much cruft code

UserLock Aspect

---

src/main/java/engine/FormplayerConfigEngine.java
src/main/java/services/impl/InstallServiceImpl.java

@benrudolph this will allow us to return the pretty errors again

re-add formlayer config engine to return install errors

---

build.gradle
src/main/java/application/FormplayerAuthFilter.java
src/main/java/application/UtilController.java
src/main/java/util/Constants.java

The idea here is to get rid of the current form translate jar and rather have HQ just call this endpoint to do form validation. 
What do you think?
@benrudolph @wpride

add form validation endpoint

---

src/main/java/application/MenuController.java
src/main/java/beans/menus/MenuBean.java
src/main/java/beans/menus/UpdateRequestBean.java
src/main/java/services/RestoreFactory.java
src/main/java/session/FormSession.java
src/main/java/session/MenuSession.java
src/test/java/tests/BaseTestClass.java

cross-request https://github.com/dimagi/commcare-hq/pull/14004

Route for app updates and reloading form session

---

src/main/java/services/impl/InstallServiceImpl.java

contains https://github.com/dimagi/formplayer/pull/199/files

Reuse application DBs

---

src/main/java/services/impl/InstallServiceImpl.java

Revert "Reuse application DBs"

---

src/main/java/services/impl/InstallServiceImpl.java

Revert "Revert "Reuse application DBs""

---

src/main/java/aspects/LockAspect.java
src/main/java/util/Constants.java

Increase lockout timeout

---

.travis.yml
config/application.properties.example
src/main/java/application/DebuggerController.java
src/main/java/application/FormController.java
src/main/java/application/WebAppContext.java
src/main/java/beans/debugger/DebuggerFormattedQuestionsResponseBean.java
src/main/java/beans/debugger/XPathQueryItem.java
src/test/java/tests/BaseTestClass.java
src/test/java/utils/TestContext.java

@wpride caches xpath queries in redis

Cache XPath queries in Redis

---

src/main/java/services/FormplayerStorageFactory.java
src/main/java/services/RestoreFactory.java

@benrudolph hurray for continued learning

Make factories have request scope

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

got some cool new features, in particular Continuous Build.
https://docs.gradle.org/2.5/release-notes#new-and-noteworthy

upgrade gradle to 2.5

---

.travis.yml
README.md
build.gradle
config/application.properties.example
src/test/java/tests/FormValidatorTests.java
src/test/resources/form_validation/bad_ref.xml
src/test/resources/form_validation/valid_form.xml
src/test/resources/logback-test.xml

@benrudolph @wpride 
buddyeis @millerdev @nickpell 
I'd forgotten how painful Java can be!

form validation tests

---

src/main/java/session/FormSession.java

@benrudolph / @wpride 
fixes http://manage.dimagi.com/default.asp?239709

OQPS: Skip first index if it is a Group

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/WebAppContext.java

Make smtp credentials optional, default to empty string

---

src/test/java/tests/FormValidatorTests.java
src/test/resources/form_validation/cycle.xml

@benrudolph 
cc @nickpell @millerdev

improve tests and add test for dependency cycle

---

src/main/java/application/Application.java
src/main/java/application/WebAppContext.java
src/main/java/services/FormplayerStorageFactory.java
src/main/java/services/RestoreFactory.java
src/main/java/services/impl/InstallServiceImpl.java

Update annotations so that they actually work :+1:

Request scope fix

---

src/test/java/tests/RegressionTests.java

This was bubbling up as that weird contextualizeRef() null pointer

Fix for entity list selection not resolving

---

src/main/java/beans/SessionNavigationBean.java

Mostly wanted the previewCommand value in the toString for logging

SessionNavigationBean cleanup

---

src/main/java/application/MenuController.java
src/main/java/aspects/LockAspect.java
src/main/java/beans/AuthenticatedRequestBean.java

@wpride did a couple function moving around while diving into some of the menu navigation, but the main part of this PR is adding the restoreAs to the redis lock. Realized that if i'm using restore as with `randomuser` it means i'm also blocked from any other user which is kind of annoying though not too big of a deal

Lock with username and restoreAs

---

src/main/java/application/WebAppContext.java
src/main/java/aspects/MetricsAspect.java

@wpride this didn't work which was disappointing. trying to figure out why not, but in the mean time i realized the tags could be better

better tags and use recordExecution time

---

src/main/java/aspects/MetricsAspect.java

@wpride this should do the trick

Check args length

---

src/main/java/application/AbstractBaseController.java
src/main/java/aspects/MetricsAspect.java
src/main/java/util/Constants.java

Adding some more metrics. I'm envisioning a crash report dashboard @wpride @snopoke

Metrics for errors

---

src/main/java/hq/CaseAPIs.java
src/main/java/services/RestoreFactory.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/CasePaginationTests.java
src/test/java/tests/CaseTilesTest.java
src/test/java/tests/DeleteApplicationDbsTests.java
src/test/java/tests/DoubleManagementTest.java
src/test/java/tests/FilterTests.java
src/test/java/tests/GroupTests.java
src/test/java/tests/LocalizationTests.java
src/test/java/tests/NewFormTests.java
src/test/java/tests/PreviewTests.java
src/test/java/tests/RegressionTests.java
src/test/java/tests/RepeatTests.java

@czue @wpride http://manage.dimagi.com/default.asp?245357#1272630 I _think_ this is the root cause. trying to validate. next step is figuring out if it's safe to deploy formplayer. we may need to make a PR off of the commit deployed to icds

Make force restore overwrite cache

---

src/main/java/beans/menus/EntityListResponse.java

I don't know why this existed (XpathException is a RuntimeException already)

Don't catch and rethrow RunTime

---

src/main/java/application/WebAppContext.java

revert b63bf06c8bb1ac09bc4fe90688ee8e1f3f01be70

---

config/application.properties.example

changed app properties account info @NoahCarnahan @proteusvacuum

changed application properties account info

---

.travis.yml
.travis/application.config.example
.travis/application.properties.example

use separate travis config

---

src/main/java/hq/CaseAPIs.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/session/MenuSession.java

This was causing some timeouts on prod, we should only bust the cache when the sync button is used

Be more specific about when to bust restore cache

---

src/main/java/services/impl/InstallServiceImpl.java

This still won't work for remote profile installs (but won't regress anything)

Allow profile reference in installReference

---

src/main/java/annotations/NoLogging.java
src/main/java/application/UtilController.java
src/main/java/aspects/LoggingAspect.java

Let's take back control of our logs!

Don't log validate requests

---

src/main/java/application/UtilController.java
src/main/java/beans/SyncDbRequestBean.java

@wpride @czue this adds an option to preserve the restore cache. necessary for async restore

preserveCache option

---

src/main/java/beans/FormEntryResponseBean.java
src/main/java/beans/SessionListItem.java

This has been bothering me in the logs

add session list item tostring

---

src/main/java/application/FormController.java

We need to configure the storageFactory in the FormController routes now due to https://github.com/dimagi/formplayer/pull/260

Need to set storageFactory now for form controller apis

---

src/main/java/session/MenuSession.java

@benrudolph this should cause us to display a proper error message and nav backwards when the 'null' ends up in the url (somehow)

Catch and rethrow NPE

---

src/main/java/application/FormController.java

Revert "Need to set storageFactory now for form controller apis"

---

src/main/java/application/IncompleteSessionController.java
src/main/java/beans/GetSessionsResponse.java
src/main/java/beans/SessionListItem.java
src/main/java/session/FormSession.java

Should give us performance and robustness wins

Don't instantiate formsession object for each session

---

src/main/java/application/AbstractBaseController.java

For this guy http://manage.dimagi.com/default.asp?245627

better error message for case sharing group messup

---

src/main/java/application/WebAppContext.java
src/main/java/hq/CaseAPIs.java
src/main/java/services/RestoreFactory.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/RestoreFactoryTest.java
src/test/java/utils/TestContext.java

@wpride this makes formplayer respect HQ's sync frequency http://manage.dimagi.com/default.asp?245997
cc: @emord

Respect sync freq

---

src/main/java/beans/AuthenticatedRequestBean.java
src/main/java/beans/DeleteApplicationDbsRequestBean.java

Nothing worse than not having these in the logs when you need them

Add missing toString methods

---

src/main/java/application/FormController.java
src/main/java/util/Constants.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/CaseTests.java
src/test/java/tests/FilterTests.java
src/test/java/tests/FormEntryTest.java

Broken here, not sure how this build passed https://github.com/dimagi/formplayer/pull/272

fix for tests broken when TF rotues removed

---

src/main/java/beans/QuestionBean.java

@wpride adds hint text to question json
cc: @emord

Add hint text to question json

---

src/main/java/beans/menus/EntityListResponse.java
src/test/java/tests/DoubleManagementTest.java

cross-request: https://github.com/dimagi/formplayer/pull/282

Handle multiple case list actions

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/FormController.java
src/main/java/application/FormplayerAuthFilter.java
src/main/java/application/IncompleteSessionController.java
src/main/java/application/MenuController.java
src/main/java/application/UtilController.java
src/main/java/auth/TokenAuth.java
src/main/java/beans/AuthenticatedRequestBean.java
src/main/java/hq/models/PostgresUser.java
src/main/java/hq/models/SessionToken.java
src/main/java/repo/impl/CouchUserRepo.java
src/main/java/repo/impl/PostgresUserRepo.java
src/main/java/util/Constants.java
src/main/java/util/UserUtils.java
src/test/java/tests/UserUtilsTests.java

Reverts dimagi/formplayer#287 @wpride this ended up being dependent on migration that i forgot that i had run, so when i tested this on master hq, it seemed to work fine. however the production database didn't have a table that it was expecting

Revert "Revert "Anonymous Web Apps usage""

---

src/main/java/application/AbstractBaseController.java

Really this is the wrong exception to be thrown but the fix is deep in the engine and I don't think this will ever be a "real" 500 so

Ignore this goddamn exception

---

src/main/java/application/FormplayerAuthFilter.java

@wpride it's super confusing when a blank response is returned when the request is invalid. this gives the response body a message.
Before:
```
HTTP/1.1 401
Content-Length: 0
Date: Thu, 16 Feb 2017 14:09:07 GMT
```
After:
```
HTTP/1.1 401
Content-Type: application/json;charset=ISO-8859-1
Transfer-Encoding: chunked
Date: Thu, 16 Feb 2017 14:11:30 GMT
{"error":"Invalid session id"}
```

Write response when we get an authorized request

---

src/test/java/tests/CasePaginationTests.java

don't add empty rows if the data is null/blank

No empty details

---

src/main/java/application/WebAppContext.java
src/main/java/util/Constants.java

@wpride i caved and increased the timeout to match HQ

Increase timeout

---

src/main/java/application/FormController.java
src/main/java/application/MenuController.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/session/FormSession.java
src/main/java/session/FormplayerInstanceInitializer.java
src/main/java/session/FormplayerSessionWrapper.java
src/main/java/session/MenuSession.java
src/test/java/tests/CaseTests.java
src/test/java/tests/FormEntryTest.java
src/test/java/tests/NewFormTests.java
src/test/resources/requests/new_form/edit_user_data.json
src/test/resources/requests/new_form/new_form_4.json
src/test/resources/restores/edit_user_data.xml
src/test/resources/test_restore.xml
src/test/resources/xforms/edit_user_data.xml

And some other cleanup/refactoring
cross-request: https://github.com/dimagi/commcare-hq/pull/15174

Edit forms fix

---

src/main/java/services/NewFormResponseFactory.java

@wpride this ensure we do a restore on editing a form

Force restore when loading a new form

---

src/main/java/application/FormController.java
src/main/java/objects/FunctionHandler.java
src/main/java/objects/SessionData.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/session/FormSession.java
src/main/java/session/MenuSession.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/CaseTests.java
src/test/java/tests/EditTest.java
src/test/java/tests/FormEntryTest.java
src/test/java/tests/GroupTests.java
src/test/java/tests/NewFormTests.java
src/test/java/tests/RepeatTests.java
src/test/resources/requests/new_form/edit_form.json
src/test/resources/xforms/edit_form.xml

Add handling for static functions to be used for edit forms
Fixes https://manage.dimagi.com/default.asp?247788
cross-request: https://github.com/dimagi/commcare-core/pull/529

Add static function handling

---

src/main/java/beans/menus/CommandListResponseBean.java

@wpride this adds the layout style (grid, list, or null) to the response. necessary for https://github.com/dimagi/commcare-hq/pull/15312 to work

Add layout style to command response

---

src/test/java/tests/EditTest.java
src/test/resources/requests/new_form/edit_image.json
src/test/resources/xforms/edit_image.xml

Fixes https://manage.dimagi.com/default.asp?249073#1299220
Before, for binary type questions, Formplayer would return null as the answer. However, this makes editing forms with required binary-type questions impossible as they will be treated as unanswered, even when they have been. This returns the string path of the binary file (IE "1488964254571.jpg")
@ctsims @benrudolph curious if you know of any possible side effects of this

For binary questions return answer text

---

.gitignore
src/main/java/beans/CaseFilterRequestBean.java
src/main/java/db/migration/V12__drop_restore_xml_column.java
src/main/java/hq/CaseAPIs.java
src/main/java/objects/SerializableFormSession.java
src/main/java/repo/impl/PostgresFormSessionRepo.java
src/main/java/repo/impl/PostgresMigratedFormSessionRepo.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/services/RestoreFactory.java
src/main/java/session/FormSession.java
src/test/java/mocks/MockFormSessionRepo.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/FormEntryTest.java
src/test/java/tests/PreviewTests.java

Ok @wpride I'm feeling better about this. Can be read commit by commit. This completely removes restoreXml and removes some complexity. The conversion to using streams is in the second commit

Stream response 2

---

src/main/java/application/MenuController.java
src/main/java/application/UtilController.java
src/main/java/beans/DeleteApplicationDbsRequestBean.java
src/main/java/util/ApplicationUtils.java
src/test/java/tests/ApplicationUtilsTests.java

fixes https://manage.dimagi.com/default.asp?249750#1304393

Fix delete DBs for as user

---

src/main/java/database/models/FormplayerCaseIndexTable.java
src/main/java/sandbox/UserSqlSandbox.java

Fix for these `java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "SELECT": syntax error)`

Fix for indexing operation that happens for large case list loads

---

README.md

@wpride @snopoke some updates to the docs

Contributing process

---

README.md

@wpride @snopoke feedback from last PR to make updating CC version more clear

make docs more clear

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/MenuController.java
src/main/java/beans/menus/EntityListResponse.java

@wpride @ctsims quick POC on the case detail optimization. this loads enikshay case details in less than a second. hold off on merge right now, i want to add some comments and do a little organization

Do not process all entities for a single entity

---

src/main/java/services/InstallService.java
src/main/java/services/impl/InstallServiceImpl.java

@benrudolph This should finally stop the annoying UnresolvedResourceException (app config) emails. Just let the typed exception through instead of re-throwing as a runtime

Let UnresolvedResourceException through, don't email

---

src/main/java/beans/menus/Style.java

cross with https://github.com/dimagi/commcare-hq/pull/15735

widthHint is always int

---

src/main/java/application/AbstractBaseController.java
src/main/java/exceptions/UnresolvedResourceRuntimeException.java
src/main/java/services/impl/InstallServiceImpl.java

Unresolved Resource Exception

---

src/main/java/application/MenuController.java
src/main/java/screens/FormplayerSyncScreen.java
src/main/java/session/MenuSession.java

@proteusvacuum @ctsims @benrudolph 
fixes https://manage.dimagi.com/default.asp?252448#1321136

Fix Case Claim for Login As Users

---

src/main/java/services/FormplayerStorageFactory.java

This log statement was polluting

Remove polluting log statement

---

src/main/java/engine/FormplayerConfigEngine.java

@wpride seeing lots of different types of errors on ICDS. this handles them more gracefully

handle more errors

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/MenuController.java
src/main/java/beans/menus/EntityDetailListResponse.java

Fixes https://manage.dimagi.com/default.asp?252775
cross-request: https://github.com/dimagi/commcare-hq/pull/15959

Return persistent case tile when asked for detail not on case list

---

src/main/java/services/impl/QueryRequesterImpl.java

Log query request response

---

build.gradle
src/main/java/application/Application.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/FormValidatorTests.java

Revert "Update plugin versions, update deprecated classes"

---

src/main/java/application/AbstractBaseController.java
src/main/java/services/impl/SyncRequesterImpl.java

help to address https://manage.dimagi.com/default.asp?253902

Logging around sync requests and external errors

---

src/main/java/application/MenuController.java
src/main/java/application/UtilController.java

@benrudolph think for the time being we should revert back to our previous behavior of restoring fresh 😢  seems like this isn't playing nicely with case claim

switch back to forcing restore for both case claim and manual sync

---

.travis.yml
src/main/java/application/MenuController.java
src/main/java/application/UtilController.java
src/main/java/hq/CaseAPIs.java
src/main/java/services/RestoreFactory.java
src/main/java/util/UserUtils.java

Revert "Incremental Sync Episode II"

---

src/main/java/application/DebuggerController.java
src/main/java/beans/EvaluateXPathResponseBean.java
src/main/java/beans/debugger/AutoCompletableItem.java
src/main/java/beans/debugger/DebuggerFormattedQuestionsResponseBean.java
src/main/java/beans/debugger/InstanceAutocompletableItem.java
src/test/java/tests/FormEntryTest.java

@wpride @ctsims this serializes nodes returned to the debugger in XML. i've already found it to be very useful. it also adds autocomplete options for instance declarations if it knows them. hold off on merge as it needs to be formatted properly on HQ side

Serialize nodes

---

src/main/java/services/RestoreFactory.java

Add device_id param to Formplayer sync requests

---

src/main/java/api/json/PromptToJson.java

Remove datetime

---

.travis.yml
build.gradle

Attempted fix from https://discuss.gradle.org/t/gradle-travis-sudo-false-leads-to-an-error/17034/3

Try forking with gradle

---

src/main/java/api/json/PromptToJson.java

fixes https://manage.dimagi.com/default.asp?256187

Error when adding choice with spaces

---

src/main/java/beans/debugger/InstanceAutocompletableItem.java

better instance auto complete

---

src/main/java/api/json/PromptToJson.java

Revert "Remove datetime"

---

src/main/java/api/json/PromptToJson.java

Spaces are valid in single-select answer values

Only apply space check to multi-selects

---

src/main/java/aspects/UserRestoreAspect.java
src/main/java/beans/AuthenticatedRequestBean.java
src/main/java/hq/CaseAPIs.java
src/main/java/services/RestoreFactory.java
src/main/java/util/PropertyUtils.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/RestoreFactoryTest.java

cross-request: https://github.com/dimagi/commcare-hq/pull/16859
cc @ctsims @millerdev

Respect LiveQuery application configuration

---

src/main/java/hq/CaseAPIs.java
src/test/resources/restores/case_create.xml
src/test/resources/restores/dbtests/case_create_index.xml
src/test/resources/restores/dbtests/case_db_model_query.xml
src/test/resources/restores/dbtests/case_test_db_optimizations.xml

@ctsims Just comparing to the Android code looks like this `purgeCases()` call is possibly the missing element

Purge cases after syncing

---

src/main/java/application/WebAppContext.java

remove abandoned threads

---

.travis.yml
src/main/java/engine/FormplayerCaseInstanceTreeElement.java

cross-request: https://github.com/dimagi/commcare-core/pull/612

CommCare 2.37 on Formplayer

---

src/main/java/util/FormplayerRaven.java

Forgot to PR this, from a while ago
@wpride

Fix getAppUrl()

---

src/main/java/application/UtilController.java
src/main/java/util/ApplicationUtils.java
src/main/java/util/Constants.java

@ctsims @wpride route to clear the user's data. note this wipes everything (applications and user restore). frontend coming soon
cc: @proteusvacuum

Route to clear the user's data

---

src/main/java/services/RestoreFactory.java
src/main/java/util/FormplayerRaven.java

@wpride @ctsims 
buddy: @proteusvacuum

Add a few more details to sentry

---

src/main/java/services/impl/InstallServiceImpl.java
src/main/java/sqlitedb/SQLiteDB.java

Should be checking whether parent directory exists rather than DB itself

Check database path rather than folder

---

src/main/java/sandbox/SqliteIndexedStorageUtility.java

@ctsims think this is all we need

use boolean iterator

---

build.gradle
scripts/archive_dbs.sh

follow-up to https://github.com/dimagi/formplayer/pull/452 after testing and @emord's comment

make updates to archive_dbs.sh for prod

---

src/main/java/application/AbstractBaseController.java

Gets us inline with Android
cc @ctsims

Clear volatiles after popping session

---

config/application.example.properties
src/main/java/application/Application.java
src/main/java/application/WebAppContext.java

We can remove this dependency since @snopoke auth service refactor
Thanks @esoergel

Remove couch

---

src/main/java/aspects/MetricsAspect.java

buckets are (in both lexical and numerical order):
- `lt_001s`
- `lt_005s`
- `lt_020s`
- `lt_060s`
- `lt_120s`
- `over_120s`
I chose these buckets to match the ones in https://app.datadoghq.com/dash/74381/hq-vitals?live=true&page=0&is_auto=false&from_ts=1503660835264&to_ts=1503675235264&tile_size=m's "Restore Count by Time Bucket" graph (`commcare.restores.count` metric), and added the `lt_001s` bucket, since it's more relevant in formplayer's case as it supports a realtime web interface.

add duration buckets to datadog requests metric

---

src/main/java/application/AbstractBaseController.java
src/main/java/aspects/LockAspect.java
src/main/java/aspects/MetricsAspect.java
src/main/java/util/Constants.java

- make error metrics `request` tag a little nicer
- log lock timeouts and expiries to datadog

Datadog metrics

---

src/main/java/engine/FormplayerConfigEngine.java

fixes https://manage.dimagi.com/default.asp?260966#1385367

Give more actionable error message

---

src/main/java/application/AbstractBaseController.java
src/main/java/aspects/LockAspect.java
src/main/java/util/FormplayerRaven.java

and also add an `as_user` tag to sentry reports

Send lock expiry to sentry

---

src/main/java/aspects/MetricsAspect.java

I'm guessing we'll get about ~15-30 of these from production and ~3-18 of these from enikshay a day at this point. It'll give us a chance to dig into what's causing the slowness in each case, whether there are certain problem users that get a disproportionate number of them, etc.

send info for long running requests to sentry

---

src/main/java/application/WebAppContext.java
src/main/java/aspects/AppInstallAspect.java
src/main/java/aspects/LoggingAspect.java
src/main/java/aspects/MetricsAspect.java
src/main/java/services/RestoreFactory.java

turns out `BreadcrumbBuilder` is a builder

clean up builder syntax for sentry breadcrumbs

---

src/main/java/application/WebAppContext.java
src/main/java/aspects/AppInstallAspect.java
src/main/java/aspects/LoggingAspect.java
src/main/java/aspects/MetricsAspect.java
src/main/java/services/RestoreFactory.java
src/main/java/util/FormplayerRaven.java
src/test/java/tests/FormplayerRavenTest.java

Re-did this in a way that doesn't cause https://manage.dimagi.com/default.asp?261639 (failing on null values in data).
I'm going to see if I can write a test into this that would have caught the other bug.

try 2: clean up builder syntax for sentry breadcrumbs

---

src/main/java/aspects/LockAspect.java

My initial attempt (#472) didn't cause any problems but doesn't produce the correct metrics either—I put the code around the wrong line. This should fix it. Tested locally that everything still works.

put lock timing around the correct line

---

src/main/java/api/process/FormRecordProcessorHelper.java
src/main/java/application/FormController.java
src/main/java/services/CategoryTimingHelper.java
src/main/java/util/Constants.java

Add timings for https://manage.dimagi.com/default.asp?262477

add purge_cases category timings

---

src/main/java/beans/menus/EntityDetailResponse.java
src/test/java/tests/InlineCaseTilesTest.java

Fixes https://manage.dimagi.com/default.asp?262073#1397185
Jackson expects setters to be in an exact format, which my Intellij auto-complete was not respecting. Rookie mistake. Added regression test.

Persistent inline fix

---

src/main/java/aspects/LockAspect.java
src/main/java/aspects/MetricsAspect.java
src/main/java/services/CategoryTimingHelper.java
src/main/java/util/FormplayerRaven.java
src/main/java/util/RequestUtils.java

This should fix some blank/null metrics we've been receiving on datadog from enikshay ever since https://github.com/dimagi/formplayer/pull/484 was deployed yesterday afternoon.

Fix request injection

---

src/main/java/application/AbstractBaseController.java

Provides a better error message for https://manage.dimagi.com/default.asp?261017

Check for null reference

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/MenuController.java
src/main/java/beans/InstallRequestBean.java
src/main/java/hq/CaseAPIs.java
src/main/java/services/InstallService.java
src/main/java/session/MenuSession.java
src/test/java/mocks/TestInstallService.java

To bring parity with Android
requested https://manage.dimagi.com/default.asp?262821

Perform restore after Web Apps update

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/DebuggerController.java
src/main/java/application/FormController.java
src/main/java/application/MenuController.java
src/main/java/application/WebAppContext.java
src/main/java/services/FormplayerFormSendCalloutHandler.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/session/FormSession.java
src/main/java/session/MenuSession.java
src/main/java/util/PrototypeUtils.java
src/test/java/utils/TestContext.java

cross-request/context in https://github.com/dimagi/commcare-core/pull/653/files
cc @ctsims @esoergel

Support for requests during form entry

---

src/main/java/exceptions/SQLiteRuntimeException.java
src/main/java/hq/CaseAPIs.java
src/main/java/sandbox/SqlHelper.java
src/main/java/sandbox/SqliteIndexedStorageUtility.java

Addresses https://manage.dimagi.com/default.asp?262124
When encountering a SQL issue during restore, attempt to wipe the databases and retry the restore once.

SQLException Restore Retries

---

src/main/java/hq/CaseAPIs.java

Addresses two issues with previous retry PR:
1. When we retry, we need to get a fresh input stream
2. When we retry we need to clear the databases

Clear DBs on restore failure

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/DebuggerController.java
src/main/java/application/FormController.java
src/main/java/application/MenuController.java
src/main/java/screens/FormplayerQueryScreen.java
src/main/java/services/FormattedQuestionsService.java
src/main/java/services/FormplayerFormSendCalloutHandler.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/services/RestoreFactory.java
src/main/java/services/SubmitService.java
src/main/java/services/XFormService.java
src/main/java/session/MenuSession.java
src/test/java/tests/BaseTestClass.java

...and move `getHeaders()` function into RestoreFactory to centralize concerns. Includes commits from https://github.com/dimagi/formplayer/pull/496 so might be cleaner if that's merged first.

Include sync token in form submissions

---

build.gradle
src/main/java/application/AbstractBaseController.java
src/main/java/application/WebAppContext.java
src/main/java/aspects/AppInstallAspect.java
src/main/java/aspects/LockAspect.java
src/main/java/aspects/LoggingAspect.java
src/main/java/aspects/MetricsAspect.java
src/main/java/services/CategoryTimingHelper.java
src/main/java/services/RestoreFactory.java
src/main/java/util/FormplayerSentry.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/FormplayerRavenTest.java
src/test/java/utils/TestContext.java

Per https://docs.sentry.io/clients/java/migration/

Change Sentry library, migrate to new class names

---

src/main/java/application/MenuController.java
src/main/java/application/UtilController.java
src/main/java/aspects/UserRestoreAspect.java
src/main/java/hq/CaseAPIs.java
src/main/java/services/CategoryTimingHelper.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/session/MenuSession.java
src/main/java/util/SimpleTimer.java
src/main/java/util/Timing.java

Still want to test this locally, but wanted to PR this basic idea.

More comprehensive purge timing

---

src/main/java/beans/menus/EntityListResponse.java

Gives better error for https://manage.dimagi.com/default.asp?264352#1412404

Throw informative error

---

config/application.example.properties
src/main/java/beans/NewFormResponse.java
src/main/java/beans/menus/EntityListResponse.java
src/main/java/services/QueryRequester.java
src/main/java/util/SessionUtils.java

Noticed are logs are now getting unwieldy within 24 hours. This trims down on some of the bigger frequent logs (that I've also never found really useful):
- Logging the entire question tree
- Logging all case list entities and menu list commands
- Logging entire case claim query response

Log Cleanup

---

src/main/java/application/MenuController.java
src/main/java/aspects/UserRestoreAspect.java
src/main/java/hq/CaseAPIs.java
src/main/java/services/NewFormResponseFactory.java
src/main/java/services/RestoreFactory.java
src/main/java/session/MenuSession.java
src/main/java/util/Constants.java

This adds separate timings for the download and parsing of the restore file

Add download restore and parse restore timings

---

src/main/java/session/FormSession.java

Greys out the "Previous" button correctly when display condition is false on first question

Set isFirstIndex in walking method

---

src/main/java/util/PrototypeUtils.java

Adds `distinct-values` function in core
cross-request: https://github.com/dimagi/commcare-core/pull/676
@ctsims not sure how you want to handle announce or this?

Add distinct-values function

---

src/main/java/api/process/FormRecordProcessorHelper.java
src/main/java/beans/GetSessionsResponse.java
src/main/java/beans/SessionListItem.java
src/main/java/database/models/FormplayerCaseIndexTable.java
src/main/java/engine/FormplayerCaseInstanceTreeElement.java
src/main/java/engine/FormplayerLedgerInstanceTreeElement.java
src/main/java/hq/CaseAPIs.java
src/main/java/parsers/FormplayerBulkCaseXmlParser.java
src/main/java/sandbox/JdbcSqlStorageIterator.java
src/main/java/sandbox/SqlStorage.java
src/main/java/sandbox/UserSqlSandbox.java
src/main/java/services/FormplayerStorageFactory.java
src/main/java/services/RestoreFactory.java
src/main/java/session/FormSession.java
src/main/java/session/FormplayerInstanceInitializer.java
src/main/java/util/SessionUtils.java
src/test/java/tests/CaseClaimTests.java
src/test/java/tests/CaseTests.java
src/test/java/tests/FilterTests.java
src/test/java/tests/ReassignCaseTest.java
src/test/java/tests/sandbox/SqlStorageIndexedTests.java

This name has been bugging me forever. PR just changes the name.

Rename SQLiteIndexedStorageUtility -> SqlStorage

---

src/main/java/application/AbstractBaseController.java
src/main/java/application/FormplayerAuthFilter.java
src/main/java/application/WebAppContext.java
src/main/java/aspects/LockAspect.java
src/main/java/exceptions/InterruptedRuntimeException.java
src/main/java/services/FormplayerLockRegistry.java

Revert "Revert "JVM-level locking""

---

src/main/java/application/DebuggerController.java
src/main/java/beans/EvaluateXPathMenuRequestBean.java
src/main/java/beans/EvaluateXPathRequestBean.java
src/main/java/beans/EvaluateXPathResponseBean.java
src/main/java/util/Constants.java
src/test/java/tests/BaseTestClass.java

Allow formplayer to respond to xpath eval requests with structured trace responses.
Requires:
https://github.com/dimagi/commcare-core/pull/678

Improved Debugger Responses

---

Dockerfile
config/application.docker.properties
config/set_webhost

This PR adds a Dockerfile that pulls the latest build from Jenkins, and uses the example application properties as a default config.
The idea of compiling as part of the build is definitely up for debate. I chose this approach because I figured it would be the quickest way to get a docker image for developers.
(I'm not sure whether the couch connection is still necessary.)
cc @millerdev @ctsims

Dockerfile

---

Dockerfile
config/application.docker.properties

Follows up on discussion at corresponding [PR on HQ](https://github.com/dimagi/commcare-hq/pull/18584).
@wpride cc @millerdev @nickpell

Use ports 801x to avoid conflicts

---

src/main/java/repo/impl/PostgresFormSessionRepo.java
src/main/java/repo/impl/PostgresMigratedFormSessionRepo.java

This will remove form sessions that are older than one week old. Runs every time Formplayer boots up.

Purge stale form sessions

---

src/main/java/repo/impl/PostgresFormSessionRepo.java

Revert "Purge stale form sessions"

---

README.md

@wpride @dannyroberts cc @nickpell

Update README for FormPlayer in Docker

---

README.md

(Oof, sorry @wpride . I got the nested list formatting wrong. :roll_eyes: )

Markdown numbering nitpick

---

src/main/java/services/RestoreFactory.java

If sync frequency returns null, default to not requiring a sync
fixes https://manage.dimagi.com/default.asp?268659
Thanks @kaapstorm

Check for sync frequency null

---

src/main/java/services/NewFormResponseFactory.java

configure the storage manager in NewFormResponseFactory

---

src/main/java/application/IncompleteSessionController.java

Fixes https://manage.dimagi.com/default.asp?269177
PR forthcoming that will centralize `StorageFactory` configuration in one aspect

Configure StorageFactory for incomplete session

---

src/main/java/application/FormController.java
src/main/java/beans/GetInstanceResponseBean.java
src/main/java/beans/RawInstanceResponseBean.java
src/main/java/util/Constants.java
src/test/java/tests/BaseTestClass.java
src/test/java/tests/FormEntryTest.java

Route needed by SMS forms. 
CC @gcapalbo

Implement get-instance for SMS forms

---

src/main/java/api/json/PromptToJson.java

SMS tests were exposing this bug. Not sure why this was this way previously but this seems correct-er.

PromptToJson long handling

---

src/main/java/application/Application.java
src/test/java/tests/BaseTestClass.java

cross-request: https://github.com/dimagi/commcare-core/pull/757

Add LocalizerManager class, set to usethreadLocal for Formplayer

---

src/main/java/application/Application.java
src/main/java/engine/ClasspathFileRoot.java
src/main/java/engine/FormplayerConfigEngine.java

cross-request: https://github.com/dimagi/commcare-core/pull/761
implements static/thread-local shared pattern for `ReferenceManager`

ReferenceManagerHandler refactor

---

src/main/java/beans/menus/EntityListResponse.java
src/main/java/util/EntityStringFilterer.java

And some changes to remove unused variables/code from Android - can see that here d57e9f2
cross-request: https://github.com/dimagi/commcare-core/pull/759

Move EntityStringFilterer into formplayer

---

src/main/java/application/FormController.java

Not sure why we weren't doing this already, but should be validating answers on submission for one question per screen just like in normal mode. Addresses https://manage.dimagi.com/default.asp?271268

Validate OQPS answers on submission

---

src/main/java/application/FormController.java

Revert "Validate OQPS answers on submission"

---

src/main/java/application/IncompleteSessionController.java
src/main/java/services/FormplayerStorageFactory.java
src/main/java/services/NewFormResponseFactory.java

the `StorageManager` class should use the same `CASE*` username format as the `RestoreFactory` class

StorageManager should respect restoreAsCaseId username

---

src/main/java/application/MenuController.java
src/main/java/session/MenuSession.java

Allow Formplayer to update an application instead of always deleting DBs and re-installing. PR appears strange because a lot of this code was merge but unused already; majority of code changes are error handling. 
cross-request: https://github.com/dimagi/commcare-core/pull/785

App updates for Formplayer

---

src/main/java/repo/impl/PostgresFormSessionRepo.java

Was running into an issue where people who wiped their DBs could not get `formplayer` to start because this code ran before the migration re-created the DB. Broad fix because we should not crash on session purge since this would block the application from starting; instead, log the issue.

Don't crash for exceptions during session purge

---

src/main/java/sandbox/UserSqlSandbox.java

cross-request: https://github.com/dimagi/commcare-core/pull/772

Update Formplayer to 2.43

---

src/main/java/util/Constants.java

Don't merge until [this PR](https://github.com/dimagi/commcare-hq/pull/20654) is merged
This will force all users to sync again which will ensure that SMS users get the code changes above

Increment SQLite DB version for SMS

---

src/main/java/application/UtilController.java

addresses https://manage.dimagi.com/default.asp?277481
Check for nullity of edges before running DFS
Also, log when the `validate` call crashes
cross-request https://github.com/dimagi/commcare-core/pull/812

Fix ShortestCycleAlgorithm bug

---

src/main/java/application/FormplayerAuthFilter.java
src/main/java/services/HqUserDetailsService.java
src/main/java/util/Constants.java
src/main/java/util/RequestUtils.java

Implements HMac Verification of requests from Touchforms
Partner of https://github.com/dimagi/commcare-hq/pull/20916

Implement HMac verification for Touchforms requests

---

src/main/java/services/MenuSessionRunnerService.java
src/main/java/session/MenuSession.java

determines whether or not it's a clmi in the same way [commcare-android](https://github.com/dimagi/commcare-android/blob/fa8737adac20d1e2b378313313164fa323934bda/app/src/org/commcare/activities/EntityDetailActivity.java#L99) does it. then it steps back to the case list.
https://manage.dimagi.com/default.asp?281324
@emord

fixes end of form navigation bug

---

src/main/java/beans/menus/EntityListResponse.java

use long detail for detail screen

---

src/main/java/beans/menus/Command.java
src/main/java/beans/menus/CommandListResponseBean.java

makes it easier to use on the client side.

Move badges into respective command in CommandListResponseBean

---

.gitignore
build.gradle
src/main/java/beans/EvaluateXPathResponseBean.java
src/main/java/engine/FormplayerConfigEngine.java
src/main/java/installers/FormplayerOfflineUserRestoreInstaller.java
src/main/java/sandbox/SqlHelper.java
src/main/java/session/FormplayerInstanceInitializer.java
src/main/java/session/MenuSession.java

Refactoring for commcare-core changes. 
Sets Java to Java8

Formplayer 2.45

---

src/main/java/services/RestoreFactory.java
src/main/java/util/FormplayerSentry.java

NullPointerException on staging caused by null username
in restore factory since it isn't configured when the
exception is raised
buddies @kaapstorm @emord

check if RestoreFactory configured before using it

---

src/main/java/beans/menus/Command.java
src/main/java/util/SessionUtils.java

Formplayer changes for https://github.com/dimagi/commcare-android/pull/2111/files

Adds support to use instance variables in Menu text xpath

---

src/main/java/database/models/EntityStorageCache.java
src/main/java/database/models/FormplayerCaseIndexTable.java
src/main/java/engine/FormplayerIndexedFixtureInstanceTreeElement.java
src/main/java/sandbox/SqlHelper.java
src/main/java/sandbox/SqlStorage.java
src/main/java/sandbox/UserSqlSandbox.java
src/main/java/session/FormplayerInstanceInitializer.java
src/main/java/util/Constants.java
src/main/java/util/SerializationUtil.java

Also adds support for non-string values in sql insert operations. 
Corresponding Android PR: https://github.com/dimagi/commcare-android/pull/2085
cross-request: https://github.com/dimagi/commcare-core/pull/858

Adds Support for Root level attribute lookup for Indexed Fixtures 

---

src/main/java/services/InstallService.java

https://dimagi-dev.atlassian.net/browse/MOB-94

Improves error

---

src/main/java/engine/FormplayerConfigEngine.java

Jira: https://dimagi-dev.atlassian.net/browse/MOB-110
Shows associated 500 error message from response if available on app downloads requests.

Error Improvement

---

.gitignore
scripts/rebuildstaging
scripts/rebuildstaging-requirements.txt
scripts/rebuildstaging.py
scripts/sh_verbose.py
scripts/staging.yaml

Document and flesh out rebuildstaging workflow

---

.travis/application.example.properties
config/application.docker.properties
config/application.example.properties
src/main/java/application/Application.java
src/main/java/application/WebAppContext.java
src/main/resources/application.properties

This will need to wail until the config changes have been pushed out: https://github.com/dimagi/commcare-cloud/pull/3377

let spring manage the DB datasource

---

.travis/application.example.properties
config/application.docker.properties
config/application.example.properties
src/main/java/application/WebAppContext.java

Tested locally (unit tests mock out redis)

support redis password

---

src/main/java/session/MenuSession.java

Makes two fairly small changes with big performance payoffs. Should make page loads when entity lists are in the thousands about 5x faster.
1) We redundantly request the Current Screen definition from scratch quite a bit. Long term we could do a higher level cache, but this introduces caching for at least the most expensive unit of calculation (the entity list screen) so that it isn't recalculated 3-4 times per request.
2) In commcare-core  (PR linked below) - use the same basic bulk query context hints / cues that we use on Android to make bulk entity loading more efficient.
For consistency https://github.com/dimagi/commcare-core/pull/884 should be accepted and pulled before this PR

[In Development] Performance Optimizations for Lists

---

src/main/java/services/RestoreFactory.java

When in "sync after submit"mode, force a sync on session refresh if state by 20 minutes.

Permit more aggressive autosync

---

src/main/java/services/RestoreFactory.java

Set aggressive sync timing from 20 mins to 5 mins (on Nestle's request)

Update Aggressive Sync times

---

src/main/java/aspects/MetricsAspect.java
src/main/java/util/SimpleTimer.java

JIRA: https://dimagi-dev.atlassian.net/browse/SAAS-10832

Use time in seconds for getDurationBucket method call

---

scripts/staging.md

Add documentation for how to deploy a set of branches to staging through the rebuildstaging process

Document rebuildstaging

---

src/main/java/org/commcare/formplayer/services/ScheduledTasks.java

Small PR as a followup to https://github.com/dimagi/formplayer/pull/761 that changes schedule default to midnight daily.

change purge task default schedule to midnight

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java

These are a couple changes required for https://github.com/dimagi/commcare-hq/pull/28463
I am not totally sure if there are other steps I need to take (first formplayer PR), but let me know

change form language

---

src/main/java/org/commcare/formplayer/api/json/PromptToJson.java

Needed for https://github.com/dimagi/commcare-hq/pull/28484

Added appearance attribute to json representation of groups

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/session/MenuSession.java

This is the formplayer half of https://github.com/dimagi/commcare-core/pull/937
Opening for review, but it cannot be merged until that is merged and the commcare-core reference in the formplayer repo is updated.

use minimal entity screen for case lists

---

src/main/java/org/commcare/formplayer/services/BrowserValuesProvider.java

Fixes an error on my part for not logging the error message.  Also updates commcare-core to latest [5cb31](https://github.com/dimagi/commcare-core/commits/formplayer).
FYI @calellowitz this will also bring in your commcare-core changes.

timezone error message and updated cc-core

---

scripts/rebuildstaging-requirements.txt

See https://github.com/dimagi/commcare-hq/pull/28563/

Uninstalled enum34

---

src/main/java/org/commcare/formplayer/services/BrowserValuesProvider.java
src/test/java/org/commcare/formplayer/tests/BrowserValuesProviderTest.java

Browser tz test fix to accomodate for DST by fixing the date for tests.

browser tz provider test fix

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
src/main/java/org/commcare/formplayer/services/RestoreFactory.java
src/main/java/org/commcare/formplayer/util/Constants.java

Adding some more timing to datadog

add new datadog timings

---

src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
src/main/java/org/commcare/formplayer/services/InstallService.java
src/main/java/org/commcare/formplayer/services/RestoreFactory.java
src/main/java/org/commcare/formplayer/services/SubmitService.java
src/test/java/org/commcare/formplayer/tests/SubmitServiceTests.java

Followup to https://github.com/dimagi/formplayer/pull/795

add domain to more metrics

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/session/FormSession.java

https://dimagi-dev.atlassian.net/browse/USH-480

Read autosubmit pragma and send it in the response

---

src/main/java/org/commcare/formplayer/services/RestoreFactory.java

Reverts dimagi/formplayer#805 since still in QA.

Revert "url encode loginas"

---

src/main/java/org/commcare/formplayer/session/MenuSession.java

Followup for https://github.com/dimagi/formplayer/pull/783/

Added function comments [ci skip]

---

.github/labels.yml

This will help standardise the labels across HQ and Formplayer.

add labels config

---

src/main/java/org/commcare/formplayer/application/DebuggerController.java
src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
src/main/java/org/commcare/formplayer/session/FormSession.java
src/main/java/org/commcare/formplayer/util/FormplayerSentry.java

[JIRA Ticket](https://dimagi-dev.atlassian.net/browse/USH-612)
To improve analysis of formplayer requests, add a tag with the form title as the value for form related requests that get sent to Sentry.

Add form name tag to sentry when creating form session

---

build.gradle

See https://github.com/dimagi/formplayer/pull/827 for changes etc.

Bump jsonpath version

---

build.gradle

https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-devtools

add spring boot devtools

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
src/main/java/org/commcare/formplayer/services/RestoreFactory.java
src/main/java/org/commcare/formplayer/util/Constants.java
src/main/java/org/commcare/formplayer/util/FormplayerSentry.java

In addition to adding the call to `FormplayerDatadog` to add the `form_name` tag, I consolidated some string constants. Tested on staging.

Use datadog wrapper to add form_name tag

---

src/main/java/org/commcare/formplayer/session/FormSession.java
src/main/java/org/commcare/formplayer/util/serializer/FormDefStringSerializer.java

more miscellaneous refactoring

---

src/main/java/org/commcare/formplayer/session/MenuSession.java

Passing an unresolved reference (`null`) to `installService.configureApplication` causes a NullPointerException.
This was introduced by https://github.com/dimagi/formplayer/pull/849

Use resolved install reference

---

build.gradle
src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
src/main/java/org/commcare/formplayer/session/FormSession.java
src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java

Revert "only update changing fields when saving form sessions"

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/beans/NewFormResponse.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
src/main/java/org/commcare/formplayer/session/FormSession.java
src/test/java/org/commcare/formplayer/tests/RepeatTests.java
src/test/resources/xforms/repeat_model_iteration.xml

https://dimagi-dev.atlassian.net/browse/USH-707

fix repeat bug caused by side effects in `getFullFormJSON`

---

.travis.yml
src/main/java/org/commcare/formplayer/database/models/EntityStorageCache.java
src/main/java/org/commcare/formplayer/database/models/FormplayerCaseIndexTable.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresApplicationDB.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresDB.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresDBPath.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresDatabaseHelper.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresSqlHelper.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresTableBuilder.java
src/main/java/org/commcare/formplayer/sandbox/PostgresDB.java
src/main/java/org/commcare/formplayer/sandbox/SqlHelper.java
src/main/java/org/commcare/formplayer/sandbox/SqlStorage.java
src/main/java/org/commcare/formplayer/services/FormplayerStorageFactory.java
src/main/java/org/commcare/formplayer/sqlitedb/DBPath.java
src/main/java/org/commcare/formplayer/sqliteutil/SqliteSqlHelper.java
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
src/test/java/org/commcare/formplayer/tests/DeleteApplicationDbsTests.java
src/test/java/org/commcare/formplayer/tests/sandbox/CaseAPITests.java

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11691
This is the first PR in the step of [migrating sqlite dbs to postgres](https://dimagi-dev.atlassian.net/browse/SAAS-11690)(Note the base branch is beta). 
The goal of this PR is to make application DB work with postgres while user DB still uses sqlite.

Sqlite to postgres

---

src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java

https://dimagi-dev.atlassian.net/browse/QA-2563
Depends on HQ PR https://github.com/dimagi/commcare-hq/pull/29214

Added URL encoding to case claim URL

---

.travis.yml
scripts/docker_deploy.sh

Build docker image and push to dockerhub.
Making the gradle build work on Dockerhub is tricky so I went with this approach.

formplayer docker build

---

src/main/java/org/commcare/formplayer/engine/FormplayerConfigEngine.java
src/main/java/org/commcare/formplayer/services/InstallService.java

Similar to https://github.com/dimagi/formplayer/pull/914, this makes use of the global rest template so that it can take advantage of the url re-writing in docker (Also it's just much cleaner).

use restTemplate to download ccz

---

src/main/java/org/commcare/formplayer/installers/FormplayerInstallerFactory.java
src/main/java/org/commcare/formplayer/installers/FormplayerLocaleInstaller.java
src/main/java/org/commcare/formplayer/installers/SimpleInstaller.java
src/main/java/org/commcare/formplayer/util/PrototypeUtils.java

https://dimagi-dev.atlassian.net/browse/SAAS-11840

formplayer locale installer to always save locale data in the application DB

---

src/main/java/org/commcare/formplayer/application/WebAppContext.java

This error handling isn't needed and is actually reconfigured resulting in incorrect error responses.

remove custom error handling

---

src/main/java/org/commcare/formplayer/session/MenuSession.java

Very minor cleanup that should not result into any changes today with auto launch functionality but can potentially be harmful if remained unaddressed.

AutoLaunch cleanup

---

build.gradle
src/main/java/org/commcare/formplayer/postgresutil/PostgresApplicationDB.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresDB.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresProperties.java
src/main/java/org/commcare/formplayer/postgresutil/PostgresSqlHelper.java
src/main/java/org/commcare/formplayer/sandbox/SqlHelper.java
src/main/java/org/commcare/formplayer/sandbox/SqlStorageWrapper.java
src/main/java/org/commcare/formplayer/services/FormplayerStorageFactory.java
src/main/java/org/commcare/formplayer/sqlitedb/SQLiteDB.java

https://dimagi-dev.atlassian.net/browse/SAAS-11692
This PR is on top of https://github.com/dimagi/formplayer/pull/813 and is a continuation to the goal of migrating app DB to postgres. 
It'll add a wrapper around SqlStorage so that we can write to both sqlite and postgres and at the same time compare the performance of the two. The wrapper is used for app db only.

Adds a wrapper around connection handler for dual writing to sqlite and postgres

---

src/main/java/org/commcare/formplayer/api/process/FormRecordProcessorHelper.java
src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
src/main/java/org/commcare/formplayer/services/RestoreFactory.java
src/main/java/org/commcare/formplayer/util/Constants.java

https://dimagi-dev.atlassian.net/browse/USH-818
In case of case purge failing due to cycles in case graph, forces a fresh sync in order to try resolve the cycles and In case of no resolution throws an error. 
cross-request: https://github.com/dimagi/commcare-core/pull/985

Break out of case purge in case of cycles

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
src/main/java/org/commcare/formplayer/util/FormplayerSentry.java

[USH-826](https://dimagi-dev.atlassian.net/browse/USH-826)
Publish DD metrics in addition to recording the timings as Sentry breadcrumbs.

record DD metrics for answer timings

---

src/main/java/org/commcare/formplayer/objects/SessionData.java
src/test/resources/old_incomplete_session.json
src/test/resources/requests/filter/filter_cases_4.json
src/test/resources/requests/new_form/edit_form.json
src/test/resources/requests/new_form/edit_image.json
src/test/resources/requests/new_form/edit_user_data.json
src/test/resources/requests/new_form/new_form.json
src/test/resources/requests/new_form/new_form_2.json
src/test/resources/requests/new_form/new_form_3.json
src/test/resources/requests/new_form/new_form_4.json
src/test/resources/requests/new_form/new_form_group.json
src/test/resources/requests/new_form/new_form_oqps.json

Companion to https://github.com/dimagi/commcare-hq/pull/29589

remove unused 'additional_filters'

---

build.gradle
src/main/java/org/commcare/formplayer/auth/HmacAuthFilter.java
src/main/java/org/commcare/formplayer/beans/auth/FeatureFlagChecker.kt
src/main/java/org/commcare/formplayer/beans/auth/HqUserDetailsBean.java
src/test/java/org/commcare/formplayer/tests/HqUserDetailsTests.java
src/test/java/org/commcare/formplayer/utils/WithHqUser.java
src/test/java/org/commcare/formplayer/utils/WithHqUserSecurityContextFactory.java

https://dimagi-dev.atlassian.net/browse/USH-807
cross-request: https://github.com/dimagi/formplayer/pull/964

Feature flag checker for Formplayer, Kotlin Support

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java

https://dimagi-dev.atlassian.net/browse/USH-903

Remove claim success message

---

src/main/java/org/commcare/formplayer/beans/menus/DisplayElement.java
src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java

@shubham1g5 
cross-request: https://github.com/dimagi/commcare-core/pull/996
https://docs.google.com/document/d/1n34UU73EMFe5EnbtIaLXsIeFOHY3J3iXnf27GOZhBQE/edit#

Add hidden attr to query prompt and display

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/util/Constants.java
src/test/java/org/commcare/formplayer/tests/EndpointLaunchTest.java

PR into https://github.com/dimagi/formplayer/pull/984/

Smart linking: check feature flag

---

src/main/java/org/commcare/formplayer/session/MenuSession.java

Tiny, noticed while doing research on the CLI.

Removed unused variable

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
src/main/java/org/commcare/formplayer/beans/FormEntryResponseBean.java
src/main/java/org/commcare/formplayer/util/Constants.java

https://dimagi-dev.atlassian.net/browse/USH-1023
Adds `answersToValidate` in the request to `answer` endpoint.  While answering a question, Formplayer validates these additional answers and in case of errors return `errors` in the response. 
QA - https://dimagi-dev.atlassian.net/browse/QA-3310
Web Apps - https://github.com/dimagi/commcare-hq/pull/30100

Validates additional answers when answering a question

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java

PR into https://github.com/dimagi/formplayer/pull/984
Update exception handling to support https://github.com/dimagi/commcare-core/pull/1025
Old message
New message

Updated endpoint args exception handling

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
src/main/java/org/commcare/formplayer/beans/FormEntryResponseBean.java
src/main/java/org/commcare/formplayer/util/Constants.java

Reverts dimagi/formplayer#988
https://dimagi-dev.atlassian.net/browse/SUPPORT-10458
See also https://github.com/dimagi/commcare-hq/pull/30271

Revert "Validates additional answers when answering a question"

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/beans/AnswerQuestionRequestBean.java
src/main/java/org/commcare/formplayer/beans/FormEntryResponseBean.java
src/main/java/org/commcare/formplayer/util/Constants.java

Reverts dimagi/formplayer#995
@shubham1g5 confirmed that this can be deployed without the HQ portion and it won't affect what users see until the HQ side is deployed

Revert "Revert "Validates additional answers when answering a question""

---

src/main/java/org/commcare/formplayer/util/FormplayerGraphUtil.java

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-12570
Updates c3 to the latest version ~ 0.7.20 and
d3 to ~ 5.16.0

Update c3 and d3

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java

PR into https://github.com/dimagi/formplayer/pull/984
https://dimagi-dev.atlassian.net/browse/QA-3392

Added logic for setting menu session data to startFormEntry

---

src/main/java/org/commcare/formplayer/session/FormSession.java

I'm not sure this is the best location for these docs but it seemed reasonable to have them alongside the actual keys.
Apart from the volatility indicators I don't see any external docs for these, should we create some somewhere?

add docs for form pragmat's

---

src/main/java/org/commcare/formplayer/session/FormplayerInstanceInitializer.java
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
src/test/java/org/commcare/formplayer/tests/FormEntryWithQueryTests.java

companion to https://github.com/dimagi/commcare-core/pull/1053
minor alternative proposed to : https://github.com/dimagi/formplayer/pull/1022

Case Template persistence refactor

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java

PR into https://github.com/dimagi/formplayer/pull/1028
Formplayer side of https://github.com/dimagi/commcare-hq/pull/30702

Removed logic adding session variables to smart link

---

build.gradle

The previous version breaks on Java8
https://github.com/n0mer/gradle-git-properties/issues/195

upgrade gradle-git-properties plugin

---

src/main/java/org/commcare/formplayer/application/MenuController.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java

https://dimagi-dev.atlassian.net/browse/USH-1341 / https://dimagi-dev.atlassian.net/browse/USH-1432

Smart links: don't aggressively sync

---

src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
src/main/java/org/commcare/formplayer/application/GlobalDefaultExceptionHandler.java
src/main/java/org/commcare/formplayer/application/UtilController.java
src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
src/main/java/org/commcare/formplayer/beans/auth/HqUserDetailsBean.java
src/main/java/org/commcare/formplayer/configuration/WebSecurityConfig.java
src/main/java/org/commcare/formplayer/util/FormplayerDatadog.java
src/main/java/org/commcare/formplayer/util/NotificationLogger.java
src/test/java/org/commcare/formplayer/auth/HmacAuthTests.java
src/test/java/org/commcare/formplayer/auth/SessionAuthTests.java
src/test/java/org/commcare/formplayer/tests/FormValidatorAuthTests.java
src/test/java/org/commcare/formplayer/utils/TestContext.java

Builds on https://github.com/dimagi/formplayer/pull/1046 with the goal of adding a test for the auth changes.
The refactors allow for easier testing by reducing the dependencies that are required by the controller. I'd like to split the controllers up more but that's for another day.
Best reviewed by commit.
(redo of https://github.com/dimagi/formplayer/pull/1049 after messing up a rebase)

refactor and tests for #1046

---

src/main/java/org/commcare/formplayer/services/FormplayerLockRegistry.java

I'm hoping this will give a bit more insight into some of the locking issues and help in debugging.
Jira: https://dimagi-dev.atlassian.net/browse/SUPPORT-12171

add more detail to lock locking & check for hash collisions

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

cross-request: https://github.com/dimagi/commcare-core/pull/1065/files

Gradle 7 update

---

.ide_settings/codestyles/CommCare Coding Style.xml
checkstyle.xml

https://github.com/dimagi/commcare-core/pull/1075

Bump max line length to 115

---

src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
src/main/java/org/commcare/formplayer/util/PrototypeUtils.java

Cross request from https://github.com/dimagi/commcare-core/pull/1078
There are no function changes here and no support for the list query data type either since that is blocked by the code to produce the 'selected-cases' instance.

formplayer changes related to list query data support

---

src/main/java/org/commcare/formplayer/session/FormplayerInstanceInitializer.java

Cross request from https://github.com/dimagi/commcare-core/pull/1083

update to handle unwrapped session instance

---

src/main/java/org/commcare/formplayer/session/MenuSession.java
src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
src/test/resources/archives/multi_select_case_list/modules-0/forms-0.xml
src/test/resources/archives/multi_select_case_list/modules-0/forms-1.xml
src/test/resources/archives/multi_select_case_list/suite.xml

Fixes and tests EOF Navigation with a multi-select Entity List
cross-request: https://github.com/dimagi/commcare-core/pull/1091

Multi Select Case Lists - EOF Navigation

---

src/main/java/org/commcare/formplayer/db/migration/V23__init_entities_selection.java
src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
src/main/java/org/commcare/formplayer/services/RestoreFactory.java
src/main/java/org/commcare/formplayer/session/MenuSession.java
src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
src/test/resources/archives/case_claim_with_multi_select/suite.xml

Some minor fixes that came up during testing. 
https://github.com/dimagi/commcare-core/pull/1097

Fixes for multi select Case list

---

src/main/java/org/commcare/formplayer/session/MenuSession.java

PR into https://github.com/dimagi/formplayer/pull/1109
Depends on https://github.com/dimagi/commcare-core/pull/1105

Added breadcrumb support for MultiSelectEntityScreen

---

src/main/java/org/commcare/formplayer/sandbox/SqlStorage.java

Relates to https://github.com/dimagi/commcare-core/pull/1113

Update cc-core reference and implement getPrototype

---

src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/session/MenuSession.java
src/main/java/org/commcare/formplayer/util/SessionUtils.java

Based on comments [here](https://github.com/dimagi/formplayer/pull/1109#pullrequestreview-984801534)
cross-request: https://github.com/dimagi/commcare-core/pull/1114

Menu session clean up [No Op]

---

src/main/java/org/commcare/formplayer/application/MenuController.java
src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/session/MenuSession.java

https://dimagi-dev.atlassian.net/browse/USH-2059
cross-request: https://github.com/dimagi/commcare-core/pull/1116

Skip evaluating Entity Detail fields if current request is not for Entity Detail Screen

---

gradle/wrapper/gradle-wrapper.properties

Required by newer plugin versions e.g. https://github.com/dimagi/formplayer/pull/1157

upgrade gradle to 7.4.2

---

src/main/java/org/commcare/formplayer/application/FormSubmissionController.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java

Reverts dimagi/formplayer#1162
Reverting due to https://dimagi-dev.atlassian.net/browse/QA-4290

Revert "clear volatile session elements after stack ops"

---

src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java
src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java

https://dimagi-dev.atlassian.net/browse/QA-4291
Bug introduced here: https://github.com/dimagi/formplayer/commit/3acf594db028783135f0c20687954d66f2993115

use key without namespace in instance source

---

src/main/java/org/commcare/formplayer/application/FormSubmissionController.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java

Reverts dimagi/formplayer#1163
The QA issues have been resolved or else deemed not related to this change.

Revert "Revert "clear volatile session elements after stack ops""

---

src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java
src/main/java/org/commcare/formplayer/repo/VirtualDataInstanceRepo.java
src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
src/test/java/org/commcare/formplayer/repo/VirtualDataInstanceRepoTest.java
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java

pure code refactor with no functional changes

rename field and make mock service behave like the real one

---

src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java

Reverts dimagi/formplayer#1169
https://dimagi-dev.atlassian.net/browse/SUPPORT-13909

Revert "capture new root"

---

build.gradle
src/main/java/org/commcare/formplayer/configuration/CacheConfiguration.java
src/main/resources/application.properties

https://dimagi-dev.atlassian.net/browse/USH-2210

expire case search cache 60s after last access

---

src/main/resources/application.properties

https://sentry.io/organizations/dimagi/issues/3407319750/
https://dimagi-dev.atlassian.net/browse/SAAS-13723

add missing cache

---

src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java

https://dimagi-dev.atlassian.net/browse/USH-2267
https://github.com/dimagi/commcare-core/pull/1142

Itemset tests 

---

README.md

Added cc-core test example to README

---

.github/workflows/build.yml
.gitignore
build.gradle
gradle.properties
settings.gradle

Reverts dimagi/formplayer#1233
This way of specifying versions isn't supported by dependabot.

Revert "move plugin versions to gradle.properties"

---

src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationParentChildTests.java
src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java

Tests for Entity Detail Screen to complement safety coverage for https://github.com/dimagi/commcare-core/pull/1156

Detail tests

---

.github/workflows/build.yml
.github/workflows/publish_docker.yml

This only impacts the build and includes no code changes.

Update github actions to resolve deprecation warnings

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/test/java/org/commcare/formplayer/tests/RegressionTests.java

Trying to get more info on https://dimagi-dev.atlassian.net/browse/USH-2576
N/A
N/A

Logs cc session exception to Sentry

---

src/main/java/org/commcare/formplayer/services/FormplayerFormSendCalloutHandler.java
src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java

API changes based on https://github.com/dimagi/commcare-core/pull/1176

Changes for Master Backmerge

---

src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
src/main/java/org/commcare/formplayer/services/FormplayerRemoteInstanceFetcher.java

Changes for https://github.com/dimagi/commcare-core/pull/1215

[No Op] Refactoring for instance loading methods

---

.github/workflows/publish_docker.yml

This updates the CI/CD workflow to use Java 17 instead of 8.

Set Java to version 17

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java

Needed because of changes [here](https://github.com/dimagi/commcare-core/pull/1227)
Bunch of tests testing for correct request data for case search screen.
None

call getQueryParams as getRequestData is no longer there

---

.gitignore
scripts/commit-staging
scripts/rebuildstaging
scripts/staging.md
scripts/staging.yaml

Moves the staging configuration file into the staging-branches repository, similar to what was done in commcare-hq.
Staging workflow only.

Reference formplayer-staging.yml in staging-branches

---

README.md

Change run config instructions

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Build tools update 
cross-request: https://github.com/dimagi/commcare-core/pull/1274

update to gradle 8

---

src/main/java/org/commcare/formplayer/beans/auth/HqUserDetailsBean.java
src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/util/Constants.java
src/test/java/org/commcare/formplayer/junit/request/MockRequest.kt
src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java

Attach query response to entity response when the `SPLIT_SCREEN_CASE_SEARCH` ff is enabled.
Minor change, behind a FF with good test coverage overall.
Not planning QA for the FP part, overall feature will be QA'ed later with the UI changes
cross-request: https://github.com/dimagi/commcare-core/pull/1282

Split Screen Case Search Support

---

src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/test/java/org/commcare/formplayer/junit/Installer.kt

Minor cleanup for [this PR](https://github.com/dimagi/formplayer/pull/1396/files#r1222531522) 
No Op
No

[No op] Removes the overided method only used in test

---

src/main/java/org/commcare/formplayer/services/MediaValidator.kt
src/main/resources/application.properties

jira ticket: https://dimagi-dev.atlassian.net/browse/USH-3276
HQ PR: https://github.com/dimagi/commcare-hq/pull/33099
this increases the maximum file upload size to 4MB
small change to size limit
if this PR is reverted the corresponding HQ PR should also be reverted. https://github.com/dimagi/commcare-hq/pull/33099

increase file upload size limit to 4MB

---

src/main/java/org/commcare/formplayer/beans/menus/EntityBean.java
src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
src/test/java/org/commcare/formplayer/tests/CaseGroupingTests.java
src/test/resources/archives/case_list_auto_select/suite.xml
src/test/resources/restores/casegroup.xml

[Spec](https://docs.google.com/document/d/1me7aYlJTijDuUP7jC2-yJFwG86h8QUoOBSyWUOuU4uY/edit?disco=AAAAzg4TzNU)
Changes are well abstracted, behind tests and will be QA'ed
https://dimagi-dev.atlassian.net/browse/QA-5265
core: https://github.com/dimagi/commcare-core/pull/1298

Implements Entity List Grouping 

---

src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java

https://github.com/dimagi/commcare-core/pull/1319 added required validation on FP which is now causing FP tests with required condition to fail. This PR makes test changes to fix them.
Only tests

Required validation test fixes

---

src/main/java/org/commcare/formplayer/application/FormController.java
src/main/java/org/commcare/formplayer/session/FormSession.java
src/main/java/org/commcare/formplayer/util/Constants.java
src/test/java/org/commcare/formplayer/junit/request/ClearMediaQuestionRequest.kt
src/test/java/org/commcare/formplayer/tests/MediaCaptureTest.kt

jira ticket: https://dimagi-dev.atlassian.net/browse/USH-3582
spec doc: https://docs.google.com/document/d/1lRYWe-IRUWN7OTYK9mVvGYhPoy_Wo85NnF0dooSw1rY/edit#heading=h.d7s2sycdfk92
hq PR: https://github.com/dimagi/commcare-hq/pull/33443
changes restricted to feature flag
tested locally and on staging
no QA planned
If this PR is reverted the related hq PR should also be reverted, as `clear_answer` requests will fail.

clear media answer

---

src/main/java/org/commcare/formplayer/beans/menus/EntityDetailListResponse.java
src/test/java/org/commcare/formplayer/tests/CaseGroupingTests.java

Keep empty columns when requesting short details
https://dimagi-dev.atlassian.net/browse/QA-5774
cross-request: https://github.com/dimagi/commcare-core/pull/1371

Keep empty columns for short details

---

src/main/java/org/commcare/formplayer/application/FormSubmissionHelper.java
src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/session/MenuSession.java
src/test/java/org/commcare/formplayer/tests/EndpointLaunchTest.java
src/test/java/org/commcare/formplayer/tests/SubmitTests.java
src/test/resources/archives/endpoint/suite.xml

https://dimagi-dev.atlassian.net/browse/USH-3887
Changes for https://github.com/dimagi/commcare-core/pull/1380

Endpoint relevancy fix for Auto Advance Menus

---

src/main/java/org/commcare/formplayer/application/GlobalDefaultExceptionHandler.java
src/main/java/org/commcare/formplayer/application/MenuController.java
src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
src/main/java/org/commcare/formplayer/beans/exceptions/BaseExceptionResponseBean.java
src/main/java/org/commcare/formplayer/beans/exceptions/ExceptionResponseBean.java
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java

This improves on error for not found cases and marks requests as coming from clickable icons to allow for filtering case list by clickable icon properties.
jira ticket: https://dimagi-dev.atlassian.net/browse/USH-3875
mini spec: https://docs.google.com/document/d/11oJjcL5LnP0gwHOBuOZMGqcjkaRnekukbLN3K6vWxPo/edit
tested locally and on staging

Rc/clickable icons remove case from UI

---

src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java

This goes with this [HQ pr](https://github.com/dimagi/commcare-hq/pull/33868/files)
This was a workaround for not modifying the suite or Xforms
The HQ side that works with that code fail gracefully if that key is not available
I am not requesting QA

Submit Button Translation

---

src/main/java/org/commcare/formplayer/beans/menus/EntityDetailResponse.java

Formplayer support for https://dimagi-dev.atlassian.net/browse/USH-3873
There will be an HQ PR that will depend on this, but not for a little while. This PR can be released on its own.
This is pretty minimal, adding data to the response. It's not a lot of data, and it will only add data to apps that are using case tiles in case details, which is not yet configurable in HQ.
no
Not requesting QA, as this is an additive change with no user-facing effects.

Make case tiles available to case detail

---

src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
src/test/resources/archives/caseclaim/suite.xml

See description in [HQ PR 
](https://github.com/dimagi/commcare-hq/pull/33983)
[Jira Ticket](https://dimagi-dev.atlassian.net/browse/USH-4046)
[Commcare Core PR](https://github.com/dimagi/commcare-core/pull/1397)
[HQ PR 
](https://github.com/dimagi/commcare-hq/pull/33983)
added test that attribute is correctly parsed from suite
no QA

Adds searchOnClear to queryResponse

---

src/main/java/org/commcare/formplayer/services/ResponseMetaDataTracker.java
src/main/java/org/commcare/formplayer/util/Constants.java

No visual change.
Adds a `metadata` tag to Datadog where the value can include `app_install` or `attempt_restore`. These processes can lead to slow response times so the tags are added so those requests can be filtered and analyzed independently. 
Related [PR](https://github.com/dimagi/formplayer/pull/1526) which added this metadata to the response.
[USH-4069](https://dimagi.atlassian.net/browse/USH-4069)
Tested on staging. No change to product behavior.
no QA
[USH-4069]: https://dimagi.atlassian.net/browse/USH-4069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds datadog tags for restore and app installs

---

src/main/java/org/commcare/formplayer/application/MenuController.java
src/main/java/org/commcare/formplayer/application/UtilController.java
src/main/java/org/commcare/formplayer/beans/SyncDbResponseBean.java
src/main/java/org/commcare/formplayer/util/Constants.java
src/test/java/org/commcare/formplayer/junit/request/ScheduleSyncDbRequest.kt
src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
src/test/java/org/commcare/formplayer/tests/FilterTests.java
src/test/java/org/commcare/formplayer/tests/SyncTests.java

See description in [HQ PR](https://github.com/dimagi/commcare-hq/pull/34161)
[Jira Ticket](https://dimagi.atlassian.net/browse/USH-4063)
[Spec](https://docs.google.com/document/d/1owJma7M8TcxiitpqTDB6StkwMd--HPITku0rh-XBba4/edit?tab=t.0#heading=h.d7s2sycdfk92) 
[Related HQ PR ](https://github.com/dimagi/commcare-hq/pull/34161)
Tested locally and on staging. No effect on existing data and impact would be only for HQ calls to this endpoint. Currently limited to only the case captured in the [Related HQ PR ].(https://github.com/dimagi/commcare-hq/pull/34161)
https://dimagi.atlassian.net/browse/QA-6156?focusedCommentId=314984&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-314984
Deploy before related [HQ PR ](https://github.com/dimagi/commcare-hq/pull/34161) …

Endpoint to check restore expiration before syncing db

---

src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
src/test/java/org/commcare/formplayer/tests/CaseSearchResultsInStorageTests.java
src/test/java/org/commcare/formplayer/tests/EndOfFormNavFormLinkingWithQueryTests.java

No visible change 
Jira Ticket: https://dimagi.atlassian.net/browse/USH-4069
[HQ PR ](https://github.com/dimagi/commcare-hq/pull/34226)
Adds the module name to the request body for case search. The module name will be used on HQ for metric tagging.
Locally tested, will test on staging.
Test exists that checks `sessionNavigateWithQuery` creates uri with expected parameters
no QA
Needs to be deployed after related HQ PR

Add module name to Case Search Query Request Body for metric tagging on HQ

---

.github/workflows/build.yml

Update github actions plugins

---

src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java

[SAAS-11223](https://dimagi.atlassian.net/browse/SAAS-11223)
Will request QA to test all web apps form inputs thoroughly, and potentially plan to leave on staging for a while to see no ill effects reported.
[SAAS-11223]: https://dimagi.atlassian.net/browse/SAAS-11223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove check for answer 'None'

---

src/test/java/org/commcare/formplayer/tests/RepeatTests.java
src/test/resources/xforms/nested_repeat_deletion_regression.xml

Test for https://github.com/dimagi/commcare-core/pull/1415
Test only

Regression test for repeat deletion

---

src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java

Adds better error handling to be able to debug [errors like this](https://dimagi.sentry.io/issues/4616588934/?environment=production&project=142105&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+Array+index+out+of+range&referrer=issue-stream&statsPeriod=24h&stream_index=0) more easily
Tested basic lookup functionality on staging, think the only way it can cause errors is if I am not happening index comparison correctly which I have double checked that it looks right. 
None
None

Add explicit errors on incorrect index identifying the question in form
