- src/main/java/application/FormController.java
- src/main/java/requests/NewFormRequest.java
- src/main/java/session/FormSession.java
- src/test/java/tests/BaseTestClass.java
Pull auth token from new-form request and use for authentication
Also fix for using emails as usernames (for Web user restores)
cross: https://github.com/dimagi/touchforms/pull/231
cross: https://github.com/dimagi/commcare-hq/pull/12186
> New form auth

- src/main/java/hq/RestoreUtils.java
- src/main/java/session/FormplayerInstanceInitializer.java
So the NPE Priya was seeing was due to getLoggedInUser of the SQLSandbox returning null. When I examined the table there were no rows for the User which was really weird. Hopefully this will obviate the need to read that table and will also fail early if we do a restore and don't get a user entry.
> Set logged in user after restore

- src/main/java/application/FormController.java
- src/main/java/beans/GetInstanceResponseBean.java
- src/test/java/tests/BaseTestClass.java
@wpride fixes up the xpath route and indents the instance xml. the readable form questions to come later. it's a bit more tricky since a lot of the logic to represent the form data questions is in HQ and i don't think it makes sense to replicate that logic in java. we can either 1, make a request to HQ from inside formplayer, or 2, have the formplayer frontend make a request to HQ directly instead of formplayer. right now i'm leaning towards option 1
cc: @dannyroberts
> Eval xpath and instance XML

- src/main/java/application/AbstractBaseController.java
@wpride fixes form linking. previously it would try to get the title of the screen even though the next screen was null causing an error. Also wouldn't this function be more aptly named `getNextScreen` rather than `getNextMenu`? maybe we can pair on a way to test this. couldn't think of any way that wasn't super heavy like creating and installing an app that has form linking
cc: @dannyroberts
> Fix form linking

- src/main/java/beans/SessionListItem.java
@wpride this fixes opening saved sessions. we weren't passing the session id to the browser so opening an incomplete form would result in an error cause we'd try to look up the id "undefined." going to add a test for this.
cc: @dannyroberts
> Add session id back in

- src/main/java/install/FormplayerConfigEngine.java
@wpride i see a bunch of these in the commcare lib, but a couple in formplayer. isn't it really dangerous to have sys.exit? doesn't that mean it just stops the web server for everyone. not sure how to handle the ones in the commcare lib yet
> Remove sys.exit

- src/main/java/application/AbstractBaseController.java
- src/main/java/beans/ExceptionResponseBean.java
- src/main/java/exceptions/ApplicationConfigException.java
- src/main/java/install/FormplayerConfigEngine.java
@wpride @snopoke this'll handle handle app config errors and display the message. i don't think this'll yet handle xpath errors, but all we need to do is catch those and re wrap as an ApplicationConfigError and that'll stop the emails
I know it's ugly at the moment, going to work on fixing later
cross: https://github.com/dimagi/commcare-hq/pull/13038
> Handle app config errors

- src/main/java/session/FormSession.java
This should clear up an annoying, obscurely failing bug that was breaking forms when the web user had a default language set that wasn't available in the form. For now fail silently and log - possible we'll want to notify the user in the future, but maybe not?
> don't crash hard when user sets to non-registered locale

- src/main/java/application/UtilController.java
This was causing usernames with '-' or '.' in them to do the wrong search for form sessions
> Scrub names before searching for form sessions

- src/main/java/application/MenuController.java
- src/main/java/beans/InstallRequestBean.java
- src/main/java/repo/SerializableMenuSession.java
- src/main/java/repo/impl/PostgresMenuSessionRepo.java
- src/main/java/session/MenuSession.java
@benrudolph @biyeun 
This will allow us to set the oneQuestionPerScreen value here:
https://github.com/dimagi/commcare-hq/blob/245868750c34aa0fb301136e0f96e5dd05fa189f/corehq/apps/cloudcare/static/cloudcare/js/formplayer/entities/menu.js#L91-L91
And have that be respected. I didn't write the migration (see the TODO) because it'll clash with https://github.com/dimagi/formplayer/pull/140/files but will once that's merged
> Respect OQPS from menu selection

- src/main/java/application/UtilController.java
- src/main/java/beans/GetSessionsResponse.java
- src/main/java/beans/SessionListItem.java
- src/main/java/hq/CaseAPIs.java
- src/main/java/objects/SerializableFormSession.java
- src/main/java/session/FormSession.java
- src/main/java/util/FormplayerDateUtils.java
- src/test/java/tests/FormplayerDateUtilsTest.java
@wpride this'll include the case name in the session list. one of jwax's feedback items. i'm not sure what the performance implications are of taking all the serializable form sessions and converting them to regular form sessions are, but it didn't seem too bad
cc: @orangejenny
> Case name in form session

- src/main/java/session/FormSession.java
This fixes http://manage.dimagi.com/default.asp?239335
There's something we're not expanding during the usual getInstanceXml() call that is expanded when generating the form tree (only noticed this because the debugger had the correct XML while the submission didn't)
The right way to fix this is to to unify the android and nimbus submission code, which I'll do next
Can merge this for now as a hack
> hack fix for model iteration expansion

- src/main/java/install/FormplayerConfigEngine.java
@wpride couldn't get case tiles to work, but did realize we don't properly handle 500 errors from app manager
I think it's fine not to email, since that 500 email will be sent from HQ's side
> Handle 500 error for app builds

- src/main/java/session/FormplayerInstanceInitializer.java
@wpride this would only log the error even though it's critical that `u` not be `null`. this led to many of those null pointers later down the line. think it makes sense to error up front so we know the cause
> Throw error on missing user restore

- src/main/java/application/FormController.java
- src/main/java/session/FormSession.java
cross-request: https://github.com/dimagi/commcare-core/pull/459
Since we were already storing these variables in FormSession and they're not useful for Android (where its tracked separately) I refactored this a bit. Would be good to validate this @biyeun @benrudolph
> Move oqps and currentIndex vars into formSession

- src/main/java/aspects/LockAspect.java
@benrudolph If we timed out waiting for the lock the thread could proceed as if it had obtained the lock. Then when it went to unlock the lock it would find that it never owned the lock to begin with! Quite an anomaly.
> Don't keep lock when timed out

- src/main/java/aspects/LockAspect.java
Catching and re-throwing is breaking our exception emailing (IE we'll email every type of exception)
> Don't intercept exceptions in locking class

- src/main/java/application/AbstractBaseController.java
@wpride this'll catch HTTP error properly (useful so we don't email on permission denied errors and also provides more useful error messages in the response)
> Properly handle HTTP client error exceptions

- build.gradle
- config/application.properties.example
@wpride this provides some incredibly useful endpoints on the port specified. this will not be open to the world. read more here: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints. once this is deployed i think it makes sense to replace our servup check with `:8081/health`
> Add actuator

- src/main/java/hq/CaseAPIs.java
- src/main/java/repo/impl/PostgresFormSessionRepo.java
- src/main/java/services/RestoreFactory.java
We were looking up the restoreXml each time we looked up a session, even if this user already had extant databases. fix that.
> don't get restore XML for each session

- src/main/java/session/FormSession.java
@phillipm moved a bunch of the files in commcare-core around for a cleaner interface. This, this updates Formplayer accordingly. Makes the IntelliJ import setup much cleaner.
> Make commcare files more gradle conformant

- src/main/java/application/FormController.java
- src/main/java/application/MenuController.java
- src/main/java/services/FormplayerStorageFactory.java
- src/main/java/services/RestoreFactory.java
- src/test/java/tests/BaseTestClass.java
@benrudolph we weren't configuring the storage factory after end of form navigation, I suspect this caused this squirrelly error: :shipit: 
java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
at java.util.Vector.elementAt(Vector.java:470)
at org.commcare.session.CommCareSession.getEvaluationContext(CommCareSession.java:563)
at org.commcare.session.CommCareSession.getEvaluationContext(CommCareSession.java:549)
at org.commcare.modern.session.SessionWrapper.getEvaluationContext(SessionWrapper.java:37)
at session.MenuSession.getNextScreen(MenuSession.java:174)
at session.MenuSession.(MenuSession.java:98)
at application.FormController.doEndOfFormNav(FormController.java:161)
at application.FormController.submitForm(FormController.java:144)
> configure storage factory before end of form nav

- src/main/java/services/FormplayerStorageFactory.java
- src/main/java/session/MenuSession.java
- src/test/java/mocks/MockFormSessionRepo.java
- src/test/resources/requests/install/case_media.json
- src/test/resources/requests/navigators/navigator_0.json
- src/test/resources/requests/preview/preview.json
- src/test/resources/requests/preview/preview_step.json
This adds some logging and better error messaging around the exception Jessica reported:
java.lang.ArrayIndexOutOfBoundsException: 2
at org.commcare.util.screen.MenuScreen.handleInputAndUpdateSession(MenuScreen.java:158)
at session.MenuSession.handleInput(MenuSession.java:167)
the logs around this are very strange:
Request to navigate_menu with bean SessionNavigationBean [id= 3d45b792-cf0e-4d61-9ca5-60e5e74e7deb, selections=[2, 41df827f-bf39-41a5-804d-d0e17836b455, 74a8153d-2bde-4069-b3a9-48ab6a5243b8] parent=InstallRequestBean: [installReference=null, username=asi-test@asi-selever.commcarehq.org, domain=asi-selever, appId=cb33358bb543442b0fc14990358f7118, oneQuestionPerScreen: false]]
2016-12-13 11:01:59.936  INFO 30929 --- [nio-8181-exec-7] services.impl.InstallServiceImpl         : …
> Better logging and error handling around menu nav

- src/main/java/session/MenuSession.java
Should fix those one:
java.lang.RuntimeException: java.sql.SQLException: [SQLITE_BUSY] The database file is locked (database is locked)
at org.commcare.api.persistence.SqlHelper.updateToTable(SqlHelper.java:221)
at org.commcare.api.persistence.SqliteIndexedStorageUtility.update(SqliteIndexedStorageUtility.java:353)
at org.commcare.api.persistence.SqliteIndexedStorageUtility.write(SqliteIndexedStorageUtility.java:83)
at org.javarosa.core.services.PropertyManager.writeValue(PropertyManager.java:287)
at org.javarosa.core.services.PropertyManager.setProperty(PropertyManager.java:137)
at org.javarosa.core.services.PropertyManager.setProperty(PropertyManager.java:120)
at org.commcare.suite.model.Profile.initializeProperties(Profile.java:191)
at …
> PropertyManager singleton fix

- src/main/java/application/WebAppContext.java
- src/main/java/aspects/LockAspect.java
Partial fix for http://manage.dimagi.com/default.asp?244524#
Before we were expiring the lock after 60 seconds of ownership (the default) so if the request took longer than this the request would fail (even though the result was returned correctly). This bumps that expiry time to five minutes. 
I've also made it so that we won't crash and discard the result if we've lost the lock. I'm not sure if this is the right thing to do since there are potential concurrency issues (IE another thread could have gotten the lock and changed the DBs). However, this seems exceedingly unlikely to me since 1) the expiry period is now five minutes and 2) now that app and user DBs are used data churn seems much less likely.
In fact I was considering whether we can disregard the user locking entirely now that …
> Increase lock expiration time, don't crash when it timesout

- src/main/java/aspects/LockAspect.java
@wpride this rewraps the lock message error to be more user friendly. stack trace now looks like this:
```
java.lang.IllegalStateException: That request took too long to process, please try again.
at aspects.LockAspect.beforeLock(LockAspect.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
at …
```
> Rewrap error message

- build.gradle
- src/main/java/application/WebAppContext.java
- src/main/java/aspects/MetricsAspect.java
@wpride @snopoke  gave up trying to get datadog's jmxfetch utility to work with spring actuator and just wrote the metrics myself. there's a write up here: https://github.com/DataDog/jmxfetch/issues/118 of the issue i was facing. think this is better in the end anyways because it will allow us to capture custom metrics if we want. if the statsd client isn't running, it just silently fails which is what we want
cc: @millerdev @gcapalbo
> Use statsdclient for metrics

- src/main/java/aspects/MetricsAspect.java
Fixes 500s, I think every request that doesn't have auth is broken:
java.lang.ArrayIndexOutOfBoundsException: 0
at aspects.MetricsAspect.logRequest(MetricsAspect.java:30)
at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java …
> check nullity

- src/main/java/repo/impl/PostgresFormSessionRepo.java
@wpride realized we weren't actually ordering by date. since dateOpened is stored as text as a string like `"Fri Jan 06 15:58:03 SAST 2017`. thus when we order by dateopened it orders by the day of the week. i think at some point we should move dateOpened to actual date time column stored as an epoch or in UTC format. tried writing a test for this, but had trouble mocking the time, but verified it works locally.
> Actually order by date

- src/main/java/application/CORSFilter.java
- src/main/java/application/FormplayerAuthFilter.java
Have our filters extend a class that guarantees to only fire once, hopefully will resolve these recursive filtering overflows we saw. Also makes the code tidier.
> Fix for recursive filter calls

- src/main/java/beans/menus/EntityListResponse.java
- src/test/java/tests/GeoTests.java
- src/test/resources/restores/geo.xml
This was actually already being overridden with a dummy function in the CLI (thanks Phillip) just needed to properly get the EvaluationContext from the screen
> Don't crash on here() function

- src/main/java/db/migration/V11__form_session_add_missing_appid.java
Some migrated incomplete forms were missing appId's which caused errors as in http://manage.dimagi.com/default.asp?245942
This migration addresses that by using either the linked menu session or the postUrl depending on what is available. This migration is very janky and I am not proud of that. However its also very resourceful and I am proud of that 😑
> Fix for missing appIds

- src/test/java/tests/InstallTests.java
Don't know how I missed this one on my previous static object pass. Should fix the GLOBAL_RESOURCES_TABLE exception that we've been seeing. Hopefully the last of these.
> Change StorageManager static to StorageManager thread safe singleton

- src/main/java/session/MenuSession.java
Use appId from the request instead of from the profile. This was not correct and was resulting in re-installations happening on some submissions (also explaining why submit times were so long for some requests).
> Fix appId in menu session

- src/main/java/application/UtilController.java
This was (hopefully) the last source of the terrible and seemingly unkillable GLOBAL_RESOURCE_TABLE does not exist errors
> Lock syncDb and deleteDbs requests

- src/main/java/beans/menus/EntityListResponse.java
- src/main/java/util/StringUtils.java
Previously we were evaluating every case list field for every case in user's DB before showing the case list even when this list might be filtered and would certainly be paginated. This changes that pushing the row loading back in the EntityListScreen class until they're needed and by making the filter and paginate operations work on the list of pre-rendered Entity<TreeReference> objects instead of the fully actualized rows. Required moving some code down from -android into -core.
This should be a massive performance win for enikshay
@benrudolph cc @czue
> Case list optimization

- src/main/java/beans/EvaluateXPathResponseBean.java
- src/main/java/services/NewFormResponseFactory.java
- src/test/java/tests/CaseTests.java
- src/test/java/tests/FormEntryTest.java
This aligns our code path with the one used by the CLI, in particular it allows us to return multiple nodes in the case that the expression matches multiple.
> Make evaluate instance work better

- src/main/java/beans/menus/EntityDetailListResponse.java
Handling detail screens with a nodeset defined (IE a table) will require some work. For now we can skip these and show the other details.
> Skip any detail screens with nodesets

- src/main/java/application/FormController.java
- src/main/java/session/FormSession.java
- src/test/java/mocks/MockFormSessionRepo.java
- src/test/java/tests/OQPSDateRegression.java
- src/test/resources/xforms/oqps_date.xml
fixes https://manage.dimagi.com/default.asp?247996
In OQPS when you answered a question in a sub-group, the currentIndex would focus on that specific answer (as if it had not been in a sub-group at all) so the other group members would not be displayed.
~This PR addresses that by using the top-level (shallowest) index (rather than the deepest one) to generate the current set of relevant questions.~
Actually, re-wrote to use currentIndex from the FormSession rather than hacky string chopping
> Fix OQPS sub-group indexing issue

- src/main/java/repo/impl/PostgresMigratedFormSessionRepo.java
Fix for https://manage.dimagi.com/default.asp?249209
If the JSON doesn't have an init_lang, we can just allow this property to be null and we will use the default locale.
> Graceful fail when migrated form session has null lang

- src/main/java/session/MenuSession.java
Should fix these exceptions:
Screen org.commcare.util.screen.EntityScreen@5bc3341e handling input 7bd4c465-facc-47d9-91c8-16ab3140361e threw exception null. Please try reloading this application and if the problem persists please report a bug.
@ctsims
> Skip EntityScreen when necessary

- src/main/java/application/FormController.java
- src/main/java/beans/FormEntryNavigationResponseBean.java
- src/main/java/session/FormSession.java
We were running into a situation where anytime the FormIndex for the first displayed question wasn't `0` - for example when the first question is in a group it will have index `0,0` - then we would not grey out the getPrevious arrow if we returned to the question. This rectifies that by checking on Formplayer whether there is truly another question before the current one. 
cross-request: https://github.com/dimagi/commcare-hq/pull/15738
> Check if form index is first in the form

- src/main/java/screens/FormplayerSyncScreen.java
@wpride @ctsims needs this guy https://github.com/dimagi/commcare-core/pull/547. default scoping of variables is package level which is what caused the null pointer exception
> Fix case claim

- src/main/java/database/models/FormplayerCaseIndexTable.java
Two issues:
Our SQLite version didn't like/need the `CAST(? AS INT)` casting for its arguments
`resultSet.getFetchSize()` apparently doesn't work (?!) and also isn't needed
fixes http://manage.dimagi.com/default.asp?252012
> Fix FormplayerCaseIndexTable SQL issues

- src/main/java/beans/menus/EntityListResponse.java
Fixes https://manage.dimagi.com/default.asp?251978
This happened because the pagination code relied (indirectly) on the case tile processing code being called first, at some point the calls must've gotten out of order. Removed this silly dependency.
> Don't rely on member variable

- build.gradle
- src/main/java/application/Application.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/tests/FormValidatorTests.java
This brings us to the latest `spring-boot` version and updates deprecated classes accordingly. Also switched from setting dependency versions manually to using the Spring Boot Gradle plugin's [dependency manager](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html) which is the more canonical way to do this.
> Update plugin versions, update deprecated classes

- src/main/java/application/AbstractBaseController.java
- src/main/java/application/WebAppContext.java
- src/main/java/aspects/AppInstallAspect.java
- src/main/java/aspects/LoggingAspect.java
- src/main/java/engine/FormplayerConfigEngine.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/SentryUtils.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/utils/TestContext.java
@wpride this should fix up sentry for the most part. there is still one race condition when the logging of one of the breadcrumbs fails on the initial request. Wasn't able to quickly get to the bottom of it, but it works on subsequent requests oddly. For now going to leave as is because I don't think it's terribly high priority
> Require raven param

- src/main/java/services/RestoreFactory.java
Temporarily remove `since` param from restore requests 
@benrudolph
> Don't use sync token anymore

- src/main/java/util/SentryUtils.java
- src/test/java/tests/ApplicationUtilsTests.java
Confused as to why this works locally and not on prod. My guess is that the way raven does it's static reference to the raven instance doesn't work as I expect it to. This changes the calls to utilize the raven object passed in, not the one stored statically. Also adds stack trace to log call so i can see where the null pointer is coming from if this doesn't fix it
> Sentry tweaks

- src/main/java/services/impl/QueryRequesterImpl.java
@proteusvacuum @wpride spring already encodes urls so this was getting double encoded
> Decode uri before sending

- .travis.yml
- src/main/java/application/MenuController.java
- src/main/java/application/UtilController.java
- src/main/java/hq/CaseAPIs.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/UserUtils.java
Re-implements Incremental Restore with a couple fixes.
I think the main one causing the issue we saw was with disagreement between username formatting when getting the syncToken. Specifically, User objects don't have a domained username while the SqlSandbox would. This would cause a mismatch resulting in the `syncToken` being empty and since we weren't overriding the cache this would result in the (stale) cached XML being returned instead of the differential. I was able to reproduce and fix this behavior locally. 
I've also added checks for empty (non-null) syncToken and returned the "Sync" button to forcing a full restore.
> Incremental Sync Episode II

- .travis.yml
- src/main/java/application/MenuController.java
- src/main/java/application/UtilController.java
- src/main/java/aspects/UserRestoreAspect.java
- src/main/java/beans/AuthenticatedRequestBean.java
- src/main/java/hq/CaseAPIs.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/UserUtils.java
cross-request: https://github.com/dimagi/commcare-hq/pull/16485
Addresses previously exposed bug with case claim that would result in case claims being re-initiated during asyncronous restores. Fixes this by adding an optional mustRestore param that will force a sync before navigations can proceed.
> Incremental Sync Episode III: Revenge of the Syncs

- src/main/java/services/FormplayerStorageFactory.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/ApplicationUtils.java
- src/main/java/util/Constants.java
- src/test/java/tests/ApplicationUtilsTests.java
- src/test/java/tests/DeleteApplicationDbsTests.java
- src/test/java/tests/sandbox/TestConnectionHandler.java
@wpride this cleans up the application user db path creation quite a bit. it now all happens in one class. before we were generating the same path in multiple places, making it very hard to actually change the db name. the second commit actually add `V1` to the end of the db file. if we ever want to wipe dbs on deploy, we should just bump change that string
buddy: @mkangia
> Version sqlite dbs

- src/main/java/application/MenuController.java
- src/main/java/application/UtilController.java
- src/main/java/aspects/UserRestoreAspect.java
- src/main/java/hq/CaseAPIs.java
- src/main/java/services/NewFormResponseFactory.java
- src/main/java/services/RestoreFactory.java
- src/main/java/session/FormSession.java
- src/main/java/session/MenuSession.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/tests/CaseClaimTests.java
Removes the `override_cache=true` parameter in favor of using the `since` token parameter in all cases. This brings Formplayer in line with how Android handles restores.
Worth noting that this removes all paths for blowing away user DBs manually - now this will only happen when the DBs have expired (as determined by the sync frequent property).
> Always use the sync token, never overwrite cache

- src/main/java/beans/menus/EntityBean.java
- src/main/java/beans/menus/EntityDetailListResponse.java
Fixes https://manage.dimagi.com/default.asp?258552
That error was occurring because we were attempting to load up the long details (detail tabs) before we had selected a case so variables in the detail that expected to be contextualized by a reference were not. I think we were only doing that preloading for legacy reasons (IE before we split out the navigation and getDetails calls) so I've just refactored that .
> Refactor EntityDetailList to separate list from detail

- README.md
to use `&&` instead of `;` (to abort if the build fails)
and include instructions for skipping test on build
> improve README run instructions

- scripts/archive_dbs.sh
- src/main/java/sandbox/ArchivableFile.java
- src/main/java/sandbox/SqlSandboxUtils.java
- src/main/java/sqlitedb/ApplicationDBPath.java
- src/main/java/sqlitedb/DBPath.java
- src/main/java/sqlitedb/SQLiteDB.java
- src/main/java/sqlitedb/UserDBPath.java
This PR provides
- functionality for detecting and unarchiving .gz archive when the original db file is not present, and working transparently from there as if it had been present all along
- a script that can be used in a cron job to archive all .db files in a directory that haven't been accessed for a given period of time. (This will not be "live" until we add such a cron job in ansible.)
Thus the only immediate effect of this PR is to turn on the ability to read from *.db.gz files, but doesn't actually turn on the archiving that will create them yet.
To test this out locally (with the archiving), you can (from the formplayer directory) run (assuming you're storing dbs in `formplayer/dbs`)
```bash
watch './scripts/archive_dbs.sh dbs +10s'
```
in one terminal window to archive all dbs …
> Gzip archiving

- src/main/java/application/AbstractBaseController.java
- src/main/java/aspects/LockAspect.java
- src/main/java/util/Constants.java
and change response behavior on the lock timeout and lock expiry.
EDIT: I originally was going to change it to 7 seconds, but @ctsims convinced me to try 21 seconds instead, as thousands of requests a day fall into the < 20s bucket.
The impetus here is that the _vast_ majority of requests take under 20 seconds, so if you can't obtain a lock in 21 seconds, chances are you're waiting on a loooong process or a deadlock, and it's relatively likely you won't be able to obtain it in 120 seconds either—so there's no point in presenting that baffling behavior where you do some super simple thing and hangs for 2 minutes, and then fails anyway.
This should only get merged after https://github.com/dimagi/commcare-hq/pull/17639, which improves the behavior of server errors like this one to be less …
> Shorten user lock timeout

- src/main/java/aspects/LockAspect.java
I noticed that datadog `lock_issue:` values were starting with
an `_`, and it's because of an unintentional space I put in there.
It's good to have continuity, so I'm leaving the underscore there, but
I'm also making it more explicit by putting it in the string values.
> make underscore prefix in lock_issue explicit

- src/main/java/application/WebAppContext.java
- src/main/java/aspects/AppInstallAspect.java
- src/main/java/aspects/LoggingAspect.java
- src/main/java/aspects/MetricsAspect.java
- src/main/java/services/RestoreFactory.java
Fixes https://sentry.io/dimagi/formplayer/issues/346089672/ introduced here https://github.com/dimagi/formplayer/pull/468
@dannyroberts looks like ImmutableMap does not allow null values which some of these can be https://github.com/google/guava/issues/1782
> Revert "clean up builder syntax for sentry breadcrumbs"

- src/main/java/aspects/LockAspect.java
- src/main/java/util/Constants.java
datadog: *.granular.timings metric, category "wait_on_lock";
sentry: breadcrumb, category "wait_on_lock"
> log lock timings to datadog and sentry

- src/main/java/application/WebAppContext.java
- src/main/java/aspects/LockAspect.java
- src/main/java/aspects/MetricsAspect.java
- src/main/java/services/CategoryTimingHelper.java
- src/main/java/util/SimpleTimer.java
Quick prefactor to make adding standardized category timings easier.
The idea with category timings is that they should be _mutually exclusive_, so that all together they add up to less than the total time a request took—i.e. don't time a function and then also time a smaller potion within it.
To add a timing now, it looks like this:
```
CategoryTimingHelper.RecordingTimer timer = categoryTimingHelper.newTimer("my_category");
timer.start();
timer.end()
.setMessage("My message which can be a function of timer duration")
.record();
```
(if there's one already there, if the thing is in a `try`-`catch`, consider putting the `timer.end()...` step in a `finally`).
> Simplify timing

- src/main/java/application/MenuController.java
- src/main/java/util/Constants.java
web apps will use the new endpoint when entering an app and the main one for everything else.
this will help us break out the first click, which often includes lots of app installs,
from all the other menu navigation
> add /navigate_menu_start as alias to /navigate_menu

- src/main/java/application/WebAppContext.java
- src/main/java/aspects/LockAspect.java
- src/main/java/aspects/MetricsAspect.java
- src/main/java/services/CategoryTimingHelper.java
- src/main/java/util/RequestUtils.java
the overall timing metric and lock metric were pulling
from the route name rather than the url.
this made navigate_menu vs navigate_menu_start indistinguishable
> fix request param in datadog

- src/main/java/application/WebAppContext.java
- src/main/java/aspects/LockAspect.java
- src/main/java/aspects/MetricsAspect.java
this was causing most requests to be double-counted in datadog
Not exactly clear _why_ that's the effect of request-scoping these (maybe two `MetricAspect` objects end up getting created somehow, one global-scoped, one request-scoped... or something), but this is definitely what was causing it and it turns out just removing them works. I'd originally put them there as part of a workaround for something that ended up not working anyway, before I settled on the better approach (injecting the spring `HttpServletRequest` request rather than our own wrapper of it: https://github.com/dimagi/formplayer/pull/486), and it turns out it's not needed anymore anyway.
There've been a bunch of PRs related to this, which has been confusing even for me, so I pulled the total diff of the original PR …
> fix double-running MetricAspect and LockAspect

- src/main/java/hq/CaseAPIs.java
- src/main/java/sandbox/UserSqlSandbox.java
- src/main/java/services/RestoreFactory.java
Resolves https://manage.dimagi.com/default.asp?261905
Convoluted but straightforward bug. When looking up the current user in the users database we compare the name strings. ~~The target name is escaped (`-` and `.` become `_`) but the names stored in the database are not. So if we are looking for the user named EG `district.support.test` we will never find this user and thus never set the sync token. This causes subsequent restores to use the cached lookup as we do not have a sync token.~~
Turned this into a bigger refactor. Formplayer borrowed a lot of unnecessary code from Android here - namely, our DBs will only have one user on them (Which we rely on elsewhere in the code) so iterating over the users comparing names is unnecessary.
I've also made a change so that we update the user's …
> Refactor syncToken management

- src/main/java/services/RestoreFactory.java
Use `*` instead of `|` as separator in URL because [`|` is not safe][1] and [`*` is][2].
[1]: https://manage.dimagi.com/default.asp?263058#BugEvent.1401215
[2]: https://perishablepress.com/stop-using-unsafe-characters-in-urls/
> Use '*' as separator in URL

- src/main/java/hq/CaseAPIs.java
- src/main/java/services/RestoreFactory.java
I * think* this will resolve some of the issues seen [here](https://manage.dimagi.com/default.asp?263442)
I believe that when we encountered certain exceptions (chiefly `InvalidStructureException`) we would error out without closing the SQLite database. This would result in the user being locked out. Until the database was cleared out and could also result in incorrect data being present in the database.
> Rollback SQL writes on exception

- src/main/java/application/AbstractBaseController.java
- src/main/java/application/DebuggerController.java
- src/main/java/application/FormController.java
- src/main/java/application/MenuController.java
- src/main/java/session/MenuSession.java
HQ Auth was already available through the `RestoreFactory` so instantiating and passing around through methods was unnecessary.
> Refactor to get auth from restoreFactory

- src/main/java/services/FormplayerFormSendCalloutHandler.java
Previous method was loading these as query parameters rather than URL parameters. I must've only tested this with the values loaded directly into the URL.
@ctsims
> Change how we load up params map into variables

- src/main/java/engine/FormplayerArchiveFileRoot.java
- src/main/java/engine/FormplayerConfigEngine.java
This is a pretty nifty refactor wherein app install requests will first check whether the CCZ has already been downloaded to the file system before attempting to download a new copy and re-use that file if so. We accomplish this by updating the `FormplayerArchiveFileRoot` class, which already handled mapping between `jr://` paths and the actual file during install, to use the versioned `app_id` (as passed by the install request URL) of the application as the archive's GUID instead of a randomly generated UUID. Then subsequent requests simply use the FileRoot to check whether a mapping is already available for that UUID in the static mapping or in Redis and re-use the file if so. If the mapping isn't present or it is but the file has been deleted we fail gracefully to the old code path. 
I …
> Formplayer to attempt to re-use downloaded CCZ files for install

- src/main/java/engine/FormplayerConfigEngine.java
Turn this off for now - because the Live Preview route uses `appId` rather than `versionId` this was breaking live preview uodates
> Disable ccz caching

- src/main/java/session/FormSession.java
This removes some hacky logic around moving to the next/previous FormIndex and instead uses the Android code both.
The `moveToNextView` and `moveToPreviousView` functions are heavily copied from `FormEntryActivityUIController` - unfortunately the code there is pretty paired with the Android UI so I'm not sure how feasible it is to move it into `commcare-core` but I want to take a second look tomorrow.
> Use Android OQPS logic

- src/main/java/application/MenuController.java
- src/main/java/application/UtilController.java
- src/main/java/aspects/UserRestoreAspect.java
- src/main/java/hq/CaseAPIs.java
- src/main/java/services/InstallService.java
- src/main/java/services/NewFormResponseFactory.java
- src/main/java/services/RestoreFactory.java
- src/main/java/session/FormSession.java
- src/main/java/session/MenuSession.java
- src/main/java/util/Constants.java
After dealing with the timing objects in https://github.com/dimagi/formplayer/pull/523 decided it might be better just to centralize this logic in the `RestoreFactory` where we already have the `CategoriesTiming` class Autowired. Downside is this makes `RestoreFactory` even more of a god class. I think the upside is worth it though; removing the whole `SyncTimings` class, removing the un-DRY calls to `recordTimings`. The CaseAPIs static functions all took a `RestoreFactory` as an argument anyways which just seems silly/un-static.
> Fold most CaseAPIs fucntionality into RestoreFactory

- build.gradle
@amstone326 This codifies some of the IDE changes we had to make in Gradle. Specifically
1. Exclude `jmh` directory in `commcare-core`
2. Defer to `commcare-core` library versions
@dannyroberts should clear up recurring `regex.me` dependency issue
> Remove dependecies from commcare-core, exlude jmh

- src/main/java/services/RestoreFactory.java
- src/main/java/session/MenuSession.java
Ugly, but the code [here](https://github.com/dimagi/formplayer/blob/b26414f48500e0243dc9db4e6d84970a1c09ec6e/src/main/java/session/MenuSession.java#L107-L107) that enforced a sync every time a new application was installed conflicted with the `mustRestore` param [here](https://github.com/dimagi/formplayer/blob/80dec1294b6510ed82e93f3bd94240a79492355d/src/main/java/aspects/UserRestoreAspect.java#L55-L55) added to ensure a sync happens after case claim. This was resulting in a sync being kicked off twice on requests that were asyncronous *and* the triggered the installation of a new application. Haven't worked out all the details yet, but this tripped out my local environment when I got it reproducing.
> Only restore once

- src/main/java/engine/FormplayerArchiveFileRoot.java
A sometimes expected error needlessly clogging the logs
> Don't print stack trace

- src/main/java/application/MenuController.java
- src/main/java/db/migration/V15__add_preview_menu_session.java
- src/main/java/engine/FormplayerConfigEngine.java
- src/main/java/repo/SerializableMenuSession.java
- src/main/java/repo/impl/PostgresMenuSessionRepo.java
- src/main/java/services/InstallService.java
- src/main/java/session/MenuSession.java
- src/test/java/mocks/TestInstallService.java
Because App Preview uses the `appId` instead of the `buildId` we need to not re-use the CCZ when in preview mode (since the ID would remain the name). This PR does that and adds `preview` as part of the MenuSession database in support of this.
> Don't re-use CCZ for Preview Mode

- src/main/java/application/DebuggerController.java
If the `authToken` argument isn't specified in the route then it isn't available to us in the `UserRestoreAspect`. This was breaking the MenuDebugger routes. 
Product announce: Menu debugger functional again
> Add authToken args to MenuDebugger routes

- src/main/java/application/AbstractBaseController.java
Was seeing this exception crop up with some gnarly stack overflows; apparently not handling this properly can cause this. 
Background reading:
https://mtyurt.net/2016/04/18/spring-how-to-handle-ioexception-broken-pipe/
> Check for client aborted

- src/main/java/application/AbstractBaseController.java
- src/main/java/application/FormplayerAuthFilter.java
- src/main/java/application/WebAppContext.java
- src/main/java/aspects/LockAspect.java
- src/main/java/exceptions/InterruptedRuntimeException.java
- src/main/java/services/FormplayerLockRegistry.java
Move locking off of Redis and onto the JVM since we know user requests are on one machine
Also add ability to evict locks owned by dead threads
> JVM-level locking

- src/main/java/api/process/FormRecordProcessorHelper.java
- src/main/java/application/FormController.java
- src/main/java/sandbox/JdbcSqlStorageIterator.java
- src/main/java/sandbox/SqlHelper.java
- src/main/java/sandbox/SqlSandboxUtils.java
- src/main/java/services/RestoreFactory.java
- src/main/java/services/SubmitService.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/tests/SubmitTests.java
Delete `FormSession` from Postgres immediately after getting a successful sync. Previously, we retrieved the next screen (for end of form navigation) before deleting the row. If we encountered an error here, we would have submitted the form but *not* have deleted the `FormSession`. The user would be redirected back to the home screen by the failed end of form nav, but in theory they could go to the Incomplete Forms page and re-open and re-submit that form, as appears to have happened here:
https://manage.dimagi.com/default.asp?265683
@ctsims turned this into a two-fer to include rolling back on failed submissions
> Delete form session right after submit success

- src/main/java/aspects/UserRestoreAspect.java
Running into `SQLiteBusyException` because these connections are being left open
> Close restore factory connections in aspect

- src/main/java/beans/menus/EntityDetailResponse.java
- src/main/java/beans/menus/EntityListResponse.java
- src/main/java/util/FormplayerGraphUtil.java
Moves around a few pieces of graphing in Formplayer to allow for the deletion of some files
1. Move up evaluation of detail data to the `Formplayer` level so that we can use a `FormplayerGraphUtil` class instead of `GraphUtil` in `commcare-core`
2. This allows us to delete those methods from `GraphUtil` in commcare-core (we wouldn't have been able to unify these because Formplayer gets the D3 libs from a CDN while Android stores them locally)
3. This allows us to delete `Color.java` from `commcare-core` as well
> Graphing refactor

- src/main/java/application/AbstractBaseController.java
Don't need to send a Sentry error for this one
> No sentry error for localized text missing

- src/main/java/sandbox/SqlHelper.java
- src/main/java/sandbox/SqlStorage.java
- src/main/java/sandbox/UserSqlSandbox.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/tests/Enikshay2bTests.java
- src/test/resources/requests/sync_db/sync_db.json
Noticed this in Sentry, looks like this statement should be an insert-or-replace rather than a basic insert. Added a line to the tests that would trigger this failure.
> Fix for FixtureIndex update failing

- src/main/java/screens/FormplayerSyncScreen.java
- src/main/java/services/MenuSessionFactory.java
cross-request: https://github.com/dimagi/commcare-core/pull/724
make `CommCareSessionException` typed again
> SessionException back to typed

- src/main/java/application/FormController.java
Broken by https://github.com/dimagi/formplayer/pull/591
Some request paths that required the StorageManager to be initialized were not. 
Should fold this into an Aspect in a later PR, hotfix for now
> Fix StorageManager being null for some requests

- build.gradle
- src/main/java/application/FormController.java
- src/main/java/beans/OpenRosaResponse.java
- src/main/java/beans/SubmitResponseBean.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/tests/FormEntryTest.java
- src/test/java/tests/SubmitTests.java
Parse the `OpenRosaResponse` message block from submissions (currently always a `√`) and send to the browser
@orangejenny this ends up in the extant notifications JSON attribute (which we use for pop-ups), if you don't want to re-purpose this for this case we can add a new attribute:
`{..."notification":{"message":"   √   ","error":false}, ...}`
> Attempt to parse message in submission response and send to browser

- README.md
`assemble` by default won't run any tests, so is preferable to `build -x test` which will skip the `test` task but run others like `lint` and `jenkinsTest` which are not desired here. 
cc @orangejenny
> Update command to run without tests

- src/main/java/engine/FormplayerConfigEngine.java
cross-request: https://github.com/dimagi/commcare-core/pull/742
Pass in a dummy `PrintStream` to `CommCareConfigEngine` since we do not care about the (mostly diagnostic) logging done there. Hard failures should be sent as Exceptions and logged at the Sentry level.
> CommCareConfigEngine use PrintStream, Formplayer passes in dummy

- src/main/java/screens/FormplayerQueryScreen.java
- src/main/java/screens/FormplayerSyncScreen.java
- src/main/java/services/MenuSessionRunnerService.java
- src/main/java/session/MenuSession.java
Backmerge of 2.42 into formplayer and compatibility.
The big compatibility fix was making `EntityScreen` handle *either* a case-id *or* a case index. I decided this was necessary (rather than trying both) because I've seen errors where the front end will send a command index (ie `1`) twice and so the `EntityScreen` would receive a `1` as input. Currently we'll error on this because there's no case with Id `1` but if we were permissive of indexes this error would successfully select some random case. 
cross-request: https://github.com/dimagi/commcare-core/pull/753
> Formplayer 2.42

- src/main/java/beans/IncompleteSessionRequestBean.java
Fixes https://manage.dimagi.com/default.asp?270558
Looks like when I added `session_id` to the `AuthenticatedRequestBean` class as part of the SMS work it interfered `IncompleteSessionRequestBean` which expects the variable in form `sessionId`. This rectifies that.
> Override sessionId variable name for incomplete forms

- src/main/java/aspects/UserRestoreAspect.java
- src/main/java/beans/AuthenticatedRequestBean.java
- src/main/java/db/migration/V17__add_case_id_field.java
- src/main/java/objects/SerializableFormSession.java
- src/main/java/repo/impl/PostgresFormSessionRepo.java
- src/main/java/services/NewFormResponseFactory.java
- src/main/java/session/FormSession.java
- src/main/java/session/MenuSession.java
And use this caseId to restore on subsequent requests.
The `FormSession` class has become overloaded, eventually I'd like to split the functionality into `SMSFormSession`, `OQPSFormSession`, and standard `FormSession` classes
cc @gcapalbo
> Add caseId property to FormSession to enable filling out a form as a case in SMS

- src/main/java/services/MenuSessionRunnerService.java
- src/main/java/services/RestoreFactory.java
Noticed investigating https://manage.dimagi.com/default.asp?270264 that there were many case claim requests that took a while due to case purging. I don't think its correct to do a purge for a case claim sync and I don't believe the mobile does so.
> Don't purge caseDB for case claim sync

- src/main/java/engine/ClasspathFileRoot.java
- src/main/java/engine/FormplayerConfigEngine.java
For consistency reasons, switch to using `ReferenceManager.instance()` (as in `commcare-android`) rather than `ReferenceHandler`
cross-request: https://github.com/dimagi/commcare-core/pull/766
> Use ReferenceManager.instance() instead of ReferenceHandler

- src/main/java/installers/FormplayerOfflineUserRestoreInstaller.java
cross-request: https://github.com/dimagi/commcare-core/pull/763
Skip demo user restore parsing in `FormplayerOfflineUserRestoreInstaller`
@ctsims only returning `true` from install resulted in an infinite loop [here](https://github.com/dimagi/commcare-core/blob/a1a5d09e87985a85f0c208007e49b9dc47c2c35a/src/main/java/org/commcare/resources/model/ResourceTable.java#L366-L366) - parsing in a dummy `OfflineUserRestore` and then skipping initialization gives the desired result. Please let me know if I'm missing something
> Skip user restores in OfflineUserRestoreInstaller

- src/main/java/application/FormController.java
- src/main/java/session/FormSession.java
I think I messed this up in my SMS PR - when you get the *next* answer in prompt mode you know that the previous answer was `accepted`, but not for all requests (duh) 
addresses https://manage.dimagi.com/default.asp?270677
> Answer response isn't always positive, dummy

- src/main/java/services/NewFormResponseFactory.java
Restoring as a case was running into issues when a case purge was triggered; because the logged in user (the case) is not the owner, the case would be purged. Set `shouldPurge` to false in this mode.
> Don't purge CaseDB when restoring as a case

- src/main/java/api/json/JsonActionUtils.java
- src/test/java/tests/FormEntryTest.java
- src/test/resources/xforms/no_questions.xml
When using OQPS on a form with no questions (for example, only hidden values) we would crash. Fix that by returning an empty tree instead. 
Sentry: https://sentry.io/dimagi/formplayer/issues/438147580/?query=is:unresolved%20level:error
Shoutout to @pr33thi for helping me get to the bottom of this one!
> Do not crash when using OQPS on a form with no questions

- src/main/java/application/FormController.java
Fixes https://sentry.io/dimagi/commcarehq/issues/492026734/?referrer=slack
Seems like technically this should be a `GET` request but for the sake of the SMS migration accept `POST` too
> Allow POST requests to get-instance as well

- src/main/java/installers/FormplayerInstallerFactory.java
- src/main/java/installers/FormplayerOfflineUserRestoreInstaller.java
- src/main/java/installers/FormplayerProfileInstaller.java
- src/main/java/installers/FormplayerSuiteInstaller.java
- src/main/java/installers/FormplayerXFormInstaller.java
An earlier refactor for parity with `commcare-core/master` added the `StorageManager` to the `CommCarePlatform` class so we no longer need to configure it separately inside these installers. 
~~Contains commits from https://github.com/dimagi/formplayer/pull/641 so don't look into until that is merged~~
> StorageManager refactor

- src/main/java/api/json/JsonActionUtils.java
- src/main/java/application/FormController.java
- src/main/java/beans/ChangeLocaleRequestBean.java
- src/main/java/session/FormSession.java
- src/main/java/util/Constants.java
- src/test/java/tests/BaseTestClass.java
- src/test/java/tests/LocalizationTests.java
For easier debugging in App Preview. Not wired into anything in the front end at the moment but safe to merge on its own.
@orangejenny 
The languages should be available at form start in the 'data' object [here](https://github.com/dimagi/commcare-hq/blob/b322c7ce0e00790b81e4937b6fef19b03737a9cb/corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js#L144-L144)  under the `langs` key
> Add route for changing language of form session

- src/main/java/application/FormController.java
- src/main/java/application/FormplayerAuthFilter.java
Don't make `sessionId` cookie required in methods that SMS uses, only check for `sessionId` when not doing SMS authentication.
> Don't require sessionId cookie

- src/main/java/services/MenuSessionRunnerService.java
Addresses https://manage.dimagi.com/default.asp?277832
I hadn't realized we didn't evaluate `<assertion>` blocks in Formplayer - I thought we got them for free at the `commcare-core` level. This rectifies that. 
cc @orangejenny
> Check assertions in Formplayer

- src/main/java/services/MenuSessionRunnerService.java
https://manage.dimagi.com/default.asp?280046#1513916
This response does seem unnecessarily confusing. It seems reasonable to just get rid of it. I'm not sure what other situations besides the `case list menu item` would trigger it, but I think I'm ok with a silent error anyway.
I didn't find anything existent that distinguishes `clmi` items that's currently available, but maybe I can spend a bit more time at some point and figure out how to do that.
buddy: @snopoke 
not sure who else to tag --> @dannyroberts?
> unnecessary message

- src/main/java/application/FormplayerAuthFilter.java
What was being reported as an HMAC error in [sentry](https://sentry.io/dimagi/commcarehq/issues/754700558/) is acatully a `FormNotFoundException`.
Formplayer will now 404 on `FormNotFoundException` and any other errors will cause a 500.
> handle hmac exceptions separately from others

- src/main/java/sqlitedb/ApplicationDBPath.java
- src/main/java/sqlitedb/DBPath.java
- src/main/java/sqlitedb/UserDBPath.java
Fixes filepath references to use explicit file separators, rather than implicit ones
Fixes bugs that occur downstream if the paths don't match (Specifically failures to update the autoCommit behavior on the connection)
> Update File Path References

- src/main/java/application/WebAppContext.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/Constants.java
- src/test/java/utils/TestContext.java
Read timeout of 15 minutes matches the expiration period of locks used around restore requests to hopefully prevent those requests from hanging indefinitely and subsequently locking a user out of formplayer (until the next restart). While it's good to have this in place as a fallback, 15 minute lock periods make for a bad user experience, and this does not fix the root cause of that issue.
> Add HQ request timeouts

- src/main/java/application/WebAppContext.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/Constants.java
- src/test/java/utils/TestContext.java
The deploy of this code coincides with formplayer 401 errors from HQ on restore URLs. 
Notice the time of the first occurrance of the current formplayer errors
```
(production) cchq@formplayer2-production:~/www/production/log$ grep "HttpClientErrorException: 401" formplayer-spring.log | head
2019-10-17 19:30:16.851 ERROR 4660 --- [nio-8181-exec-3] application.AbstractBaseController       : Exception org.springframework.web.client.HttpClientErrorException: 401 Unauthorized making external request util.FormplayerHttpRequest@5864d204.
2019-10-17 19:39:22.577 ERROR 4660 --- [nio-8181-exec-2] application.AbstractBaseController       : Exception org.springframework.web.client.HttpClientErrorException: 401 Unauthorized making external request util.FormplayerHttpRequest@7efa5cf0.
```
Notice the …
> Revert "Add HQ request timeouts"

- src/main/java/application/WebAppContext.java
- src/main/java/services/RestoreFactory.java
- src/main/java/util/Constants.java
- src/test/java/utils/TestContext.java
Reverts https://github.com/dimagi/formplayer/pull/690
Changes since https://github.com/dimagi/formplayer/pull/688: https://github.com/dimagi/formplayer/commit/8501145de6fb84e7bcd767311ac69e105cd153c0
The default scope is singleton, so the previous version (#688) created a single `RestTemplate` instance that was used for all restore requests.
This has been deployed to and tested on staging. Testing actions taken:
- Navigate to [app](https://staging.commcarehq.org/a/dmiller-staging/apps/view/a6ee6bcff4f11ba66e7a6b0af966daf0/)
- Sync (success)
- Navigate to form
- Submit [form](https://staging.commcarehq.org/a/dmiller-staging/reports/form_data/833abd19-3ec5-4fef-9a32-6da470fea448/)
- Sync (success)
According to @dannyroberts a similar test workflow had failed on staging when he deployed and …
> Add HQ request timeouts (second try)

- src/main/resources/application.properties
Proposed change to https://github.com/dimagi/formplayer/pull/700 which would permit deployments with old settings to continue functioning without a config change. 
The jar-packaged settings are [reliably evaluated](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config) after the local settings, so this will never override user behavior, but will prevent users from needing to make a change before applying settings.
> Enable graceful upgrades for new settings

- build.gradle
- src/main/java/sandbox/SqlHelper.java
- src/main/java/sqlitedb/SQLiteDB.java
It's best practice for production Gradle builds to have explicit version dependencies, to ensure that build products are consistent.
This locks in the most up to date versions of the release libs, using spring-boot's new dependency manager for the libraries covered under its POM, and setting explicit dependencies for any other libraries without one.
To accept spring-boot's new versions, I also had to update a couple of JDBC connector details. They are tested locally, but have not been tested in a staging environment.
> Lock in Gradle dependency versions for modernized Spring libs

- src/main/java/application/WebAppContext.java
- src/main/java/services/RestoreFactory.java
- src/test/java/utils/TestContext.java
I ran into similar issues to what @millerdev fixed in https://github.com/dimagi/formplayer/pull/697, so I reworked the code to use a fresh `RestTemplate` object each time which fixed the issues.
This PR makes Web Apps support a 412 restore response from the server. Previously the behavior was that formplayer threw an error and Web Apps showed a generic error message, and all subsequent clicks showed the same error message, making it impossible to move past it until the db file got deleted.
Now the behavior is that when formplayer gets a 412, it deletes the userDB and syncs again without a sync token (i.e. without `since=...` in the URL). Other than incomplete forms getting silently deleted, and the restore possibly taking longer than normal, there's no sign that anything special happened …
> Clear the userDB and retry when we get a 412 on restore

- build.gradle
A heap dump indicates that we are seeing big thread process leak from
https://github.com/getsentry/sentry-java/issues/548
which is fixed on newer versions. Impact is unclear, but can't rule out significant issues.
> Update Sentry dependence

- src/main/java/database/models/EntityStorageCache.java
- src/main/java/database/models/FormplayerCaseIndexTable.java
- src/main/java/sandbox/ArchivableFile.java
- src/main/java/sandbox/JdbcSqlStorageIterator.java
- src/main/java/sandbox/SqlHelper.java
- src/main/java/sandbox/SqlStorage.java
- src/main/java/sandbox/UserSqlSandbox.java
- src/main/java/services/FormplayerStorageFactory.java
- src/main/java/services/RestoreFactory.java
- src/main/java/sqlitedb/SQLiteDB.java
Updates to the way that we are managing jdbc connections and objects. 
Ensures that all connection objects are closed out to try and fix the issue with the system leaking paged sqlite journal files.
Replaces (where cleanly possible) meaningless try{} finally{} blocks with cleaner [try with resource](https://www.baeldung.com/java-try-with-resources) patterns, now that we are on a compatible version.
> Modernize Database Connection Management

- src/main/java/sandbox/SqlSandboxUtils.java
The code which actually builds and establishes the SQLite connections was attempting to set the autoCommit behavior of the connection do a default state before returning it to the caller, and in doing so was unintentionally creating a hanging connection which was never closed.
This code doesn't push down the `autoCommit` portion of the change to the actually created connection, since the attempt to set the behavior of the connection to autoCommit was failing since it was only changing the behavior of the orphaned connection. It may be worth exploring whether actually setting the autoCommit value would work and/or have performance gains, but I think the system expects autoCommit to be active by default now and can't see how it would work otherwise.
> Fix Issues with Dangling DB Connections

- settings.gradle
Newer gradle versions deprecated the way we were setting the jar basename, which means the output jar for formplayer is now dependent on the name of the root project directory. This is breaking the production of the staging jar.
This change should provide a consistent output instead.
I tested manually on the buildserver after applying this change and it corrected the jar name output.
> Ensure project root name is set explicitly

- src/main/java/services/HqUserDetailsService.java
Locally, Formplayer had issues for me when I made requests too quickly back to back because the RestTemplate configured to make the auth request was being re-used, including the underlying connection object, resulting in
`localhost:8000 failed to respond; nested exception is org.apache.http.NoHttpResponseException: localhost:8000 failed to respond`
This ensures that a new RestTemplate is used for each auth attempt and fixes the issue for me. It looks like the only reason the old behavior was configured was to support a mock for testing, so this should be a safe change.
> Fix HTTP Connection issues due to re-use of Rest Template

- src/main/java/application/FormController.java
- src/main/java/util/FormplayerPropertyManager.java
Spec: https://github.com/dimagi/commcare-hq/issues/26940
Probably won't be useful for a lot of domains where syncs take a while.
Shouldn't be used broadly in production until better tested
> Basic post-form autosync

- src/main/java/application/FormController.java
- src/main/java/application/WebAppContext.java
- src/main/java/objects/FormVolatilityRecord.java
- src/main/java/services/MenuSessionRunnerService.java
- src/main/java/session/FormSession.java
- src/test/java/utils/TestContext.java
Allows forms to declare a volatility key for their case entities. When volatile forms are begun of completed for a specific case a record is made, and users are warned if they open a form which was recently opened by another user, or submitted by another user (unless they have synced since after the form was submitted). 
This is hidden for now, and shouldn't affect most domains. I don't love the fact that the volatility indicators are stored inside the form record, I think it would be way better if this was generalized more heuristically against the session, but it will be easy to build on top of later.
> Form Volatility Indicators

- src/main/java/beans/NotificationMessage.java
- src/main/java/objects/FormVolatilityRecord.java
Minor cleanups for the user experience around volatility warnings. Strip domain info from warning text and use new warning coding when accepted by HQ (but works before the other PR is accepted)
> UX cleanups for volatility warnings

- src/main/java/application/AbstractBaseController.java
- src/main/java/application/DebuggerController.java
- src/main/java/application/FormController.java
- src/main/java/application/IncompleteSessionController.java
- src/main/java/application/MenuController.java
- src/main/java/application/UtilController.java
- src/main/java/beans/NotificationMessage.java
- src/main/java/beans/menus/BaseResponseBean.java
- src/main/java/objects/FormVolatilityRecord.java
- src/main/java/services/InstallService.java
- src/main/java/services/MenuSessionRunnerService.java
- src/main/java/session/MenuSession.java
- src/main/java/util/Constants.java
* Exposes error notifications to sentry and datadog counters
* Sends all kind of exceptions to Sentry
Notes: 
1. Would be great to get this deployed to staging to test first (As my HQ setup is still not great, I was not able to fully test it)
2. Is there a better Spring way to be able to avoid multiple `logNotification` calls here ?
> Exposing Error Notifications to Sentry

- src/main/java/application/DebuggerController.java
- src/main/java/application/UtilController.java
- src/main/java/aspects/LockAspect.java
- src/main/java/beans/LockReportBean.java
- src/main/java/beans/NotificationMessage.java
- src/main/java/services/FormplayerLockRegistry.java
- src/main/java/util/Constants.java
Many long running request operations in formplayer can leave user sandboxes locked for very long amounts of time with no recourse. This makes operations like load testing especially painful.
This introduces an endpoint which forces the same 'lock eviction' process as would naturally occur if a request had come after the long timeout. 
Includes: https://github.com/dimagi/commcare-core/pull/893 to increase coverage of interruptable requests
> Lock Eviction Endpoint

- src/main/java/application/WebAppContext.java
- src/main/java/services/RestoreFactory.java
- src/test/java/utils/TestContext.java
Support for Card: https://trello.com/c/gfl9nnI7/32-mobile-endpoint-access-permissions
Before submitting restore requests to HQ, set an origin token in redis that HQ can use to identify that the request is internal to the environment.
> Include origin token in restore requests

- src/main/java/application/FormplayerAuthFilter.java
- src/main/java/exceptions/SessionAuthUnavailableException.java
- src/main/java/services/HqUserDetailsService.java
Previously we were throwing a generic 500 if the lookup for the user's session failed (because the user was logged out). Changes that to return a 401.
> Signal 401 on Unavailable Session

- src/main/java/application/WebAppContext.java
- src/main/java/util/FormplayerSentry.java
Initial Ticket: https://dimagi-dev.atlassian.net/jira/servicedesk/projects/SUPPORT/queues/custom/53/SUPPORT-1640
A barrage of unrelated surfaced the problem that once Sentry issues were reported, the reporting thread never closed out. This makes sure that connections are closed according to the bean lifecycle.
> Ensure Sentry async connections are closed on cleanup

- src/main/java/application/FormplayerAuthFilter.java
- src/main/java/application/WebAppContext.java
- src/main/java/services/FallbackSentryReporter.java
Initial Authorization in Formplayer is performed through a Request Filter before the internal Spring Request lifecycle. This means that all of the core control mechanisms available in a normal scope (Default Exception Handling, Sentry breadcrumbs,  Request Logging aspects) are unavailable and errors in the Auth process were not logged in Sentry, did not return a clear response, and were logged as
```
2020-06-03 19:24:12.307 ERROR 9294 --- [o-8181-exec-128] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.json.JSONException: JSONObject["session-id"] not found.
at org.json.JSONObject.get(JSONObject.java:473) ~[json-20131018.jar!/:na]
at org.json.JSONObject.getString(JSONObject.java:654) …
```
> Catch Errors in Auth Filter

- src/main/java/application/AbstractBaseController.java
- src/main/java/application/DebuggerController.java
- src/main/java/application/MenuController.java
- src/main/java/application/UtilController.java
- src/main/java/beans/EvaluateXPathResponseBean.java
- src/main/java/beans/NotificationMessage.java
- src/main/java/exceptions/ApplicationConfigException.java
- src/main/java/services/MenuSessionRunnerService.java
Currently when formplayer catches `assert` errors we re-throw through the top level "error" notification path, which isn't differentiated from real code errors in sentry, datadog, other monitoring.
This switches the report path to present like a proper app issue (example below, old behavior on bottom, new behavior on top)
This also eliminates the Sentry Logging for DB Clear events which were reported as errors, but if that change isn't desirable it is easy to revert, and updates other noisy notifications being thrown as errors currently.
> Update Error Reporting Paths

- src/main/java/exceptions/SqlArchiveLockException.java
- src/main/java/sandbox/ArchivableFile.java
- src/main/java/sandbox/SqlSandboxUtils.java
Core PR: https://dimagi-dev.atlassian.net/browse/COV-8
A few things in here:
1) Previously neither the Formplayer process nor the db archive script actually had the ability to clean up stale archive file locks. Archive file locks are now expunged after 5 minutes (this is a long time given the expected lifetime of such a lock)
2) When locks didn't go away on their own, formplayer threads would just hang in an endless loop. It looks like someone didn't understand how thread interrupts work and may have been assuming that calling thread interrupt did something to exit the loop it was in, but it didn't.
3) Fixed the lock ordering to always create a lock before performing the rest of the operations, to prevent race conditions where locks were created after checks
4) [Most Relevant to the …
> Improved Locking Pattern for Archivable Files

- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/services/SubmitService.java
- src/main/java/org/commcare/formplayer/util/Constants.java
Easiest to review with w=1
As far as I can tell the `submitResponse.getStatusCode().is2xxSuccessful` clause was never getting run because `submitService.submitForm` with the default error handler will throw an error instead of returning if it's a 4xx or 5xx response; I guess if we got a 3xx response it would have hit that clause.
Now we make it never raise and always return, letting us handle the status code manually.
> Fix submit error reporting and single out too-many-requests

- src/main/java/org/commcare/formplayer/application/Application.java
- src/main/java/org/commcare/formplayer/util/PrototypeUtils.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
Ensures that after the Application spins up, each worker thread gets its own PrototypeFactory to prevent thread conflicts between the underlying vectors and other shared memory.
Depends on a cross-posted formplayer commit which should be pulled first:
https://github.com/dimagi/commcare-core/pull/923
> Use Thread Local Statics for Object Prototypes

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
The new(ish) "aggressive" sync processing will force syncs before processing requests on some short-ish timeframe (IE: At least one sync every 5 mintues). 
This mechanism was previously applied to both Menu requests and in-form actions (like submitting an answer to a question, or adding a repeat), which was unintended. Syncing during a form can result in mismatches between the form start dataset and the current dataset, and introduces unnecessary churn.
This removes aggressive autosyncing from all form entry actions.
> Remove aggression from in-form requests

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Due to differences in the sync paths, if users needed an 'autosync' event because it had been to long since the previous sync a 412 response wouldn't be handled properly and would cycle for 5-10 requests when it retried.
NOTE: this doesn't autopurge during the sync simply to be as consistent as possible with the current behavior to make sure to get this fixed asap.
> Allow for 412 recovery in aggressive/timed out syncs

- config/application.example.properties
- src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Currently the timing code includes the amount of time spent waiting for a restore download in the amount of time it takes to parse this download, leading to confusing timing metrics
This change splits out those timings int non-overlapping timers
> Fix duplicate restore timings

- src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
This tag takes on too many values to be useful or cost-effective.
> Remove "user" tag from datadog metrics

- src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
This appears to be a very time consuming part of the restart process. Adding log events to confirm.
> Add log info for session purge timings

- src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
- src/main/resources/application.properties
The current behavior clears out all stale (more than 7 day old) form sessions on startup, which for large production environments has gotten untenable (Taking up to 45 minutes with a broad worker pool and hundreds of thousands of sessions). 
This sets that behavior to be dependent on the app config setting
```
commcare.formplayer.purge.trigger=startup
```
which can be used in smaller environments or on-demand without requiring new deployment to be halted until complete by default.
> Add Flag for Startup Cleanup of Form Sessions

- src/main/java/org/commcare/formplayer/application/RequestResponseLoggingFilter.java
Adds the source IP address redundantly to this log channel for more convenient in-place aggregation.
Note: For production (or any environments behind a load balance or IP carrying proxy), a new directive will need to be added to deploy scripts before this address is processed correctly.
> Add Source ID to Request Logs

- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/util/FormplayerPropertyManager.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
This adds a flag to restore requests sent on form completion to ask HQ to avoid sending down fixtures. There will be linked HQ PR that implements that for domains that enable a feature flag.
> skip fixtures

- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Building on https://github.com/dimagi/commcare-core/pull/936
This PR uses the saved reference expansion, and shares evaluation context between the `EntityScreen` and the `EntityListResponse`.
> shared references

- src/main/java/org/commcare/formplayer/services/BrowserValuesProvider.java
- src/test/java/org/commcare/formplayer/tests/BrowserValuesProviderTest.java
I realized that I was not logging to sentry the tz id that the browser reports, which made troubleshooting harder. This tries to answer the question of whether the reported tz id from the browser is `null` or another value that is not recognized by the java timezones. 
Example error message `Reported timezone America/New_York generated tz name Eastern Standard Time with offset -18000000 which is different than reported offset -18000`
This is more out of curiosity, and most likely this feature will be closed out soon with the following steps:
1. we will stop logging to sentry and *might* log to console instead to avoid sentry costs
2. if the number of users/browsers affected is not reasonable, we will disable the `%Z` for now.
> browser tz provider discrepancy check better logging

- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/application/WebAppContext.java
- src/main/java/org/commcare/formplayer/services/InstallService.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/main/java/org/commcare/formplayer/util/UserUtils.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/utils/TestContext.java
This PR has two components to hopefully speed up menu navigation.
1) Defers initialization of EntityScreens until necessary
2) Updates the menu session with known valid selections (those previously evaluated) without evaluating the input at the screen level.
It tracks valid selections in redis, keying off a combination of username, restore as user, and domain, and clearing the cache on restore, app install, and form submission.
I don't love the changes to the code organization, especially pushing the initialization and auto advance logic out of the centralized methods (`createFreshEntityScreen` and `getNextScreen`) in `MenuSession.java` and into each of the places that need it, but it was the only way I could figure out how to do it.
> Session cache

- src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
Minor.
Mobile case claim respects the order prompts were entered in the HQ configuration, but web apps does not.
Depends on https://github.com/dimagi/commcare-core/pull/953
> Updated case claim to respect ordering of prompts

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
https://dimagi-dev.atlassian.net/browse/USH-366
Adds support for actions marked as "auto_launch." When a case list with such an action is viewed, the user will not be shown the case list and will instead proceed as though they clicked on the action.
Not especially proud of this code, especially the flag being passed through five layers. Auto-launching case claim only works if the case list is the final result of the `advanceSessionWithSelections` loop that iterates over the current selection. If the action is auto-launched after the case id has been added to selections, the user gets perpetually kicked back to the case claim screen instead of advancing on to the form.
Depends on https://github.com/dimagi/commcare-core/pull/949
HQ changes, which depend on this PR but can be deployed …
> Added auto launching of actions

- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
https://github.com/dimagi/formplayer/pull/783/ "works" by [executing the autolaunch action](https://github.com/dimagi/commcare-core/blob/1c8d2a04c1219d99e9afd923d2556f3fe2c02e7c/src/cli/java/org/commcare/util/screen/EntityScreen.java#L87-L91) inside the `EntityScreen` constructor. Since that action doesn't get a session frame the same way a real user action would, there are downstream problems, notably the inability to actually claim cases.
Instead of figuring out how to make a better fake user action, this PR changes formplayer's case list response to include a flag telling web apps to immediately make an additional request to case claim. This should mimic real behavior better. Most of the logic from https://github.com/dimagi/formplayer/pull/783/ is retained so that if the case list does …
> Auto launching of actions, round 2

- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
Depends on https://github.com/dimagi/commcare-core/pull/961
Will update the commcare core ref when that is merged.
This is the formplayer component of the autolaunch fixes. The biggest change is allowing the `MenuSession` in formplayer to directly update the `SessionWrapper` rather than having the cli handle the input, to bypass rendering those cli screens.
> Revert 791 jls/autolaunch action round 2

- src/main/java/org/commcare/formplayer/api/process/FormRecordProcessorHelper.java
This removes one component of the case purge process that scales unnecessarily with the number of cases being purged by changing one sql delete per case to one bulk delete (using a method we already have).
The two methods are [defined here](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/database/models/FormplayerCaseIndexTable.java#L108-L127)
> bulk clear purged indices

- src/main/java/org/commcare/formplayer/application/UtilController.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
1. Remove the requirement for the `sessionid` cookie to be present. Without this the request with be authenticated using the HMAC digest header.
2. Don't blindly assume that the 'loginas' user is a mobile user. HQ requires that when using HMAC digest auth the `as` parameter is present to indicate which user the sync is for. When forcing the sync of a web user we need to specify the web user as the 'loginas' user.
> Small changes to allow forcing user DB sync from HQ

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
https://dimagi-dev.atlassian.net/browse/SAAS-11579
Login_as users with characters like `+` and `-` cause an error because the django app converts the `+` query param to a ` `.
Formplayer needs to URL encode the `as` query param. Mostly followed https://stackoverflow.com/a/51678215 to use a `UriComponentsBuilder` instead of a normal url string builder, and manually url encoded the `as` param (and only this one for now, since I don't want to cause any potential issues with the other params). Happy to url encode more if we're confident it won't break.
Unfortunately I looked at [RestoreFactoryTest](https://github.com/dimagi/formplayer/blob/master/src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java) and it didn't have the skeleton to easily test this. I can devote time to …
> url encode loginas

- src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java
- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
This allows forms to skip some of the validation that occurs on submit. If the answer in the submission matches the answer formplayer's model, it will no revalidate. This will still catch required questions and changes since the last validation, but will no longer catch the case where a later response invalidates an earlier one. As such, it should be used with caution, but will provide meaningful speed ups when used in that way.
> add flag for skipping full validation

- src/main/java/org/commcare/formplayer/session/MenuSession.java
Minor bugfix. Previously when using a search-first workflow, breadcrumbs on the case search screen were:
`Home > App Name > Menu Name > Search Button Label`
But both the menu name and search button label options redirected the user back to the search screen.
Now breadcrumbs in that scenario are just:
`Home > App Name > Menu Name `
> Removed breadcrumb from autolaunch actions

- src/main/java/org/commcare/formplayer/services/FormplayerLockRegistry.java
The default pool available for sandbox ID Hash -> Lock ID is currently very, very small (255) which on a high-concurrency machine could cause significant problems with unintentional locking collisions.
Long term we should probably explore a better way of measuring / reducing the collisions in general due to the high likelihood of overlap (even 65k may not be that much) and due to how uneven Java String hashes are, but this jump should be more than enough short-term unless the hash overlap is extraordinarily non-uniform.
> Increase default lock pool size from 255 to 65k

- src/main/java/org/commcare/formplayer/repo/impl/PostgresFormSessionRepo.java
Switch from `count` to `exists` since it's has better performance. Ideally we should add a DB ID field to this table so that we can tell if the data is persisted or not without having to do a DB query.
> use exists instead of count

- src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
This current implementation will become moot with plans to improve how we interact with the datadog client, but if we want to merge for now this is what it looks like.
> Add form_name tag to datadog metrics for submit-all requests

- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
In addition to sending form names to sentry, we also want to send to datadog to allow for filtering there. Some slight changes were made to the `recordTimingCategory` method to make it easy to add more data in the future. I kept the method overloading that was already in place to not break existing calls.
> Send form name to datadog for granular timings on submit requests

- src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
Lowering thresholds for `submit-all`, `answer` and `nagivate_menu` requests. See this [JIRA ticket](https://dimagi-dev.atlassian.net/browse/USH-619?focusedCommentId=116560&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-116560) for more details about # of additional requests that will be sent to sentry due to this change.
> Add slow request thresholds for specific requests

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
Since the introduction of the `for` parameter was problematic due to how SMS forms works (https://github.com/dimagi/commcare-hq/pull/29092) we can just reuse the 'as' field and update HQ to record the auth type.
> reuse 'as' parameter when doing a force sync

- src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java
- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
We were generating the full form json (`tree` attribute that gets passed to the front end) after every answer validation, when we don't need it at all during the validation stage. We never pass that back to the front end regardless of whether or not validation is successful. We do still need that when answering individual questions, which is why this is a flag for now, although I would like to refactor some of this code so that each part can call what they need, rather than having one method with a bunch of flags.
> skip json creation on validation

- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
The previous method of specifying the strategy was out of date
and generated a v1 UUID. The default strategy now is v4 random
UUID: https://docs.jboss.org/hibernate/orm/5.1/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators-uuid
> use a better UUID generation strategy

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/util/Constants.java
Adds a `module` tag to sentry and datadog. I don't think all 4 values are necessary (specifically could remove `command` and `query` but just want to verify before doing so).
> Add module tag 

- src/main/java/org/commcare/formplayer/configuration/JpaAuditConfiguration.java
- src/main/java/org/commcare/formplayer/db/migration/V19__form_session_correctly_typed_fields.java
- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
* `dateOpened` is a date but stored in the DB as a string with a very unhelpful format "Wed Feb 10 17:44:59 SAST 2021"
* replace it with an auto-generated timestamp column that stores UTC time
* `sequenceId` is an integer but saved in the DB as a string
* replace it with an auto-incremented `version` column
* this has the added benefit of providing [optimistic locking](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#locking-optimistic)
> add column to form session table to replace incorrectly typed columns

- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
- src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
- src/main/java/org/commcare/formplayer/services/FormSessionService.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
The addition of the `version` column has caused two bugs in the session list view:
* null values caused null pointer exception since the type of `version` was `int`
* deleting old sessions did not work as the DB layer interpreted the `null` version as meaning the model was not saved
QA also found this bug on staging: https://dimagi-dev.atlassian.net/browse/QA-2589
> fix session list view for old sessions (with 'null' version)

- build.gradle
- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
- src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
https://dimagi-dev.atlassian.net/browse/USH-690
* Setting [updatable=false](https://www.objectdb.com/api/java/jpa/Column/updatable) on the fields tells the DB layer that it shouldn't include those fields in update statements.
* fields that get updated are: `sequenceId`, `version`, `currentIndex`, `instanceXml`, `initLang` (locale) 
* Refactor the model to more accurately reflect it's usage and use [Lombok](https://projectlombok.org/features/GetterSetter) to auto generate the required getters and setters
> Revert "Revert "only update changing fields when saving form sessions""

- src/main/java/org/commcare/formplayer/application/IncompleteSessionController.java
- src/main/java/org/commcare/formplayer/repo/FormSessionRepo.java
- src/main/java/org/commcare/formplayer/services/FormSessionService.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
- src/test/java/org/commcare/formplayer/services/FormSessionServiceTest.java
This PR adds filtering to the session list view query to return only sessions for the domain of the request and the 'user' + 'asUser' combination.
Confirmed with @dimagi/product that this should be fixed to only show sessions appropriate to the domain and user combo.
Can be reviewed by commit.
https://dimagi-dev.atlassian.net/browse/SAAS-11862
Extract from the ticket:
The incomplete forms list view shows all sessions for the logged in user including:
1. forms that the user completed in any domain they have access to
* If a web user has access to multiple domains and they have incomplete forms, the list view shows all forms across all domains
* forms that the user completed with all ‘login as’ users that they have used
2. If a user using “login as” with multiple other users, all incomplete …
> limit form sessions returned by incomplete session view to those of the correct domain & login user

- .travis.yml
- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
Hibernate doesn't support null values for version columns so either
we need to populate it in the DB or lazily as in this commit.
Going for lazy option to avoid having to udpate large amounts of data
on the DB.
> populate version along with sequence ID

- src/main/java/org/commcare/formplayer/sandbox/ArchivableFile.java
https://dimagi-dev.atlassian.net/browse/SAAS-10840
Followed https://github.com/dimagi/commcare-core/pull/893
A few points:
- We also have [InterruptedRuntimeException](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/exceptions/InterruptedRuntimeException.java) which might be better?
- `Thread.interrupted()` clears the interrupted status as opposed to Thread.currentThread().isInterrupted(), I can't think of why clearing it would be a problem for us, but something to think about.
> add interrupt check at decompress

- src/main/java/org/commcare/formplayer/Application.java
- src/main/java/org/commcare/formplayer/repo/FormplayerBaseJpaRepoImpl.java
This adds a custom JPA repository implementation that uses ``Session.update`` instead of
``Session.merge`` when saving. This avoids the additional 'select' that
happens when saving detached entities.
With caching enabled Formplayer caches entities between requests to avoid having to re-fetch them
from the DB on successive requests. Since the caching results in detached
entities, the advantage of caching is lost since ``Session.merge`` re-fetch the entity from the DB on update.
It is safe to skip the "select before update" as long as the Formplayer
request routing is consistent. If we remove the consistent routing we would need
to use a global cache (instead of per machine).
Hibernate Docs:
https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/Session.html#merge-java.lang.Object- …
> custom JPA repository implementation to avoid 'select on update'

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
`form_name` tag already exists on submit-all and answer requests, so this is just adding to navigate_menu requests.
> Add form_name tag to navigate_menu requests that open forms

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
The previous logic mixed whether to do a search with whether include user input and default values in the search. This separates those two and attempts to clear up the naming.
https://dimagi-dev.atlassian.net/jira/servicedesk/projects/SUPPORT/queues/custom/81/SUPPORT-8316
Followup for 7839d7d4e5335762333a19d63a58f4909abed19a, restores the previous `autoSearch` flag that's passed to `doQuery`, while preserving the new logic that's used to determine whether or not to call `doQuery`.
> separate autosearch from skip default

- src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
https://dimagi-dev.atlassian.net/browse/SAAS-11642 
Corresonding cchq PR: https://github.com/dimagi/commcare-hq/pull/29279
A client has asked that we support translations for `repeat.dialog.add.new` which correspond to the `Add new repeat` button.
I believe we handle App UI Translations by having formplayer translate the text and put it in a specific section in the response json. This is a CC UI translations, which we have very little of. Since these are statically defined key names, instead of following the same approach of inserting the translation into a specific portion of the json response (which gets pretty hairy since translations can be nested in there), I created a top level `translations` attribute to the base response class where certain endpoints can append translations that …
> add translations attr in form response

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
When we do a search again for a query definition with default search on, the user entered query prompts doesn't get incorporated in the case search uri resulting in case search results with default definition. 
Introduced in https://github.com/dimagi/formplayer/pull/921/
> Bug Fix: Search prompts getting skipped from case search 

- src/main/java/org/commcare/formplayer/auth/CommCareSessionAuthFilter.java
This adds a check to the filter matcher and only attempts to do session auth if the session cookie exists.
This should remove the noise from https://sentry.io/organizations/dimagi/issues/2296129092/
> don't run session auth filter unless the cookie exists

- src/main/resources/application.properties
These weren't properly named. I've also added the `formplayer.http.client` metrics which contribute significantly to our custom metric quota.
> disable system metrics

- src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
- src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
- src/main/java/org/commcare/formplayer/util/Constants.java
- src/test/java/org/commcare/formplayer/tests/FormplayerDatadogTests.java
* Remove `formplayer.metrics.requests` entirely and update all usages with `formplayer.metrics.timings.count`
* Changes to `formplayer.metrics.timings.*` tags
    * Only add the 'domain' tag to for requests > 1s
    * Drop the following tags altogether: "unblocked_time", "blocked_time", "restore_blocked_time", "install_blocked_time", "submit_blocked_time"        
        * These tags were either unused or can be replaced with the granular timings metrics.
> prune formplayer metrics to reduce cost + remove unused

- src/main/resources/application.properties
This was only enabled in some envs to allow testing but we can now do full rollout.
> enable caching by default

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/main/java/org/commcare/formplayer/util/FormplayerPropertyManager.java
https://dimagi-dev.atlassian.net/browse/USH-636
Auto advances any menu screen with a single option if the property `cc-auto-advance-menu` is enabled. 
It was hard to test this feature without fixes in `caseSearchSkip` due to which I ended up merging `caseSearchSkip` in the current branch
cross-request: https://github.com/dimagi/commcare-core/pull/993
> Auto advance Menu screen with single option

- src/main/java/org/commcare/formplayer/beans/menus/EntityDetailListResponse.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityDetailResponse.java
https://dimagi-dev.atlassian.net/browse/SAAS-11685
and QA https://dimagi-dev.atlassian.net/browse/QA-2976?focusedCommentId=141272
Needs to pass down the list of case list property format. In the code this is called `templateForms` so I used that naming, but should we name it to something else that is more understandable for the frontend? 
Tested locally:
> pass down templateforms list in getDetails for markdown

- config/application.example.properties
- src/main/java/org/commcare/formplayer/application/WebAppContext.java
- src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
- src/main/java/org/commcare/formplayer/util/Constants.java
- src/main/java/org/commcare/formplayer/util/FormplayerDatadog.java
- src/test/java/org/commcare/formplayer/tests/FormplayerDatadogTests.java
- src/test/java/org/commcare/formplayer/utils/TestContext.java
https://dimagi-dev.atlassian.net/browse/SAAS-12284
Now that feature flags are available in formplayer, this should be implement asap. There are a few things I'm having trouble with:
- testing locally I can't seem to get enabled toggles on the user bean even though I know I enabled some on the HQ side. Are there any additional steps to take to enable feature flags on formplayer?
- the automated test should mock the FeatureFlagChecker to return true or false when necessary. Need some help with that since it doesn't appear that mockito can mock static methods? Could be wrong.
HQ PR: https://github.com/dimagi/commcare-hq/pull/29815
> Replace detailed tagging properties value with feature flag check

- src/main/java/org/commcare/formplayer/configuration/WebSecurityConfig.java
- src/test/java/org/commcare/formplayer/tests/CsrfIntegrationTest.java
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11750
Using `CookieCsrfTokenRepository` to manage the csrf token generation. It persists the CSRF token in a cookie named "XSRF-TOKEN" and then reads from the header "X-XSRF-TOKEN"
Corresponding HQ PR: https://github.com/dimagi/commcare-hq/pull/29954
In case of 403s this PR should be reverted first and then the HQ PR can be reverted. 
First the HQ PR should be deployed https://github.com/dimagi/commcare-hq/pull/29954. 
Once that is successful, we can deploy this PR.
> csrf protection

- src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
PR into https://github.com/dimagi/formplayer/pull/984
https://dimagi-dev.atlassian.net/browse/USH-1185
This uses the same design, and similar code, as https://github.com/dimagi/commcare-core/pull/1024: when executing the stack of an endpoint, pause at the end of each operation and run a sync request if needed.
Note the @ctsims has some design feedback on https://github.com/dimagi/commcare-core/pull/1024 which I haven't thought about yet, but any changes there will likely also get applied to this PR.
> Smart linking MVP: claim cases on formplayer

- src/main/java/org/commcare/formplayer/api/json/PromptToJson.java
- src/main/java/org/commcare/formplayer/beans/QuestionBean.java
- src/test/java/org/commcare/formplayer/tests/FormEntryTest.java
https://dimagi-dev.atlassian.net/browse/USH-1070
We want to show the `question_id` in the web apps errored questions text whenever question text is missing. 
HQ PR - https://github.com/dimagi/commcare-hq/pull/30259
> Sends question_id to webapps

- src/main/java/org/commcare/formplayer/aspects/UserRestoreAspect.java
- src/main/java/org/commcare/formplayer/beans/AuthenticatedRequestBean.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
Now that HQ will only support livequery, we don't need these options in the formplayer code.
> remove livequery options

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
- src/main/java/org/commcare/formplayer/session/FormplayerInstanceInitializer.java
- src/main/java/org/commcare/formplayer/session/FormplayerSessionWrapper.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
PR into https://github.com/dimagi/commcare-core/pull/1040
This moves the initialisation of external data sources to the session wrapper to ensure that they are always initialised when required. The potential downside here is that it get's called more frequently than required.
First two commits are a minor pre-factor.
> move prepare external sources into the session wrapper

- README.md
I ran into an error with my Java version while trying to get Formplayer going from this repo. Turns out it's Mac related and added a link to a StackOverflowfix that might be helpful to others.
Only a Readme edit, no code changes.
> Update README to include Mac installation error fix

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
PR into https://github.com/dimagi/formplayer/pull/1028
I [originally added this sync](https://github.com/dimagi/formplayer/pull/984#issuecomment-876702999) for the sake of claiming cases, but syncing is now handled a few lines down, in `doSyncGetNext`, only if a claim actually happens.
> Removed automatic sync from smart link navigation

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/web/client/WebClient.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
This is a (almost) pure refactor with the following goals:
* simplify logic
* create a single entry point for collecting request headers
* tests for the logic
One side effect here is that the `X-OpenRosa-Version` header is now always set to `3.0` where before it was sometimes `2.0`. I consider this an improvement.
The other side effect of the separation between restore type and the request headers is that HMAC auth is no longer enforced 'case restore' requests. I don't think that is and issue.
Best reviewed by commit.
> refactor restore factory getUrl and getHeaders

- src/main/java/org/commcare/formplayer/db/migration/V11__form_session_add_missing_appid.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
- src/test/java/org/commcare/formplayer/repo/MenuSessionRepoTest.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
- src/test/java/org/commcare/formplayer/tests/GroupTests.java
- src/test/java/org/commcare/formplayer/tests/NewFormTests.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
- src/test/java/org/commcare/formplayer/utils/TestContext.java
Prep for Spring upgrade https://github.com/dimagi/formplayer/pull/1051
> fix deprecation warnings

- src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
- src/main/java/org/commcare/formplayer/application/GlobalDefaultExceptionHandler.java
This moves the controller exception handling from the base controller into a [Controller Advice](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-controller-advice). The advantage of this is that we have have global exception handling without the need to inherit from the same base controller.
> move exception handling into global advice

- src/main/java/org/commcare/formplayer/screens/FormplayerQueryScreen.java
- src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/web/client/WebClient.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
- src/test/java/org/commcare/formplayer/tests/EndOfFormNavFormLinkingWithQueryTests.java
- src/test/java/org/commcare/formplayer/tests/FormEntryWithQueryTests.java
- src/test/java/org/commcare/formplayer/web/client/WebClientTest.java
Redo of https://github.com/dimagi/formplayer/pull/1029 with changes from master.
https://dimagi-dev.atlassian.net/browse/USH-1308
cross request: https://github.com/dimagi/commcare-core/pull/1060
This will require HQ changes since the `registry_case` endpoint only supports GET: https://github.com/dimagi/commcare-hq/blob/0f4bb130fc2da56882a499e88a3f580e1cd66810/corehq/apps/ota/views.py#L410-L414
> Switch case search to make a post request (redo)

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/test/java/org/commcare/formplayer/tests/FormEntryWithQueryTests.java
The main impetus for this refactor was to get `cc-auto-advance-menu` to work when there are queries after the last selection. Previously the auto-advance logic was executed during screen selection processing. When there is a query after the last selection the auto-advance was skipped.
This refactor moves all non-selection based navigation to it's own method and runs the logic in a loop as long as the session was advanced which makes it a more generalised solution.
The refactor also allowed simplifying some other logic.
Best reviewed by commit.
I made this branch on top of https://github.com/dimagi/formplayer/pull/1028 since that is where the query logic is added but I do not intend to merge it into that branch and will keep it separate until #1028 is merged.
Cross request: …
> refator advance session with selections

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/util/RequestUtils.java
- src/main/java/org/commcare/formplayer/web/client/WebClient.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
https://dimagi-dev.atlassian.net/browse/SAAS-12830
The refactor in https://github.com/dimagi/formplayer/pull/1045 changed how HMAC auth was calculated for URLs with no query params.
First commit is a prefactor, 2nd commit is the actual fix.
This PR updates tests to validate the HMAC headers.
> [bugfix] Fix HMAC header for requests without URL query params

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/resources/application.properties
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
Moves the restore URLs outside of the code and into the properties file. This also uses URL templates which handles all the encoding etc. which means we don't have to do it.
I started working on this because of the upcoming change in the "case restore" URL: https://github.com/dimagi/commcare-hq/pull/30826.
This does change the encoded URLs slightly since it also encodes characters like `*`. This is not an issue since it is a standard encoding which Django handles transparently.
> refactor restore URLs to use URL templates from properties

- build.gradle
I do not think we are vulnerable to this CVE since we do not use log4j however for the sake of precaution we are updating the 'log4j-to-slf4j' library along with 'log4j-api'.
CVE: https://www.randori.com/blog/cve-2021-44228/
If there are compatibility issues we will need to upgrade Spring to > 2.6.0 which is currently blocked by our usage of PostgreSQL 9.6: https://github.com/dimagi/formplayer/pull/1053
> upgrade log4j due to  CVE-2021-44228

- src/main/java/org/commcare/formplayer/application/DebuggerController.java
https://dimagi-dev.atlassian.net/browse/SUPPORT-12366
Bug introduced by [this PR](https://github.com/dimagi/formplayer/pull/1005) which defaulted `getInstanceXml()` to serialize all data (ignore relevancy). In addition to this identified spot, I'm looking through other `getInstanceXml()` calls to determine if it is expected that they serialize all data.
I replicated Clayton's [test app](https://www.commcarehq.org/a/corpora/apps/view/2d262ab3b3c5090876b15ba1e1021ef7/form/91f50ad022bf45cbbab460b32b37a6a9/source/#form/the_hidden_value_checker) locally to reproduce the issue. 
Before the fix:
After the fix:
> Respect relevancy when returning instance xml for data preview

- src/main/java/org/commcare/formplayer/beans/menus/CommandListResponseBean.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/main/java/org/commcare/formplayer/beans/menus/MenuBean.java
- src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
This allows Web Apps to know what the current command is which is
necessary when sending back query data.
This is required after the changes pass `force_manual_action` in the query data:
* https://github.com/dimagi/commcare-hq/pull/31152
* https://github.com/dimagi/formplayer/pull/1097
Related HQ change: https://github.com/dimagi/commcare-hq/pull/31273
Note: must be deployed before or at the same time as the CommCare PR
> include queryKey in EntityList responses

- src/main/java/org/commcare/formplayer/db/migration/V22__create_form_definition.java
- src/main/java/org/commcare/formplayer/objects/SerializableFormDefinition.java
- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
It is better practice to isolate the migration from the code that depends on it, which is currently not the case with https://github.com/dimagi/formplayer/pull/1075. This contains only the migration which is safe to deploy without the related code that makes use of it.
> Create form definition table in Postgres

- src/main/java/org/commcare/formplayer/repo/FormDefinitionRepo.java
- src/main/java/org/commcare/formplayer/services/FormDefinitionService.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/main/resources/application.properties
- src/test/java/org/commcare/formplayer/repo/FormDefinitionRepoTest.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
- src/test/java/org/commcare/formplayer/services/FormDefinitionServiceTest.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/HqUserDetailsServiceTests.java
- src/test/java/org/commcare/formplayer/utils/TestContext.java
[SAAS-13377](https://dimagi-dev.atlassian.net/browse/SAAS-13377)
This is a re-do of https://github.com/dimagi/formplayer/pull/1075 since the commit history got pretty messy. I know this causes an inconvenience to reviewers, but I think the clean commit history is better in the long run. The link to the closed PR will still be available here if more context if needed, but I'll try to summarize everything below. The only difference between this PR and the previous is that this includes the FormDefinitionServiceTest class. Everything else remains the same. I've tested this locally, and plan to run another pass of QA on this to ensure nothing went wrong in creating this new branch.
This PR makes use of the newly added SerializableFormDefinition to store unique form definitions in postgres. A …
> Use shared form definition from postgres

- src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
https://dimagi-dev.atlassian.net/browse/QA-4081
`storageFactory` seems to be injected with scrubbed username sometimes but not always. So doing a euality check by scrubbing both sides of the equation.
> Fixes user equality match

- src/main/java/org/commcare/formplayer/application/AbstractBaseController.java
- src/main/java/org/commcare/formplayer/aspects/ConfigureStorageFromSessionAspect.java
- src/main/java/org/commcare/formplayer/objects/SerializableFormDefinition.java
- src/main/java/org/commcare/formplayer/services/FormDefinitionService.java
- src/main/java/org/commcare/formplayer/services/FormplayerStorageFactory.java
- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
- src/test/java/org/commcare/formplayer/services/FormDefinitionServiceTest.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/SavedFormDefTest.java
- src/test/java/org/commcare/formplayer/utils/TestContext.java
I had to create a new PR since the previous PR was based off of a branch that will no longer be merged. See https://github.com/dimagi/formplayer/pull/1123 for any potentially missing context.
This work is a response to [Clayton's suggestion](https://github.com/dimagi/formplayer/pull/1121#issuecomment-1099297838) to target what specifically we want to optimize. In this case, our main goal is to improve answer timings since a user filling out a form should not have to deserialize a FormDef on every request. This still results in a FormDef being deserialized upon session creation, but that is less likely to experience noticeable gains than answer requests and submission are, since it is an already slower request.
6cd6bc1eb0d9df31a39fc6f17518c4b17cb5f06f is the bulk of this PR, but has a …
> Cache deserialized FormDef by session id

- src/main/java/org/commcare/formplayer/application/DebuggerController.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Companion to https://github.com/dimagi/commcare-hq/pull/31687 which passes query data to FP. These changes will use the query data when replaying the session to ensure correct session state.
> use query data in debugger endpoints

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
This reverts commit ceb34d315553be61dfc76708db303f3101da60cd.
This change caused an issue where input was being added into the selections multiple times: https://dimagi-dev.atlassian.net/browse/QA-4230
Todo: add test case to show the issue
> Revert "move addSelection to handleInput"

- src/main/java/org/commcare/formplayer/db/migration/V25__drop_formxml_column.java
- src/main/java/org/commcare/formplayer/objects/SerializableFormSession.java
- src/test/java/org/commcare/formplayer/repo/FormSessionRepoTest.java
https://dimagi-dev.atlassian.net/browse/SAAS-13595
This column has been replaced with the `form_definition` table via a foreign key, and therefore is no longer needed. Ideally, we will apply this migration but first need to ensure it will not result in excessive disruption for users when rolling out to environments with lots of form sessions. I briefly tested on staging and didn't see any difference between a regular deploy and this, but there are also only 33 form sessions on staging. Next plan is to create a bunch locally and test that way.
> Drop `formxml` column on form sessions

- src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
- src/main/java/org/commcare/formplayer/services/FormplayerRemoteInstanceFetcher.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
Always skip the case search cache when performing the search for the first time in a session. This is determined by looking at two factors:
1. Is this the last item in the list of selections?
* Being the last item means that we aren't replaying navigation but are computing it for the first time
2. Is this a 'details screen' request
* The only exception to # 1 is for 'details requests' which aren't treated as a navigation request so the selections remain the same
This change is intended to prevent users from seeing stale data when performing searches.
Jira: https://dimagi-dev.atlassian.net/browse/USH-2210
> skip case search cache on first request

- src/main/java/org/commcare/formplayer/application/GlobalDefaultExceptionHandler.java
- src/main/java/org/commcare/formplayer/exceptions/FormattedApplicationConfigException.java
- src/main/java/org/commcare/formplayer/services/FormplayerLockRegistry.java
- src/main/java/org/commcare/formplayer/services/InstallService.java
Looking at Sentry today I noticed that there are often 2 or more events for the same 'error'. Sentry is configured to create new events for unhandled exceptions as well as for log events at the 'ERROR' level. In some cases we are logging to ERROR and also raising exceptions or manually capturing the Sentry events which is unnecessary.
I have tried to ensure that there is still useful context being output to the console while reducing the Sentry events.
> logging / sentry changes to reduce multiple events for the same thing

- src/main/java/org/commcare/formplayer/application/UtilController.java
We expect these errors from the 'validate_form' endpoint so there's no need to log them.
> don't log expected errors

- src/main/java/org/commcare/formplayer/session/FormSession.java
- src/main/java/org/commcare/formplayer/util/SessionUtils.java
We hit this almost 10K times per day and it's not a genuine error so dropping from 'error' to 'info'.
The user's locale is set in the settings in CommCare and often doesn't match the locale's available in the app.
Also included is a small simplification to the `SessionUtils.setLocale` method.
> drop error log to info

- src/main/java/org/commcare/formplayer/beans/menus/DisplayElement.java
- src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
- src/test/resources/archives/caseclaim/default/app_strings.txt
- src/test/resources/archives/caseclaim/suite.xml
https://github.com/dimagi/commcare-core/pull/1139
Adds a new attribute `required_msg` to the Formplayer query response to support custom error messaging. This would be `null` when there is no custom message. 
````
{
"displays": [
{
"text": "age",
"id": "age",
…,
"required_msg":  "One of Age or DOB is required"
}
],
"type": "query"
}
````
[QA ticket](https://dimagi-dev.atlassian.net/browse/QA-4342)
> Dynamic required Conditions + Custom Required Messaging

- README.md
Mac users running formplayer outside of Docker (all mac users?) need to remove references to `micrometer` to run formplayer locally. I was reminded of this when helping new devs setup their environments. 
Just a readme change
no QA
> update readme for mac specific issue

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/util/Constants.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
This adds the state hash to the restore URL. This should allow better validation that HQ and formplayer are aligned on the users case DB state.
Initially any errors will only be logged to avoid breaking changes (see https://github.com/dimagi/commcare-hq/pull/32089).
The intention is to surface sync bugs sooner so that they can be fixed.
Once the HQ PR is deployed this should be safe since a state hash mismatch will still not result in an error.
The only question I have is related to the performance of computing the state hash. Is that something we should be concerned about? Perhaps @shubham1g5 @ctsims have more insight.
Tests added to make sure a blank state hash is not included and a non-blank one is included correctly
None
> add state hash to restore URL

- src/main/java/org/commcare/formplayer/aspects/LockAspect.java
- src/main/java/org/commcare/formplayer/services/FormplayerLockRegistry.java
Small refactor and additional sentry events for lock errors.
Currently lock errors are not logged in Sentry at all.
Not covered by tests
I did some basic testing locally.
> [USH-2498] additional logging for lock errors

- .github/workflows/build.yml
- .gitignore
- build.gradle
- gradle.properties
- settings.gradle
The main reason for this is to allow multiple plugin e.g. kotlin
to use the same version
https://github.com/dimagi/formplayer/pull/1231
https://github.com/dimagi/formplayer/pull/1232
build change only, no code change
> move plugin versions to gradle.properties

- src/main/java/org/commcare/formplayer/beans/menus/EntityDetailResponse.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/test/java/org/commcare/formplayer/tests/CasePaginationTests.java
https://dimagi-dev.atlassian.net/browse/USH-2536
[Sentry](https://sentry.io/organizations/dimagi/discover/formplayer:7db9f17eb5274a789549f46dc1bc4497/?environment=production&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=142105&query=domain%3Aco-carecoordination-test&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29)
From the sentry it looks like the owner thread is busy calculating case list fields for the screen.  This PR addresses the performance here by only calculating the entity fields for entities which are part of the current page as we don't really need to calculate fields for entities that we don't show. 
- Probably affect all web apps with paginated entity lists
- Tested on staging to see nothing breaks
We do have coverage …
> Only process entities on current page

- src/main/java/org/commcare/formplayer/util/Timing.java
https://dimagi-dev.atlassian.net/browse/SUPPORT-14952
This adds a 3-second bucket for datadog duration metrics.
Pretty trivial
No
No
> Added 3-second bucket to datadog timings

- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/test/java/org/commcare/formplayer/tests/CasePaginationTests.java
- src/test/resources/requests/navigators/invalid_offset_paginate_navigator.json
Currently when offset is greater than case list size we were crashing with the [exception](https://sentry.io/organizations/dimagi/issues/3677557689/?project=142105&query=is%3Aunresolved). I am not sure why it happens but it seems reasonable to reset offset to the last page when it's off the bounds like this. 
Added an automated test to test for this particular case
No QA
> Invalid offset fix for Cast List Pagination

- src/main/java/org/commcare/formplayer/beans/menus/EntityDetailResponse.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
We were calculating the display properties for Entities on the current page twice. Once as part of [buildEntityList](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java#L225) and then again while [processEntity](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java#L287) to build a `EntityBean`. This PR changes the code to directly take use of `Entity` object evaluated fields to build the `EntityBean`
Mostly relying on unit test coverage
A good number of navigation tests touches and tests over `EntityListResponse`
None
> More optimisations for Entity list performance

- src/main/java/org/commcare/formplayer/configuration/WebSecurityConfig.java
- src/test/java/org/commcare/formplayer/auth/HmacAuthTests.java
Jira: https://dimagi-dev.atlassian.net/browse/USH-2433
Migrate Spring security setup to stop using `WebSecurityConfigurerAdapter` which has been deprecated: https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
This also removes the support for URLs prefixed with double slash. This change was made to the proxy in March 2021: https://github.com/dimagi/commcare-cloud/pull/4584
This is a pure refactor but it is a complex part of the code due to how security is configured so this will be tested on staging before being rolled out.
There are two sets of tests that test this config: `HmacAuthTests` and `SessionAuthTests`.
Mostly passive testing on staging though a few aspects will need specific testing e.g. form validation, SMS forms.
> [USH-2433] security config refactor

- src/test/java/org/commcare/formplayer/junit/HasXPath.java
- src/test/java/org/commcare/formplayer/junit/HasXpath.java
- src/test/java/org/commcare/formplayer/junit/request/EvaluateXpathRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/MockRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/NewFormRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/SubmitFormRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/SyncDbRequest.kt
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
This was prompted by https://github.com/dimagi/formplayer/pull/1285. In order to do better matching of XML responses there are 2 changes:
1. Create a new 'mock request' class for the `evaluate-xpath` request.
This migrates that request to the new 'framework' and makes it possible to use
result matchers on the response.
2. Create a Hamcrest Matcher for doing xpath matching on strings (the existing ones only operate on XML documents)
Only impacts unit tests.
> xpath mock request for testing

- src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
- src/test/resources/archives/case_claim_with_multi_select/modules-1/forms-0.xml
https://dimagi-dev.atlassian.net/browse/USH-2790
Corrects instance reference as per the instanceId given while reading the instance from the guid. 
- We have a good coverage on unit tests around virtual instances workflows
- It's a no-op for old reference scheme which is currently used 
PR adds tests to verify the problematic behaviour this change is targetted towards. 
Will be QA'ed as part of https://dimagi-dev.atlassian.net/browse/USH-2084 in 
https://dimagi-dev.atlassian.net/browse/QA-1096
cross-request: https://github.com/dimagi/commcare-core/pull/1211
> Dynamically Correct virtual instance reference

- src/main/java/org/commcare/formplayer/objects/SerializableDataInstance.java
- src/main/java/org/commcare/formplayer/services/FormplayerRemoteInstanceFetcher.java
- src/main/java/org/commcare/formplayer/services/VirtualDataInstanceService.java
- src/test/java/org/commcare/formplayer/services/VirtualDataInstanceServiceTest.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/FormEntryWithQueryTests.java
https://dimagi-dev.atlassian.net/browse/QA-4784
The [core fix here](https://github.com/dimagi/formplayer/commit/c49da5d13da21a7c4bd496180003047a69be6f4a) is to use reference id (same as datum id) instead of instance id to construct instance reference when loading the instance from storage. This issue was introduced by https://github.com/dimagi/formplayer/pull/1315/files for new instance reference scheme. 
PR adds a [test](https://github.com/dimagi/formplayer/commit/cf261d803cd7001472503378a457e19e20a51534) to check for search input instance loading correctly from storage by re-running same request twice. 
https://dimagi-dev.atlassian.net/browse/QA-4784
cross-request: https://github.com/dimagi/commcare-core/pull/1221
> Fixes loading Search Input Instance from storage

- src/main/resources/application.properties
This set the size limit for multipart file uploads and a slightly higher limit for multipart request to correspond with limit set [here](https://github.com/dimagi/formplayer/blob/saveMediaAttachment/src/main/java/org/commcare/formplayer/services/MediaValidator.kt#L13.).
As discussed [here](https://dimagi-dev.atlassian.net/browse/QA-4794#:~:text=The%20issue%20I,his%20sign%20off.) only files of 1MB or smaller are able to be uploaded currently.
part of https://dimagi-dev.atlassian.net/browse/QA-4739
> set multipart file size limit

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
- src/main/java/org/commcare/formplayer/beans/menus/CommandListResponseBean.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/junit/Installer.kt
- src/test/java/org/commcare/formplayer/junit/StorageFactoryExtension.kt
- src/test/java/org/commcare/formplayer/junit/request/EvaluateXpathRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/MockRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/NewFormRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/Response.kt
- src/test/java/org/commcare/formplayer/junit/request/SessionNavigationRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/SubmitFormRequest.kt
- src/test/java/org/commcare/formplayer/junit/request/SyncDbRequest.kt
- src/test/java/org/commcare/formplayer/tests/BackNavigationTests.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
Jira: https://dimagi-dev.atlassian.net/browse/USH-2620
See HQ PR for full description: https://github.com/dimagi/commcare-hq/pull/32575
HQ cross request: https://github.com/dimagi/commcare-hq/pull/32575
Detect the presence of a 'form_session_id' during a navigation request and act appropriately. If the session ID is present it implies that the user has performed some non-app based navigation such as going back in the browser history.
When this is detected, attempt to navigate to the previous screen prior to form submission.
The first few commits are cleanups, only the last commit is a functional change.
Assuming the HQ portion of this change is working correct and the form_session_id param is properly cleared after form submission, this should only impact manual navigation.
TODO
QA on …
> [USH-2620] improved 'back' navigation after form submissions

- .github/gradle.properties.ci
- .github/workflows/build.yml
- README.md
- build.gradle
This PR upgrades Java to version 17.
cross-request: https://github.com/dimagi/commcare-core/pull/1198
These changes are going to be subjected to Regression testing by the QA team.
- Ensure that Java 17 is installed
- Remove any references to JVM parameters _MaxPermSize_ or _PermSize_ from the environment configuration, these usually live in the _gradle.properties_ file. These options have been [removed in Java 17](https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options)
> Sets Java source and target to version 17

- Dockerfile
This updates the image's Dockerfile to use Java 17 instead of 8.
> Update Dockerfile to use JRE 17

- scripts/rebuildstaging
Once I added formplayer-staging.yml to staging-branches, the git show logic had the potential to show a diff in the formplayer-staging.yml when rebuilding the commcare-hq staging branch (or vice versa), which is confusing.
This ensures we grab the most recent commit to the `formplayer-staging.yml` file in staging-branches, and show that diff to the user.
> Show the most recent commit diff to the respective staging file

- README.md
* By default Intellij uses the "Application" template to create run configs which does not work.
* Add instructions to the readme on how to create a working "JAR Application" run configuration.
Just updating the readme
Only documentation changes. No tests required
Only documentation changes. No tests required
Only documentation changes. No tests required
> Add how to create run config to readme

- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
Add `hasDetails` attribute to entity list response to allow Web Apps to skip the details request when there is no 'long detail' configured.
Cross: https://github.com/dimagi/commcare-core/pull/1280
Adds `hasDetails` to the entity list response. 
Simple addition of one field.
Tested locally
> add 'hasDetails' to EntityListResponse

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/CasePaginationTests.java
- src/test/resources/archives/multi_select_case_list/suite.xml
- src/test/resources/requests/navigators/search_navigator_2.json
- src/test/resources/restores/ccqa.xml
https://dimagi-dev.atlassian.net/browse/SUPPORT-16768
There were some places in code that were passing the incorrect EntityContext to entity screen. This code pathway was triggered when there in auto computed datum present first before the nodeset datum. I have made the changes to pass in right entityContext to the session navigation code and also removed some methods which were re-initialising Entity context in order to lessen probability of us making a similar mistake again. 
Mostly ensuring safety through tests and local testing
PR adds a regression test to verify the behaviour
Not planned
> Fix Incorrect Entity Context Attached to Entity Screen

- src/main/java/org/commcare/formplayer/util/RequestUtils.java
- src/main/java/org/commcare/formplayer/web/client/WebClient.java
https://dimagi-dev.atlassian.net/browse/USH-3093
Probably all the complexity here is in to get the IP address from the request. I am using the header "X-FORWARDED-FOR" to get the IP with a fall back to the `request.getRemoteAddr()` . I am assuming that `"X-FORWARDED-FOR"  will always be there when requests are forwarded from Nginx but we probably need to cross-check that assumption on HQ. 
Testing form submission locally and on staging should be a good enough safety check. 
No QA
> Add IP address to post requests to HQ

- src/main/java/org/commcare/formplayer/util/RequestUtils.java
- src/main/java/org/commcare/formplayer/web/client/WebClient.java
https://dimagi.sentry.io/issues/4080192544/?query=is%3Aunresolved+Parameter+specified+as+non-null+is+null&referrer=issue-stream&statsPeriod=14d&stream_index=0
This was missed on code review on https://github.com/dimagi/formplayer/pull/1391
Small fixes for a bug along with a safety check to ensure it can't happen.
None
> Avoid adding a null value to the request headers

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
- src/test/resources/archives/caseclaim/suite.xml
Since the entity list reponse is constructed using the entity screen class now, we need to initialise the entity screen fully after eof navigation to make sure that entities gets constructed properly when we are navigating to a case list after eof navigation. 
https://dimagi-dev.atlassian.net/browse/USH-3325
Regression of https://github.com/dimagi/formplayer/pull/1384
Regression fix with test coverage, code path is limited to apps using eof navigation
No
> Fixes entity list initialization after eof navigation

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/test/resources/archives/caseclaim/suite.xml
[Issue](https://dimagi-dev.atlassian.net/browse/USH-3325?focusedCommentId=271078)
https://github.com/dimagi/formplayer/pull/1384 resulted in an unintended consequence where after eof navigation we were always initialising the normal entity screen (not case search) even when the screen is going to auto-launch to entity screen. This resulted into an issue where if `instance('results')` is used for one of the detail fields for entity screen, it caused a `XPathMissingInstanceException` due to instance('results') not being available for the normal entity screen. 
This PR makes a change to only initialise entityListSubscreen and in turn the detail fields for the entity if we are not going to auto-launch to another screen.
Relying on existing tests around EOF Navigations along with adding a test …
> Handle auto launch better in EOF navigation

- src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java
related to cc-core PR: https://github.com/dimagi/commcare-core/pull/1320
merge before https://github.com/dimagi/commcare-core/pull/1320
if reverted, also revert https://github.com/dimagi/commcare-core/pull/1320
> Revert "rc/results-title-response"

- build.gradle
- src/main/java/org/commcare/formplayer/objects/QueryData.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
remove backward compatibility flag introduced as part of the [spec](https://docs.google.com/document/d/1Xtly4YfrdaB1w1Ozwlwy9LQ4JIrVRmhvg-44-Rl-z6A/edit) as all response to FP should have it set to `true` now. 
Removes a obsolete flag
tested on staging. 
Updated tests in the PR to test for new behaviour
No QA
cross-request: https://github.com/dimagi/commcare-core/pull/1325
> Remove obsolete backward compatibility flag for case search dropdowns

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/resources/archives/case_claim_with_multi_select/suite.xml
Adds support for smartlinking inline case search modules as per the [spec here](https://docs.google.com/document/d/1owt1WE91-8jF7yUnzlbk5jB0YC8Uqeg3I3yTQy5vuVo/edit#heading=h.d9dq3mdn6f9n)
[HQ PR](https://github.com/dimagi/commcare-hq/pull/33461) and [Core PR](https://github.com/dimagi/commcare-core/pull/1328)
The [main technical change](https://github.com/dimagi/formplayer/pull/1454/commits/d38c9a1c204a698d2773ea4b8895109b06ba7a8d) in the PR is to make the `selected_cases` instance available to the endpoint stack right after argument processing. This is so that we can use the `instance('selected_cases`)` expressions in the endpoint stack itself. 
- Should only affect session endpoint workflows which has wide enough test coverage for different workflows
- Locally tested …
> Inline Case Search Endpoint Support

- src/main/resources/application.properties
This is mostly for convenience in dev to reduce the amount of verbose logs.
Change to default application properties which to configure logging should not have any impact in production.
None
> set default log levels

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
[Sentry](https://dimagi.sentry.io/issues/4477380077/?project=142105&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)
[Jira](https://dimagi-dev.atlassian.net/browse/SUPPORT-17607)
Corresponding FP fix for https://github.com/dimagi/commcare-core/pull/1334
Retains old code for stack query extras processing which should already have been working.
Good test coverage to check for the core worflow around stack query datums.
> Backward compatibility fix for query extras

- src/main/java/org/commcare/formplayer/beans/menus/EndpointActionResponse.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/test/java/org/commcare/formplayer/tests/EndpointActionsTest.kt
- src/test/resources/archives/multi_select_case_list/suite.xml
Adds endpoint Action in entity list response as per [spec here](https://docs.google.com/document/d/1coxsFVCYgaQdxE3rgYikRSgEgistrfIUJuoW5KMiM5w/edit#heading=h.l8jcjx2lzmxy)
The change itself is no-op since it only adds endpoint action properties to the entity list response
Covered with a new test
None
cross-request: https://github.com/dimagi/commcare-core/pull/1342
> Returns endpoint actions in entity list response

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityDetailListResponse.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
[Jira](https://dimagi-dev.atlassian.net/browse/USH-3776)
Adds support for getting short detail for a case in `get_details` endpoint by setting a flag `is_short_detail` to `true`
Required to refresh a single case DB row after performing a [clickable action](https://docs.google.com/document/d/1coxsFVCYgaQdxE3rgYikRSgEgistrfIUJuoW5KMiM5w/edit#heading=h.yq5vabwe65r7)
Changes are isolated to `is_short_detail` being `true`
PR adds a test for new behaviour with tests for old behaviour already present
None
> Supports getting short detail in `get_details` endpoint

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/test/java/org/commcare/formplayer/tests/AutoFormSubmissionTest.kt
- src/test/resources/archives/multi_select_case_list/suite.xml
Adds auto form submission handling to get_endpoint so that the form gets submitted in the same request as get_endpoint
Only affects endpoint launches which has good test coverage 
[Covered in endpoint tests](https://github.com/dimagi/formplayer/blob/master/src/test/java/org/commcare/formplayer/tests/EndpointLaunchTest.java)
None
Review commit by commit as there are some indentation changes in a commit
> Fixes endpoint launch for auto form submission

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
- src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
https://dimagi-dev.atlassian.net/browse/QA-5771
Fixes issue where get_details request doesn't give latest data after performing a case change using clickable icon due to cache search cache not refreshing.
Adds a flag called `is_refresh_case_search` to request beans and clear cache search cache if it's set to `true`
Should only affect clickable icons feature when we set the `isRefreshCaseSearch` to true for `get_details`
PR adds a test to verify new bheaviour
None
> Clickable Icons: Clear cache search cache for get_details request based on a request flag

- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
Part of https://dimagi-dev.atlassian.net/browse/USH-3867
Add new translation string to the set of translations set down to Web Apps.
Necessary for https://github.com/dimagi/commcare-hq/pull/33790
This is pretty trivial.
unlikely
not requesting QA
> Added new clear upload translation to web apps

- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
Followup for https://dimagi-dev.atlassian.net/browse/USH-3867
Translations were available only in the new form response. This meant they **weren't** available to questions shown after the form initially loaded, when a display condition switched from false to true, because that data comes from an `answer` response. This PR moves translations from `NewFormResponse` to `BaseResponseBean` so they're available on `answer` responses.
Bug fix with a fairly small blast radius. Tested locally.
I don't think so
not requesting QA
> Added translation population to answer requests

- src/test/java/org/commcare/formplayer/junit/InitializeStaticsExtension.java
- src/test/java/org/commcare/formplayer/junit/RestoreFactoryExtension.kt
- src/test/java/org/commcare/formplayer/junit/StorageFactoryExtension.kt
- src/test/java/org/commcare/formplayer/junit/request/SessionNavigationRequest.kt
- src/test/java/org/commcare/formplayer/tests/CaseListLazyLoadingTests.kt
- src/test/java/org/commcare/formplayer/tests/EndpointActionsTest.kt
- src/test/resources/archives/case_claim_with_multi_select/suite.xml
Tests for https://github.com/dimagi/commcare-core/pull/1388
(Skipping PR Template as there are no functional code changes)
> Basic test for lazy loading Case Lists

- src/main/java/org/commcare/formplayer/objects/QueryData.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
Removes fallback that was added in https://github.com/dimagi/formplayer/pull/1495/files to maintain backward compatibility with older API versions. 
This fallback was added to support compatibility between live sessions before and after deploy and removing this should not result in any functional changes. 
Tests with new query key was added as part of [original PR ](https://github.com/dimagi/formplayer/pull/1495/)
None
> remove query key fallback

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
Prompted by [the issue here](https://docs.google.com/document/d/1y-G9PH3c3FFupRawIYTeaX_cehc-hGHQomu1BwnB3gY/edit#heading=h.7vsnlyupdpde)
When shifting from page 1 to page 2 of a case list backed by case search, we currently redo case search request because of `skipCache` set to true. (This is a side effect of [the fix](https://github.com/dimagi/formplayer/pull/1172) that was implemented for https://dimagi-dev.atlassian.net/browse/USH-2171.)  This PR makes a change so that if we are not requesting the first page of the entity list, we keep `skipCache` set to `false` and not redo the case search. 
Caveating that a better solution here can be for Web Apps to send a flag in the request say 'pageChange` based on which FP can know that it was only a page change from user end and it should not …
> Do not skip cache for page changes

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/beans/ResponseMetaData.java
- src/main/java/org/commcare/formplayer/beans/menus/BaseResponseBean.java
- src/main/java/org/commcare/formplayer/services/InstallService.java
- src/main/java/org/commcare/formplayer/services/ResponseMetaDataTracker.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/utils/TestContext.java
Adds metadata in request response  to indicate if the request went through a restore or app install
This is to help in adding visibility to requests that takes more than normal time once in a while. 
Locally tested
No
> Adds metadata in request response 

- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
Jira ticket: https://dimagi-dev.atlassian.net/browse/USH-3859
Related HQ PR: https://github.com/dimagi/commcare-hq/pull/33976
Related cc-core PR: https://github.com/dimagi/commcare-core/pull/1396
tested locally and will test on staging
tests in cc-core PR 
no QA planned
> add select text to entity list response

- src/main/java/org/commcare/formplayer/objects/QueryData.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/util/Constants.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
Adds a `module_initiated_by` tag to Datadog. This value is passed by HQ to signify what initiated the query. Specifically in this case, we are interested in queries triggered via user search input for case search. These will be tagged as `field_change`.
This additionally includes `module_name` tags for requests tagged as `case_search` module 
[Commcare HQ ](https://github.com/dimagi/commcare-hq/pull/34006)
[Jira Ticket](https://dimagi-dev.atlassian.net/browse/USH-4051)
Locally tested and tested on staging
no QA
> Adds DD tag for Case Search Input

- src/main/java/org/commcare/formplayer/application/UtilController.java
Written by @Robert-Costello 
P2 ticket: https://dimagi.atlassian.net/browse/USH-4181
Adds to what is cleared when syncing user data as a workaround for stale data in case search. (now if stale data is shown they can clear user data to see the updated results)
This has been tested on staging by support, tech, and delivery members
No QA has been requested
> Clear case search db when clearing user data

- src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
- src/test/java/org/commcare/formplayer/tests/CaseSearchResultsInStorageTests.java
This is the minimal fix and test for the issue described in https://dimagi.atlassian.net/browse/USH-4181
Note that there is scope for future changes to improve this further:
* move the init code to the storage classes and only clear the data if the tables already exist
* review whether skipping the mark rewind for auto-launch case lists is desirable. I believe we could adjust the 'selections' (by adding the action selection) after the first auto-launch so that future replays would be forced to follow the case search path.
* consider per session IDs stored in the stack which could be included in the cache key. The life-cycle of these IDs would need to be carefully considered
Ensure case search storage is cleared before loading new data.
Clear the case search tables before parsing new data …
> clear search data before parsing

- src/main/java/org/commcare/formplayer/beans/menus/EntityBean.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityDetailResponse.java
- src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java
- src/test/java/org/commcare/formplayer/tests/CaseListLazyLoadingTests.kt
Adds icon altText to EntityListResponse and EntityDetailResponse to be used by case list icons/clickable icons.
[USH-3933](https://dimagi.atlassian.net/browse/USH-3933)
https://github.com/dimagi/commcare-hq/pull/34044
https://github.com/dimagi/commcare-core/pull/1399
`altText` is a list of strings which correspond by index to the entity's `data` or `details` property, e.g.:
```
"entities": [
{
"altText": [null, null, "gold star"],
"data": ["Name", "DOB", "jr://file/favorite_star.png"],
...
}
]
```
or
```
"details": [
{
"altText": [null, null, "gold star"],
"details": ["Name", "DOB", "jr://file/favorite_star.png"],
...
}
]
```
Codecov says these are covered by existing tests, but happy to add if needed.
QA with the other linked PRs.
This should be deployed before or alongside …
> Alt text for icons

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/aspects/MetricsAspect.java
- src/main/java/org/commcare/formplayer/beans/SessionNavigationBean.java
- src/main/java/org/commcare/formplayer/objects/QueryData.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/util/Constants.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
For the metric `formplayer.metrics.timings`
-  Datadog tag `module_initiated_by` is renamed to `request_initiated_by`.
- `app_name` tag is added
- `module_name` tag is included when `navigate_menu` enters a menu
TODO: Add screenshot
[Jira Ticket ](https://dimagi.atlassian.net/browse/USH-4182)
[Related HQ Changes](https://github.com/dimagi/commcare-hq/pull/34247)
This PR consists of two changes:
1. The `module_initiated_by` tag was introduced previously in this [PR](https://github.com/dimagi/formplayer/pull/1533). This tag will be renamed to a more general `request_initiated_by`. This name better reflects that the tag reflects the user action that resulted in the request. 
2. The `request_initiated_by` value is moved from `QueryData` to `SessionNavigationBean` as the values are no longer …
> Datadog Metric Slicing

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/services/ResponseMetaDataTracker.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/util/Constants.java
- src/main/java/org/commcare/formplayer/util/FormplayerDatadog.java
For the metric `formplayer.metrics.timings`
- Datadog tag `category` is separated into multiple tags that are in the form `request_includes_<action>` with the value "true" if applicable. For example, `category` with the value `app_install` will now be the tag `request_includes_app_install` with the value `true`.
- Adds `request_includes_autoselect` tag
For the metric `formplayer.metrics.granular.timings`
- for `category` `complete_restore`: adds associated tag for `module_name` and `request_includes_autoselect`
- adds `category` `form_entry` with associated tag for `form_name` and `request_includes_autoselect`
[Jira Ticket](https://dimagi.atlassian.net/browse/USH-4243)
The `category` tag was introduced previously to metric `formplayer.metrics.timings` from this …
> Datadog Improve Metric Fidelity for Autoselect

- src/main/java/org/commcare/formplayer/application/FormSubmissionHelper.java
- src/main/java/org/commcare/formplayer/services/CategoryTimingHelper.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
This PR does two things: 
- Displays errors while rebuilding session from frame that were previously caught but not displayed. Namely, errors resulting from end of form navigation but that is not the only feature where rebuilding session is done.
- Adds error handling for when no matches are found between steps and menu options.
[Jira Ticket](https://dimagi.atlassian.net/browse/USH-4176)
tested locally, will test on staging
Basic end of form navigation tests exists and the response is as expected
no QA
> End of Form Error Handling

- .github/workflows/build.yml
Dependabot PRs are failing builds since they [no longer have access to the secrets](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). This change skips codecov step for dependabot PRs or for any PRs that don't have access to the repo secrets. 
Build only
> Disable codecov when PRs don't have access to secrets

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
Context:
This https://github.com/dimagi/formplayer/pull/1560 introduces validation during session rebuilding. If there's a discrepancy during this process, it will now raise an exception and show an error to the user. Before this PR, the session would simply revert to the last valid step without raising any exceptions. In terms of End of Form (EoF), this means the user would be directed to the last valid screen without any error prompts.
Issue:
There were previously working EoF navigation configurations that are now displaying an error and blocking the app workflow.
It is currently unknown what specifically about those app configurations are conflicting with this error check. However, due to the urgency, this change logs the error instead of blocking the app. The logging will aid in …
> Log instead of blocking app for EoF errors

- src/main/java/org/commcare/formplayer/util/StringUtils.java
https://dimagi.atlassian.net/browse/USH-4497
Users now can login as web users which already have the complete username used for couch. Do not append domain and host it that case. Without this change the claim-case request has a non-existing username in the body and will fail silently.
We do the same in hq: https://github.com/dimagi/commcare-hq/pull/34351/files#diff-b5520648dffd5a4f57530e5e1c36f90cd022db2cbf59bfef9bb3d65997d6f316R64-R74
> USH-4497: Do not append domain to username with @

- src/main/java/org/commcare/formplayer/api/json/JsonActionUtils.java
- src/main/java/org/commcare/formplayer/api/json/PromptToJson.java
- src/main/java/org/commcare/formplayer/application/FormController.java
- src/main/java/org/commcare/formplayer/beans/QuestionBean.java
- src/main/java/org/commcare/formplayer/beans/RepeatRequestBean.java
- src/main/java/org/commcare/formplayer/session/FormSession.java
- src/test/java/org/commcare/formplayer/tests/BaseTestClass.java
- src/test/java/org/commcare/formplayer/tests/RepeatTests.java
- src/test/resources/xforms/nested_repeat.xml
[JIra](https://dimagi.atlassian.net/browse/USH-4333)
Adds support for using both counted and non counted repeat groups in a single form on Web Apps.
[Spec](https://docs.google.com/document/d/1j8NKF3nC3uZkcyqBiShZafOItPXQv-pdi3t783SK1G0/edit)
- Will go through QA once supporting changes are done on Web Apps
- Unit tests are added to verify non counted repeat groups work correctly, there should not be any other impact of removing the non linear repeat strucuture
- Added in PR
[Notes here](https://docs.google.com/document/d/1j8NKF3nC3uZkcyqBiShZafOItPXQv-pdi3t783SK1G0/edit#heading=h.2m1ur8dtdbed)
[QA ticket](https://dimagi.atlassian.net/browse/QA-6548)
Should only be deployed after the corresponding Web Apps changes are deployed 
cross_request: …
> Linear Repeat Structure Support for Formplayer

- src/main/java/org/commcare/formplayer/application/MenuController.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/test/java/org/commcare/formplayer/junit/Installer.kt
Minor performance optimisation in session eval code. Earlier we were calculating the final screen in session navigation twice, once while processing the selection as part of [session advance](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java#L369) and then again while calling [getNextMenu](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java#L153). 
This PR makes a simple change to avoid this re-calculation if we can utilise the existing screen again. 
- Good test coverage arounf this code
- Did basic testing on staging, will let it go through a few round of QA automated tests as well.
No
> Avoid Re-calculating next screen again if we can

- src/main/java/org/commcare/formplayer/api/json/PromptToJson.java
- src/test/java/org/commcare/formplayer/tests/RepeatTests.java
- src/test/resources/xforms/repeat.xml
https://dimagi.atlassian.net/browse/USH-4710
Adds ability to specify custom captions for repeat groups. 
[Spec](https://docs.google.com/document/d/1hQnoQadLpK-SVf2OMtcCm75yjLBPRT7IWjhZpJWcNoc/edit)
We have test coverage to check for add captions that this PR changes in accordance to new behaviour. 
Not planning
cross-request: https://github.com/dimagi/commcare-core/pull/1428
> Custom Repeat Captions Support

- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/tests/CaseClaimNavigationTests.java
- src/test/java/org/commcare/formplayer/tests/EndpointLaunchTest.java
- src/test/java/org/commcare/formplayer/utils/MockRequestUtils.java
- src/test/resources/archives/case_claim_post_in_entry/default/app_strings.txt
- src/test/resources/archives/case_claim_post_in_entry/suite.xml
- src/test/resources/archives/endpoint/suite.xml
Navigating to form’s smartlink lands the user all the way to the form’s defined End of Form instead of to the form. This PR fixes that and lands the user at the defined smartlink form.
[USH-3901](https://dimagi.atlassian.net/browse/USH-3901) and [USH-5001](https://dimagi.atlassian.net/browse/USH-5001)
The problem is that on advanceSessionWithEndpoint → executeAndRebuildSession, [ops](https://github.com/dimagi/commcare-core/blob/d09e72adeab33cff86a324da2fa0d542a62bf2c3/src/main/java/org/commcare/session/CommCareSession.java#L880) contain the stack operation of EoF nav and this is being executed. 
The solution here depends on the fact that only the last stack defined in the `<endpoint>` stack definition defines the navigation. While the stacks prior define only case claim. Meaning that when …
> Fix Smartlink with End of Form Navigation Compatibility

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/test/java/org/commcare/formplayer/tests/CaseListAutoSelectTests.kt
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
- src/test/resources/archives/case_claim_with_multi_select/profile.ccpr
- src/test/resources/archives/case_list_auto_select/profile.ccpr
- src/test/resources/archives/case_list_auto_select/suite.xml
- src/test/resources/archives/multi_select_case_list/suite.xml
https://dimagi.atlassian.net/browse/USH-5045
Fixes an issue where a reference to case list auto-selection will get added to the persistent menu and breadcrumbs. This only happens in case search and claim workflows. 
With case search and claim, we were triggering `auto-selection` on the case list with the `handleInput` method when `autoselectEntities()` is a better method to do so as it skips un-needed handling like adding a reference to persistent menu/ breadcrumbs. 
- Added tests  for persistent menus around various auto-select and auto-advance workflows
- Will test the exact workflow on staging before deploy. 
NA
> Persistent menu auto select fix

- src/main/java/org/commcare/formplayer/session/PersistentMenuHelper.kt
- src/test/java/org/commcare/formplayer/mocks/FormPlayerPropertyManagerMock.java
- src/test/java/org/commcare/formplayer/tests/AutoAdvanceMenuInNestedMultiSelectList.kt
- src/test/java/org/commcare/formplayer/tests/EndpointLaunchTest.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
https://dimagi.atlassian.net/browse/USH-5045?focusedCommentId=353249
In some cases involving case search and claim, we run the call to `getNextScreen` multiple times which can result into peristent menu having duplicate entries. This change ensures uniqueness of persistent menu items by adding a `exists` check before `add` . 
Relying on tests and staging testing
Added with the PR
No QA
> Ensure Unique Menu Entries in Persistent Menu

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/test/java/org/commcare/formplayer/tests/CaseListAutoSelectTests.kt
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
- src/test/resources/archives/case_claim_with_multi_select/profile.ccpr
- src/test/resources/archives/case_list_auto_select/profile.ccpr
- src/test/resources/archives/case_list_auto_select/suite.xml
- src/test/resources/archives/multi_select_case_list/suite.xml
[Jira Ticket](https://dimagi.atlassian.net/browse/USH-5100)
Reverting to fix an issue with `instance('selected_cases')` leading to too many cases being selected. 
Tested on staging and confirmed with Delivery.
> Revert persistent menu auto select bug fix and related tests

- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/session/MenuSession.java
- src/test/java/org/commcare/formplayer/tests/CaseListAutoSelectTests.kt
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
- src/test/resources/archives/case_claim_with_multi_select/profile.ccpr
- src/test/resources/archives/case_list_auto_select/profile.ccpr
- src/test/resources/archives/case_list_auto_select/suite.xml
- src/test/resources/archives/multi_select_case_list/suite.xml
Alternate implementation for skipping auto-select menu from contextual menus
[Original PR](https://github.com/dimagi/formplayer/pull/1638/files)
[Revert PR](https://github.com/dimagi/formplayer/pull/1642)
[Jira](https://dimagi.atlassian.net/browse/USH-5121)
Reverts [original solution](https://github.com/dimagi/formplayer/pull/1638) implemented in favor of a simple check before adding the entity list menu to contextual menus. 
In addition to the unit test, I tested the correspondix fix on staging as per the steps outlined in [this comment](https://dimagi.atlassian.net/browse/USH-5100?focusedCommentId=354489). 
PR adds a regression test for the issue that caused the revert. 
None
> Reinstate auto select revert

- src/main/java/org/commcare/formplayer/application/FormSubmissionHelper.java
This results in the following difference:
vs
The first example doesn't seem ideal to display to users. I believe `getResponseBodyAsString` should be sufficient to display the error to the user with enough information to take action or get help. 
This only impacts general errors on form submissions. I would assume that if a typical user comes across an error like this, they would be overwhelmed and potentially not even see the useful part of the message.
The risk is that we return errors with empty messages, in which case it will render like this:
Perhaps including the http status code at the very least would be helpful in the event the user receives an empty error message and reports it to us.
> Simplify default error message

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/util/UserUtils.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
- src/test/java/org/commcare/formplayer/tests/UserUtilsTests.java
- src/test/resources/restores/location_update1.xml
- src/test/resources/restores/location_update2.xml
- src/test/resources/restores/location_update3.xml
- src/test/resources/restores/location_update4.xml
Resolves a bug in which users were being shown cases that belonged to locations the user was not assigned to. In the specific reported scenario, users were initially assigned to a parent location (Organization) and then assigned to a child location (Facility) but still being shown all cases belonging to children of the parent location. This turned out to be happening because when a user data sync is triggered every five minutes (or at least five minutes after the last sync - they are currently using both the `cc-skip-fixtures-after-submit` and `cc-sync-after-form` custom properties), `shouldPurge` is always set to false, so even scenarios in which users switched between child locations were also accumulating cases belonging to locations they were previously assigned to. 
All this does it …
> Purge old cases more often

- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
[Fix for this bug](https://dimagi.atlassian.net/browse/SUPPORT-23193)
I put in the condition `!oldSandboxLocations.isEmpty()` mostly so tests can pass but forgot that first time users won't even have that field initialized before calling `parseIntoSandbox` for the first time. This makes sure that that field isn't null. 
Tested locally.
> Check that oldSandboxLocations is not null for first time app users

- src/main/java/org/commcare/formplayer/application/FormSubmissionHelper.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/main/java/org/commcare/formplayer/services/NewFormResponseFactory.java
- src/main/java/org/commcare/formplayer/services/RestoreFactory.java
- src/main/java/org/commcare/formplayer/util/FormplayerPropertyManager.java
- src/test/java/org/commcare/formplayer/junit/RestoreFactoryExtension.kt
- src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java
- src/test/java/org/commcare/formplayer/tests/CaseSearchResultsInStorageTests.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseListTest.java
- src/test/java/org/commcare/formplayer/tests/RestoreFactoryTest.java
- src/test/java/org/commcare/formplayer/utils/MockRequestUtils.java
This feature is no longer used
The `cc-skip-fixtures-after-submit` feature is no longer used. This removes the code associated with it.
https://dimagi.atlassian.net/browse/USH-5376
> Remove cc-skip-fixtures-after-submit code

- src/main/java/org/commcare/formplayer/services/MediaValidator.kt
- src/test/java/org/commcare/formplayer/tests/MediaCaptureTest.kt
Allows users to upload a variety of file types (docx, xlsx, txt, rtf, html, msg), without formplayer complaining that they're invalid.
[Jira ticket](https://dimagi.atlassian.net/browse/USH-5366)
This is just the formplayer side changes. HQ PR to follow.
Tested locally and on staging
> Add more supported filetypes

- src/main/java/org/commcare/formplayer/application/FormSubmissionController.java
- src/main/java/org/commcare/formplayer/application/FormSubmissionHelper.java
- src/main/java/org/commcare/formplayer/util/Constants.java
No user facing changes
Continuation of https://github.com/dimagi/formplayer/pull/1697
[USH-5896](https://dimagi.atlassian.net/browse/USH-5896)
This is to aid in investigating increases to submit-all timings. This PR adds timing to the high level `processAndSubmitForm` function and raises a warning on Sentry if the timing exceeds 5 seconds (typically the threshold for where we consider performance in the unacceptable range). The sentry issue will include breadcrumbs of other subtimings.
These specific timings can most likely be removed once its confirmed to not be large contributors to performance.
Tested on staging. There is no functional change, only addition of timing.
no QA
[USH-5896]: https://dimagi.atlassian.net/browse/USH-5896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
> Add Timing for high level Submit Form and Report Long timing to Sentry

- src/main/java/org/commcare/formplayer/services/CaseSearchHelper.java
- src/main/java/org/commcare/formplayer/services/MenuSessionFactory.java
- src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java
- src/test/java/org/commcare/formplayer/mocks/FormPlayerPropertyManagerMock.java
- src/test/java/org/commcare/formplayer/tests/CaseSearchResultsInStorageTests.java
- src/test/java/org/commcare/formplayer/tests/MultiSelectCaseClaimTest.java
- src/test/resources/query_responses/case_search_multi_select_response.xml
[See CC-core PR](https://github.com/dimagi/commcare-core/pull/1488)
This PR is in coordination with this [commcare-core PR](https://github.com/dimagi/commcare-core/pull/1488)
locally tested. This PR change only creates a getter and setter function.
No automated test
[QA-7869](https://dimagi.atlassian.net/browse/QA-7869)
This PR is in coordination with the [commcare-core PR](https://github.com/dimagi/commcare-core/pull/1488) so if this is reverted, that one will also need to be reverted.
[QA-7869]: https://dimagi.atlassian.net/browse/QA-7869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Inline Case Search Breadcrumb Display Bug Fix
